post:
  tags:
    - Feature Configs
  summary: Create or update feature configs.
  description: |
    This API allows you to create or update feature configs.
  operationId: feature_configs_bulk_post
  requestBody:
    required: True
    content:
      application/json:
        schema:
          type: object
          additionalProperties: False
          required:
            - data
          properties:
            data:
              type: array
              items: 
                $ref: '../../components/schemas/feature_configs.yaml#/feature_config_spender_in'
  responses:
    '200':
      description: OK
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '../../components/schemas/bulk_error.yaml'
              - type: object
                properties:
                  error:
                    type: string
                    nullable: true
                  message:
                    type: string
                    nullable: true
                  data:
                    type: object
                    nullable: true
    '401':
      description: Unauthorised request
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/401.yaml"
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/403.yaml"
                

