get:
  tags:
    - Employee Settings
  summary: Get Employee Settings
  operationId: employee_settings_get
  description: |
    Get employee settings for the authenticated user.
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            required:
              - data
              - count
              - offset
            properties:
              count:
                $ref: '../../components/schemas/count.yaml'
              offset:
                $ref: '../../components/schemas/offset.yaml'
              data:
                type: array
                items:
                  $ref: '../../components/schemas/employee_settings.yaml#/spender_employee_settings_out'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/400.yaml'
    '401':
      description: Unauthorized request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/401.yaml'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/403.yaml'

post:
  tags:
    - Employee Settings
  summary: Update Employee Settings
  operationId: employee_settings_post
  description: |
   Update employee settings for the authenticated user.
  requestBody:
    required: true
    content:
      application/json:
       schema:
          type: object
          required:
            - data
          properties:
            data:
              $ref: '../../components/schemas/employee_settings.yaml#/spender_employee_settings_in'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            required:
              - data
            properties:
              data:
                $ref: '../../components/schemas/employee_settings.yaml#/spender_employee_settings_out'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/400.yaml'
    '401':
      description: Unauthorized request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/401.yaml'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/403.yaml' 