post:
  tags:
    - Page Configurations
  summary: Create or update page configurations
  description: |
    This API allows you to create or update page configurations.
  operationId: page_configurations_bulk_post
  requestBody:
    required: True
    content:
      application/json:
        schema:
          type: object
          additionalProperties: False
          required:
            - data
          properties:
            data:
              type: array
              items: 
                $ref: '../../components/schemas/page_configurations.yaml#/page_configuration_in'
  responses:
    '200':
      description: OK
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '../../components/schemas/bulk_error.yaml'
              - type: object
                properties:
                  error:
                    type: string
                    nullable: True
                  message:  
                    type: string
                    nullable: True
                  data: 
                    type: string
                    nullable: True
    '401':
      description: Unauthorised request
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/401.yaml"
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/403.yaml"
                

