openapi: 3.0.3
info:
  version: '1.0'
  title: Head of Project APIs
  termsOfService: 'https://www.fylehq.com/privacy/terms-and-conditions'
  description: |
    These APIs are used by applications for Head of a Project - typically to understand budget usages and analytics.
  contact:
    name: Platform Beta
    email: platform-beta@fylehq.com
servers:
  - url: 'https://us1.fylehq.com/platform/v1beta'
    description: US Region Server
  - url: 'https://in1.fylehq.com/platform/v1beta'
    description: India Region Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            '*': 'Grant all actions'
tags:
  - name: Budget Usages
    description: |
      This API gives you insight of budgets in an organisation

paths:
  /hop/budget_usages:
    $ref: paths/hop@budget_usages.yaml
