post:
  tags:
    - Org Logo
  summary: Generate URLs for org logo
  description: |
    Generate URLs for org logo file
  operationId: org_logo_generate_urls
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: ../../components/schemas/org_settings.yaml#/logo_file_generate_urls_action_out
    '401':
      description: Unauthorized request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/401.yaml'
    '400':
      description: Unauthorized request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/400.yaml'
