get:
  tags:
    - Organisation Settings
  security:
    - oauth2: ['*']
  summary: Get organisation settings
  description: Returns the feature and workflow settings for the authenticated user's organisation.
  operationId: admin_org_settings_get
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            required:
              - data
            properties:
              data:
                $ref: '../../components/schemas/org_settings.yaml#/org_settings_out'
    '401':
      description: Unauthorized request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/401.yaml'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/403.yaml'
    '404':
      description: Organisation settings not found
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/404.yaml'
