get:
  tags:
    - Expenses
  summary: List expenses export configurations
  description: |
    This API gets you the saved export configurations for expenses in the current organization.
    
    Export configurations allow users to save and reuse export settings including column selections, 
    formulas, sort orders, and formatting preferences.

    This API supports very rich filtering on all response fields and pagination via query parameters. To understand how to use these parameters, please see the [Guide to Data APIs](https://docs.fylehq.com/docs/fyle-platform-docs/ZG9jOjI3Mzk2NTM3-guide-to-data-ap-is#filtering)
  operationId: expenses_export_configurations_list
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              count:
                $ref: '../../components/schemas/count.yaml'
              offset:
                $ref: '../../components/schemas/offset.yaml'
              data:
                type: array
                items:
                  $ref: '../../components/schemas/expenses_export_configurations.yaml#/expenses_export_configuration_out'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/400.yaml'
    '401':
      description: Unauthorized request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/401.yaml'
