openapi: 3.0.3
info:
  version: '1.0'
  title: Manager APIs
  description: |
    These APIs are generally used to integrate Fyle with accounting or HRMS systems. 
  contact:
    name: Platform Beta
    email: support@fylehq.com
servers:
  - url: 'https://us1.fylehq.com/platform/v1'
    description: US Region Server
  - url: 'https://in1.fylehq.com/platform/v1'
    description: India Region Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://app.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            '*': 'Grant all actions'
tags: []

paths:
  /manager/employee_overview/expense_comments:
    $ref: paths/manager@employee_overview@expense_comments.yaml
  /manager/employee_overview/files/generate_urls/bulk:
    $ref: paths/manager@employee_overview@files@generate_urls@bulk.yaml