openapi: 3.0.3
info:
  version: '1.0'
  title: Admin APIs
  description: >
    These APIs are generally used to integrate Fyle with accounting or HRMS
    systems. 
  contact:
    name: Platform Beta
    email: support@fylehq.com
servers:
  - url: https://us1.fylehq.com/platform/v1
    description: US Region Server
  - url: https://in1.fylehq.com/platform/v1
    description: India Region Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.fylehq.com/app/developers/#/oauth/authorize
          tokenUrl: https://accounts.fylehq.com/oauth/token
          scopes:
            '*': Grant all actions
  schemas:
    '400':
      type: object
      properties:
        message:
          type: string
          nullable: true
          description: |
            Message describing why the request is invalid
    '401':
      type: object
      properties:
        message:
          enum:
            - invalid token
          type: string
          description: >
            This error means that the input access token is either not issued by
            Fyle or has expired.

            You need to generate a new access token.
    count:
      type: integer
      description: |
        The total number of objects that can be requested.
      example: 10000
    offset:
      description: >
        offset is used to skip that many number of objects before counting. <br>

        For example, if there are 2000 objects, <br>

        The first request will have offset as 0 and limit as 1000 to return
        first 1000 objects. <br>

        The second request will have offset as 1000 and limit as 1000 to return
        next 1000 objects. <br>
      type: integer
      example: 10
    org_id:
      type: string
      description: |
        The unique id of the Organization to which the object is associated.
      readOnly: true
      example: orwruogwnngg
    currency:
      type: string
      description: >
        The three-letter currency code following ISO standard <a
        href='https://www.iso.org/iso-4217-currency-codes.html'>ISO 4217</a>.
      example: USD
      pattern: ([A-Z]{3})
    created_at:
      type: string
      format: date-time
      description: >
        Signifies when this object was created in [ISO8601
        format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
      example: '2020-06-01T13:14:54.804+00:00'
    updated_at:
      type: string
      format: date-time
      description: >
        Signifies when this object was updated in [ISO8601
        format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
      example: '2020-06-11T13:14:55.201598+00:00'
    id_string:
      type: string
      maxLength: 15
      description: |
        This id provided by Fyle to identify an object.
      example: sdfd2391
    file_generate_urls_action_out:
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/id_string'
        name:
          type: string
          description: |
            Name of the uploaded file.
          example: uber_expenses_vmrpw.pdf
        content_type:
          type: string
          example: text/csv
        download_url:
          type: string
          description: |
            Link to download this file
        upload_url:
          type: string
          description: |
            Link to download this file
    org_rov_out:
      type: object
      additionalProperties: false
      required:
        - id
        - name
        - domain
        - currency
        - created_at
        - updated_at
        - is_verified
        - approval_pending_reports_count
        - billed_users_count
        - enabled_users_count
        - incomplete_card_expenses_count
        - pending_reimbursement_amount
        - pending_users_count
        - logo_file_id
        - logo_file
      properties:
        id:
          $ref: '#/components/schemas/org_id'
        name:
          type: string
          maxLength: 255
          description: Represents the name of the org.
          example: Demo Account
        domain:
          type: string
          maxLength: 255
          description: >-
            This field specifies the domain with which the organisation is
            registered.
          example: example.com
        currency:
          $ref: '#/components/schemas/currency'
        created_at:
          $ref: '#/components/schemas/created_at'
        updated_at:
          $ref: '#/components/schemas/updated_at'
        is_verified:
          type: boolean
          nullable: false
          description: >
            Determines whether this organization has been verified by a
            verifier.
        approval_pending_reports_count:
          type: integer
          nullable: false
          description: |
            Determines the number of reports that are pending for approval.
        billed_users_count:
          type: integer
          nullable: false
          description: >
            Determines the number of users who qualify as active users to be
            billed.
        enabled_users_count:
          type: integer
          nullable: false
          description: |
            Determines the number of enabled users in the org.
        incomplete_card_expenses_count:
          type: integer
          nullable: false
          description: >
            Determines the number of incomplete expenses mapped to a card
            transaction.
        pending_reimbursement_amount:
          type: number
          nullable: false
          description: |
            Determines the total amount that is to be paid to the employees.
        pending_users_count:
          type: integer
          nullable: false
          description: >
            Determines the number of users who are yet to accept invite and
            verify email.
        logo_file_id:
          type: string
          nullable: false
          description: |
            Determines the file id of the branding logo
        logo_file:
          $ref: '#/components/schemas/file_generate_urls_action_out'
tags: []
paths:
  /accountant/orgs:
    get:
      tags:
        - Organisations
      summary: List Organisations
      operationId: orgs_list
      description: >
        This API supports very rich filtering on all response fields and
        pagination via query parameters. To understand how to use these
        parameters, please see the [Guide to Data
        APIs](https://docs.fylehq.com/docs/fyle-platform-docs/ZG9jOjI3Mzk2NTM3-guide-to-data-ap-is#filtering)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  count:
                    $ref: '#/components/schemas/count'
                  offset:
                    $ref: '#/components/schemas/offset'
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/org_rov_out'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
