openapi: 3.0.3
info:
  version: '1.0'
  title: Authorization APIs
  termsOfService: 'https://www.fylehq.com/privacy/terms-and-conditions'
  contact:
    name: Platform Beta
    email: platform-beta@fylehq.com
  description: |
    These APIs are used for authorization.
servers:
  - url: 'https://accounts.fylehq.com/oauth'
    description: Authorization Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            '*': Grant all actions
  schemas:
    '401':
      type: object
      properties:
        message:
          enum:
            - invalid token
          type: string
          description: >
            This error means that the input access token is either not issued by
            Fyle or has expired.

            You need to generate a new access token.
paths:
  /oauth/cluster:
    get:
      summary: Get Data Cluster
      operationId: get-data-cluster
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  cluster_domain:
                    type: string
                    maxLength: 255
                    description: |
                      The data for this user will be available in this cluster
                    example: 'https://us1.fyleh1.com'
        '401':
          description: Unauthorised request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
