openapi: 3.0.3
info:
  version: '1.0'
  title: Fyler APIs
  termsOfService: 'https://www.fylehq.com/privacy/terms-and-conditions'
  contact:
    name: Integrations
    email: support@fylehq.com
servers:
  - url: 'https://hulk.fyle.tech/platform/v1'
    description: Staging Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            '*': Grant all actions
tags:
  - name: My Profile
    description: |
      This API gives you access to manage your profile data.
  - name: Projects
    description: |
      These APIs gives you access to Projects data.
  - name: Cost Centers
    description: |
      These APIs gives you access to Cost Centers data.
  - name: Vendors
    description: |
      This API gives you a list of vendors
  - name: Categories
    description: |
      This API gives you list of your organisation's Categories data.
  - name: Currencies
    description: |
      This API gives you list of currencies supported by Fyle.
  - name: Expenses
    description: |
      This API gives you access to your Expenses data.
  - name: Reports
    description: |
      This API gives you access to your Expense Reports data.
  - name: Trips
    description: |
      This API gives you stats of your trip requests.
  - name: Advances
    description: |
      This API gives you stats of your advance requests.
  - name: Files
    description: |
      Creates a file.
  - name: Mileage Rates
    description: |
      These APIs gives access to your organisation's Mileage Rates
paths:
  /fyler/my_profile:
    get:
      tags:
        - My Profile
      summary: Retrieve my profile
      operationId: get-my-profile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      employee_id:
                        type: string
                        maxLength: 255
                        description: |
                          Employee Id of the fyler
                        example: ouHXboARkbAB
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    enum:
                      - invalid token
                    type: string
                    description: >
                      This error means that the input access token is either not
                      issued by Fyle or has expired.

                      You need to generate a new access token.
