openapi: 3.0.3
info:
  version: '1.0'
  title: Head of department APIs
  description: Fyle Platform Head of department APIs
  contact:
    name: Integrations
    email: support@fylehq.com
servers:
  - url: https://hulk.fyle.tech/platform/v1
    description: Staging Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.fylehq.com/app/developers/#/oauth/authorize
          tokenUrl: https://accounts.fylehq.com/oauth/token
          scopes:
            '*': Grant all actions
  parameters:
    created_at:
      in: query
      name: created_at
      description: >
        Date string in yyyy-MM-ddTHH:mm:ss.SSSZ  format along with operator in
        RHS dot pattern.<br> Supported operators are `gte`,`lte`,`gt`,`lt`.
      schema:
        type: string
        example: gte.2020-06-01T00:00:00.000-08:00
    updated_at:
      in: query
      name: updated_at
      description: >
        Date string in yyyy-MM-ddTHH:mm:ss.SSSZ  format along with operator in
        RHS dot pattern.<br> Supported operators are `gte`,`lte`,`gt`,`lt`.
      schema:
        type: string
        example: gte.2020-06-01T00:00:00.000-08:00
    offset:
      in: query
      name: offset
      description: |
        offset is used to skip that many number of objects before counting. <br>
      schema:
        type: integer
        example: 10
    limit:
      in: query
      name: limit
      description: >
        A limit on the number of objects to be returned. Allowed values are from
        1 to 200.
      schema:
        type: integer
        example: 20
        default: 50
        maximum: 200
    order:
      in: query
      name: order
      description: |
        use comma separated column names for sorting the results. <br>
        For sorting in descending order, use `column_name.desc`
      schema:
        type: string
        example: updated_at.desc,id
  schemas:
    '401':
      type: object
      properties:
        message:
          enum:
            - invalid token
          type: string
          description: >
            This error means that the input access token is either not issued by
            Fyle or has expired.

            You need to generate a new access token.
    count:
      type: integer
      description: |
        The total number of objects that can be requested.
      example: 10000
    offset:
      description: >
        offset is used to skip that many number of objects before counting. <br>

        For example, if there are 2000 objects, <br>

        The first request will have offset as 0 and limit as 1000 to return
        first 1000 objects. <br>

        The second request will have offset as 1000 and limit as 1000 to return
        next 1000 objects. <br>
      type: integer
      example: 10
    id_string:
      type: string
      maxLength: 15
      description: |
        This id provided by Fyle to identify an object.
      example: sdfd2391
    amount:
      type: number
      description: |
        amount of money
      example: 47.99
    id_integer:
      type: integer
      description: |
        This id provided by Fyle to identify an object.
      example: 1234
    name:
      type: string
      maxLength: 255
      description: >
        This represents the name of the resource. This should be unique in an
        organization
      example: foo123
    budget_type:
      nullable: false
      type: string
      enum:
        - WEEKLY
        - MONTHLY
        - QUARTERLY
        - SEMI_ANULALLY
        - YEARLY
        - ONE_TIME
      description: |
        Type of budgets 
      example: WEEKLY
    is_enabled:
      type: boolean
      description: >
        This indicates if the resource is enabled for use within the
        organisation.
      default: true
      example: true
    budget_out_embed:
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/id_string'
        name:
          allOf:
            - $ref: '#/components/schemas/name'
          example: Sales Montly Budget
        type:
          $ref: '#/components/schemas/budget_type'
        amount_limit:
          allOf:
            - $ref: '#/components/schemas/amount'
          example: 10000
        observer_ids:
          type: array
          items:
            $ref: '#/components/schemas/id_string'
          example:
            - usge49ielgel
        is_enabled:
          $ref: '#/components/schemas/is_enabled'
        department_ids:
          type: array
          items:
            $ref: '#/components/schemas/id_string'
          example:
            - 2222
            - 1221
          description: |
            List of department ids
        project_ids:
          type: array
          items:
            $ref: '#/components/schemas/id_integer'
          example:
            - 2222
            - 1221
          description: |
            List of project ids
    budget_usage_out:
      type: object
      required:
        - budget_id
        - observer_ids
        - spent
        - amount_limit
        - budget
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/id_string'
        budget_id:
          $ref: '#/components/schemas/id_string'
        start_date:
          type: string
          nullable: true
          format: date-time
          example: 2020-06-11T00.00.00Z
          description: Start date of the cycle of the budget
        end_date:
          type: string
          nullable: true
          format: date
          example: 2020-06-11T00.00.00Z
          description: End date of the cycle of the budget
        observer_ids:
          type: array
          items:
            $ref: '#/components/schemas/id_string'
          example:
            - usge49ielgel
        spent:
          allOf:
            - $ref: '#/components/schemas/amount'
          example: 1000
        amount_limit:
          allOf:
            - $ref: '#/components/schemas/amount'
          example: 10000
        budget_department_ids:
          type: array
          items:
            $ref: '#/components/schemas/id_string'
          example:
            - 2222
            - 1221
          description: |
            List of department ids
        budget_project_ids:
          type: array
          items:
            $ref: '#/components/schemas/id_integer'
          example:
            - 2222
            - 1221
          description: |
            List of project ids
        budget:
          $ref: '#/components/schemas/budget_out_embed'
tags:
  - name: Budget Usages
    description: |
      This API gives you insight of budgets in an organisation
paths:
  /hod/budget_usages:
    get:
      tags:
        - Get Budget Usages
      summary: List Budget Usages
      operationId: get-budget_usages
      parameters:
        - $ref: '#/components/parameters/created_at'
        - $ref: '#/components/parameters/updated_at'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/order'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    $ref: '#/components/schemas/count'
                  offset:
                    $ref: '#/components/schemas/offset'
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/budget_usage_out'
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
