openapi: 3.0.3
info:
  version: '1.0'
  title: Owner APIs
  termsOfService: https://www.fylehq.com/privacy/terms-and-conditions
  description: |
    These APIs are used by applications for Owner operations - resetting or deleting an organisation.
  contact:
    name: Platform Beta
    email: support@fylehq.com
servers:
  - url: https://us1.fylehq.com/platform/v1
    description: US Region Server
  - url: https://in1.fylehq.com/platform/v1
    description: India Region Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.fylehq.com/app/developers/#/oauth/authorize
          tokenUrl: https://accounts.fylehq.com/oauth/token
          scopes:
            '*': Grant all actions
  schemas:
    '400':
      type: object
      properties:
        message:
          type: string
          nullable: true
          description: |
            Message describing why the request is invalid
    '401':
      type: object
      properties:
        message:
          enum:
            - invalid token
          type: string
          description: |
            This error means that the input access token is either not issued by Fyle or has expired.
            You need to generate a new access token.
    '403':
      type: object
      properties:
        message:
          enum:
            - Forbidden
          type: string
          description: |
            This error means current user does not have enough permissions to perform this operation.
    '404':
      type: object
      properties:
        message:
          enum:
            - Resource not found
          type: string
          description: |
            This error means the requested resource was not found or the requester doesn't have sufficient access.
    org_reset_delete_in:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: |
            The unique id of the Organization to which the object is associated.
          example: orwruogwnngg
tags:
  - name: Organisations
    description: |
      These APIs gives you access to manage organisations.
paths:
  /owner/orgs/reset:
    post:
      tags:
        - Organisations
      summary: Reset an organisation
      description: |
        This API performs a reset of an organisation. This will delete the data like expenses, reports, files, advances, reimbursements, etc. and reset the organisation to a clean state.
        - **_Note:_** This API doesn't delete any settings or configurations _(Even employees that were invited aren't deleted)_.
      operationId: orgs_reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - data
              properties:
                data:
                  $ref: '#/components/schemas/org_reset_delete_in'
                reason:
                  type: string
                  description: |
                    Reason for resetting the organisation.
                  example: Testing account
      responses:
        '200':
          description: The Organisation has been scheduled for reset successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
  /owner/orgs/delete:
    post:
      tags:
        - Organisations
      summary: Delete an organisation
      description: |
        This API will delete the organisation and all the data like expenses, reports, files, advances, reimbursements, etc. associated with the organisation permanently.
        - **_Note:_** **This action is irreversible.**
      operationId: orgs_delete
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - data
              properties:
                data:
                  $ref: '#/components/schemas/org_reset_delete_in'
                reason:
                  type: string
                  description: |
                    Reason for deleting the organisation.
                  example: Testing account
      responses:
        '200':
          description: The Organisation has been scheduled for deletion successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
