openapi: 3.0.3
info:
  version: '1.0'
  title: SuperAdmin APIs
  description: |
    These APIs are generally used to manage the enviornment. 
  contact:
    name: Platform Beta
    email: support@fylehq.com
servers:
  - url: 'https://us1.fylehq.com/platform/v1'
    description: US Region Server
  - url: 'https://in1.fylehq.com/platform/v1'
    description: India Region Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://app.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            '*': 'Grant all actions'
tags: []

paths:
  /superadmin/auth/signup:
    $ref: paths/superadmin@auth@signup.yaml
  /superadmin/auth/signin:
    $ref: paths/superadmin@auth@signin.yaml
