/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    user_id?: string | null;
    type?: AccountResponse.TypeEnum;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency?: string;
    current_balance_amount?: number;
    tentative_balance_amount?: number;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * This id is provided by Fyle to identify a category. 
     */
    category_id?: number | null;
}
export namespace AccountResponse {
    export const TypeEnum = {
        PersonalCashAccount: 'PERSONAL_CASH_ACCOUNT',
        PersonalCorporateCreditCardAccount: 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
        PersonalAdvanceAccount: 'PERSONAL_ADVANCE_ACCOUNT',
        CompanyExpenseAccount: 'COMPANY_EXPENSE_ACCOUNT',
        CompanyCorporateCreditCardAccount: 'COMPANY_CORPORATE_CREDIT_CARD_ACCOUNT',
        CompanyCategoryAccount: 'COMPANY_CATEGORY_ACCOUNT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


