/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountPayload { 
    /**
     * The unique id of an user to which the object is associated. 
     */
    user_id?: string | null;
    type?: AccountPayload.TypeEnum;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency?: string;
    /**
     * This id is provided by Fyle to identify a category. 
     */
    category_id?: number | null;
}
export namespace AccountPayload {
    export const TypeEnum = {
        PersonalAdvanceAccount: 'PERSONAL_ADVANCE_ACCOUNT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


