/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountingExportResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * List of file ids which holds reference to export files
     */
    readonly file_ids?: Array<string>;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    exported_at?: string | null;
    /**
     * This represents name of the resource.
     */
    name?: string;
    /**
     * This represents the description of the resource. 
     */
    description?: string | null;
    /**
     * An optional URL where the exported data could be accessed
     */
    url?: string | null;
    client_id?: string | null;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
}

