/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountingExportSummaryPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    state: AccountingExportSummaryPayload.StateEnum;
    error_type: AccountingExportSummaryPayload.ErrorTypeEnum | null;
    /**
     * URL Endpoint for exported / failed expense
     */
    url: string;
}
export namespace AccountingExportSummaryPayload {
    export const StateEnum = {
        Complete: 'COMPLETE',
        Error: 'ERROR',
        InProgress: 'IN_PROGRESS',
        Skipped: 'SKIPPED',
        Initiated: 'INITIATED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
    export const ErrorTypeEnum = {
        AccountingIntegrationError: 'ACCOUNTING_INTEGRATION_ERROR',
        Mapping: 'MAPPING'
    } as const;
    export type ErrorTypeEnum = typeof ErrorTypeEnum[keyof typeof ErrorTypeEnum];
}


