/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountingExportLineitemPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    object_id: string | null;
    object_type: AccountingExportLineitemPayload.ObjectTypeEnum;
    /**
     * Optional metadata about the Export operation. For example, newly created Accounting Entry numbers in Quickbooks. 
     */
    reference: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    accounting_export_id: string | null;
}
export namespace AccountingExportLineitemPayload {
    export const ObjectTypeEnum = {
        AdvanceRequest: 'ADVANCE_REQUEST',
        Reimbursement: 'REIMBURSEMENT',
        Report: 'REPORT',
        Expense: 'EXPENSE',
        Settlement: 'SETTLEMENT'
    } as const;
    export type ObjectTypeEnum = typeof ObjectTypeEnum[keyof typeof ObjectTypeEnum];
}


