/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Account of a user belonging to any org 
 */
export interface AccountMinimal { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency?: string;
    current_balance_amount?: number;
    tentative_balance_amount?: number;
}

