/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountResponseEmbed { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    type?: AccountResponseEmbed.TypeEnum;
}
export namespace AccountResponseEmbed {
    export const TypeEnum = {
        PersonalCashAccount: 'PERSONAL_CASH_ACCOUNT',
        PersonalCorporateCreditCardAccount: 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
        PersonalAdvanceAccount: 'PERSONAL_ADVANCE_ACCOUNT',
        CompanyExpenseAccount: 'COMPANY_EXPENSE_ACCOUNT',
        CompanyCorporateCreditCardAccount: 'COMPANY_CORPORATE_CREDIT_CARD_ACCOUNT',
        CompanyCategoryAccount: 'COMPANY_CATEGORY_ACCOUNT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


