/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountingExportLineitemResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    object_id?: string | null;
    object_type?: AccountingExportLineitemResponse.ObjectTypeEnum;
    /**
     * Optional metadata about the Export operation. For example, newly created Accounting Entry numbers in Quickbooks. 
     */
    reference?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    accounting_export_id?: string | null;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
}
export namespace AccountingExportLineitemResponse {
    export const ObjectTypeEnum = {
        AdvanceRequest: 'ADVANCE_REQUEST',
        Advance: 'ADVANCE',
        BalanceTransfer: 'BALANCE_TRANSFER',
        Refund: 'REFUND',
        Reimbursement: 'REIMBURSEMENT',
        Report: 'REPORT',
        Expense: 'EXPENSE',
        CccExpense: 'CCC_EXPENSE',
        Settlement: 'SETTLEMENT'
    } as const;
    export type ObjectTypeEnum = typeof ObjectTypeEnum[keyof typeof ObjectTypeEnum];
}


