/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AchTransferState1 } from './achTransferState1';
import { AchTransferInitiatedAt } from './achTransferInitiatedAt';


export interface AchTransfer { 
    state?: AchTransferState1 | null;
    /**
     * Description of current status of the payment. 
     */
    status_info?: string | null;
    initiated_at?: AchTransferInitiatedAt | null;
    /**
     * Signifies the source of ach transfer reference code. 
     */
    source_account_ach_reference_id?: string | null;
    /**
     * Signifies the destination of ach transfer reference code. 
     */
    destination_account_ach_reference_id?: string | null;
}

