/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of ACH if this reimbursment is processed via ACH. 
 */
export const AchTransferState = {
    AchFailed: 'ACH_FAILED',
    AchInitiated: 'ACH_INITIATED',
    AchComplete: 'ACH_COMPLETE',
    AchRetry: 'ACH_RETRY'
} as const;
export type AchTransferState = typeof AchTransferState[keyof typeof AchTransferState];

