/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminExpenseSplitObjectInner } from './adminExpenseSplitObjectInner';
import { CustomField } from './customField';
import { LocationsInner } from './locationsInner';


export interface AdminSplitExpensePayload { 
    /**
     * This id is provided by Fyle to identify an object - When `id` is sent, default action is to update the expense 
     */
    id: string;
    /**
     * The expense amount which is added or modified by admin or approver. 
     */
    admin_amount: number;
    /**
     * This array contains the number of split expenses admin wants to create for the expense. The `admin_amount` provided for the original expense should be equal to the sum of `admin_amount` provided for each split. Each attribute in the splits array will take precedence to the original expense object. If any attribute is not provided in the split object, then null or default value will be taken for that attribute in the resultant split. 
     */
    splits?: Array<AdminExpenseSplitObjectInner>;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    category_id?: number | null;
    /**
     * This value signifies the client from which this expense was created 
     */
    source?: string;
    /**
     * It signifies when this expense was made. This date cannot be in future. - **Note:**   - This field is required while creating an expense.   - _Not required when updating an expense, but is non-nullable_.  
     */
    spent_at?: string;
    /**
     * This field marks whether a given expense is reimbursable or not.
     */
    is_reimbursable?: boolean | null;
    /**
     * This field is applicable only for `Flight`, `Train`, `Bus` category. Index 0 holds onward journey travel class, index 1 holds return journey travel class. 
     */
    travel_classes?: Array<string> | null;
    /**
     * This field will be present for travel related categories. For travel between Place A to Place B, this array will contain two items. From location at array index i and To location at array index i+1. 
     */
    locations?: Array<LocationsInner> | null;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency?: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    project_id?: number | null;
    /**
     * List of file IDs to be attached to the expense. 
     */
    file_ids?: Array<string>;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    cost_center_id?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    source_account_id?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_wallet_id?: string | null;
    /**
     * Tax amount as setup by your organization. - _Note:_   - Tax amount cannot be greater than the expense amount. 
     */
    tax_amount?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    tax_group_id?: string | null;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    started_at?: string | null;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    ended_at?: string | null;
    /**
     * String denoting the name of the vendor to which the expense was made. 
     */
    merchant?: string | null;
    purpose?: string;
    /**
     * This field marks whether a given expense is billable or not.
     */
    is_billable?: boolean | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField>;
}

