/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportApprovalPartial } from './reportApprovalPartial';
import { ReimbursementResponseMinimal } from './reimbursementResponseMinimal';
import { UserPartial } from './userPartial';
import { AdminReportResponseAccountingExportSummary } from './adminReportResponseAccountingExportSummary';
import { EmployeeResponseEmbedForReport } from './employeeResponseEmbedForReport';
import { AdvanceWalletReportResponse } from './advanceWalletReportResponse';
import { ReportCommentsResponseEmbed } from './reportCommentsResponseEmbed';


export interface AdminReportResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    user_id: string;
    user: UserPartial;
    /**
     * purpose for creating the report
     */
    purpose: string | null;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency: string;
    /**
     * amount of money 
     */
    amount: number;
    /**
     * Tax amount for the report 
     */
    tax: number | null;
    state: AdminReportResponse.StateEnum;
    /**
     * Number of expenses part of this report 
     */
    num_expenses: number;
    /**
     * Determines whether this report has been verified by a verifier 
     */
    is_verified?: boolean | null;
    /**
     * Signifies if physical has been collected for this report 
     */
    is_physical_bill_submitted?: boolean | null;
    /**
     * Signifies if and when the physical bill for this report was submitted. 
     */
    physical_bill_submitted_at?: string | null;
    /**
     * Determines whether this report was flagged manually 
     */
    is_manually_flagged: boolean;
    /**
     * Determines whether this report was flagged from a policy 
     */
    is_policy_flagged: boolean;
    /**
     * Determines whether this expense has been exported to external accounting system or not. 
     */
    is_exported?: boolean | null;
    /**
     * Signifies if and when this report was reimbursed. 
     */
    last_paid_at: string | null;
    /**
     * Signifies if and when this report was approved. 
     */
    last_approved_at: string | null;
    /**
     * Signifies if and when this report was submitted. 
     */
    last_submitted_at: string | null;
    /**
     * Signifies if and when this report was resubmitted. 
     */
    last_resubmitted_at: string | null;
    /**
     * A unique human readable identifier for the report 
     */
    seq_num: string;
    /**
     * signifies the client from which this report was created 
     */
    source: string | null;
    /**
     * List of report_approval objects 
     */
    approvals: Array<ReportApprovalPartial>;
    /**
     * This id provided by Fyle to uniquely identify an employee within an organization. This id is always prefixed with `ou`. 
     */
    employee_id?: string;
    employee: EmployeeResponseEmbedForReport;
    next_approver_user_ids: Array<string>;
    /**
     * An unique ID, generated by Fyle, for identifying the Reimbursement. 
     */
    reimbursement_id: string | null;
    reimbursement: ReimbursementResponseMinimal | null;
    /**
     * readable state name
     */
    state_display_name?: string;
    /**
     * List of comments on the report 
     */
    comments: Array<ReportCommentsResponseEmbed>;
    accounting_export_summary?: AdminReportResponseAccountingExportSummary;
    /**
     * Determines whether advances can be applied to this report 
     */
    can_apply_advances: boolean | null;
    /**
     * List of applied advance wallets 
     */
    applied_advance_wallets: Array<AdvanceWalletReportResponse> | null;
}
export namespace AdminReportResponse {
    export const StateEnum = {
        Draft: 'DRAFT',
        ApproverPending: 'APPROVER_PENDING',
        ApproverInquiry: 'APPROVER_INQUIRY',
        PaymentProcessing: 'PAYMENT_PROCESSING',
        Approved: 'APPROVED',
        PaymentPending: 'PAYMENT_PENDING',
        Paid: 'PAID'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


