/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomField } from './customField';
import { LocationsInner } from './locationsInner';
import { DistanceUnit } from './distanceUnit';


export interface AdminExpensePayload { 
    /**
     * This id is provided by Fyle to identify an object - When `id` is sent, default action is to update the expense 
     */
    id?: string;
    /**
     * The expense amount which is added or modified by admin or approver. - **Note:**   - This field is required while creating an expense.   - _Not required when updating an expense, but is non-nullable_.  
     */
    admin_amount?: number;
    /**
     * It signifies when this expense was made. This date cannot be in future. - **Note:**   - This field is required while creating an expense.   - _Not required when updating an expense, but is non-nullable_.  
     */
    spent_at?: string;
    /**
     * An immutable field that represents the email address of the employee. Must be compliant with <a href=\'https://www.ietf.org/rfc/rfc822.txt\'>RFC 822.</a> - **Note:**   - The expense will be assigned/re-assigned to this particular `employee`.    - This field is required while creating an expense.   - _Not required when updating an expense, but is non-nullable_.    - Admins can\'t assign the expense to self. 
     */
    assignee_user_email?: string;
    /**
     * This value signifies the client from which this expense was created 
     */
    source?: string;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * String denoting the name of the vendor to which the expense was made. 
     */
    merchant?: string | null;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency?: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount?: number | null;
    purpose?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    cost_center_id?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    category_id?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    project_id?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    source_account_id?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_wallet_id?: string | null;
    /**
     * Tax amount as setup by your organization. - _Note:_   - Tax amount cannot be greater than the expense amount. 
     */
    tax_amount?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    tax_group_id?: string | null;
    /**
     * This field marks whether a given expense is billable or not.
     */
    is_billable?: boolean | null;
    /**
     * This field marks whether a given expense is reimbursable or not.
     */
    is_reimbursable?: boolean | null;
    /**
     * Actual distance travelled by employee in travel related expenses.
     */
    distance?: number | null;
    distance_unit?: DistanceUnit | null;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    started_at?: string | null;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    ended_at?: string | null;
    /**
     * This field is applicable only for `Flight`, `Train`, `Bus` category. Index 0 holds onward journey travel class, index 1 holds return journey travel class. 
     */
    travel_classes?: Array<string> | null;
    /**
     * This field will be present for travel related categories. For travel between Place A to Place B, this array will contain two items. From location at array index i and To location at array index i+1. 
     */
    locations?: Array<LocationsInner> | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField>;
    /**
     * List of file ids to attach to the expense. <br> To add new files to the expense, send the list of file ids to be attached. <br> To remove files from the expense, send the list of all file ids except which you want to remove. <br> 
     */
    file_ids?: Array<string>;
    /**
     * This field is applicable for only `Hotel` category. 
     */
    hotel_is_breakfast_provided?: boolean | null;
    /**
     * Specific to mileage expense. This represents the Mileage\'s rate id given by Fyle during creation of mileage rate for which this expense is created. 
     */
    mileage_rate_id?: number | null;
    /**
     * Flag stating whether this was a round trip or not.
     */
    mileage_is_round_trip?: boolean | null;
    /**
     * Distance computed by Fyle in mileage expenses.
     */
    mileage_calculated_distance?: number | null;
    /**
     * Amount computed by Fyle in mileage expenses.
     */
    mileage_calculated_amount?: number | null;
    /**
     * Commute details id of the expense. This id is provided by Fyle to identify a commute details. 
     */
    commute_details_id?: number | null;
    /**
     * Commute deduction type of the expense. 
     */
    commute_deduction?: AdminExpensePayload.CommuteDeductionEnum | null;
    /**
     * Specific to per diem expense. This represents the per diem\'s rate id given by Fyle during creation of per diem rate for which this expense is created. <br> This field is required for creating Per Diem Expenses. 
     */
    per_diem_rate_id?: number | null;
    /**
     * Specific to per diem related expenses, number of days for which per diem claim is made. <br> This field is required for creating Per Diem Expenses. 
     */
    per_diem_num_days?: number | null;
}

