/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminApproverCategoryResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * Represents the name of the category.
     */
    name?: string;
    /**
     * Represents the name of the sub_category.
     */
    sub_category?: string | null;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * This is a combination of name and sub_category separated by a / and spaces. In case if no sub_category is present it is same as name of the category. 
     */
    display_name?: string;
    /**
     * Represents the name of the system_category.
     */
    system_category?: string | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * List of project ids for which this category can be used. If project_ids is null, then this category can be used for any project. 
     */
    restricted_project_ids?: Array<number> | null;
    /**
     * List of IDs of users who can access this object. 
     */
    restricted_spender_user_ids?: Array<string | null> | null;
}

