/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminFilePayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Name of the uploaded file. 
     */
    name: string;
    /**
     * Indicates whether this file original size or encrypted or its thumbnail image. 
     */
    type: AdminFilePayload.TypeEnum;
    /**
     * Password which required to unlock the file. 
     */
    password?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    user_id: string;
}
export namespace AdminFilePayload {
    export const TypeEnum = {
        Integration: 'INTEGRATION',
        Receipt: 'RECEIPT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


