/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartial } from './userPartial';


export interface AdminApproverProjectResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * Represents the name of the project.
     */
    name?: string;
    /**
     * Represents the name of the sub_project.
     */
    sub_project?: string | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This is a combination of name and sub_project separated by a / and spaces. In case if no sub_project is present it is same as name of the project. 
     */
    display_name?: string;
    /**
     * This represents the description of the resource. 
     */
    description?: string | null;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * List of IDs of users who can access this object. 
     */
    restricted_spender_user_ids?: Array<string | null> | null;
    /**
     * List of IDs of users who are approvers of the project. 
     */
    approver_user_ids?: Array<string | null>;
    /**
     * List of users who are approvers for this project. 
     */
    approver_users?: Array<UserPartial> | null;
    /**
     * List of categories that are applicable for the project.
     */
    category_ids?: Array<number> | null;
}

