/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminReportPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * Indicates purpose of the reports. It can only be updated for an existing report when the report is in `APPROVER_PENDING` or `APPROVED` state. 
     */
    purpose: string;
}

