/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Summary of accounting export for this report. 
 */
export interface AdminReportResponseAccountingExportSummary { 
    state?: AdminReportResponseAccountingExportSummary.StateEnum;
    /**
     * Number of skipped expenses. 
     */
    skipped?: number;
    /**
     * Number of failed expenses. 
     */
    error?: number;
    /**
     * Number of complete expenses. 
     */
    complete?: number;
    /**
     * Number of in progress expenses. 
     */
    in_progress?: number;
    /**
     * Number of initiated expenses. 
     */
    initiate?: number;
    /**
     * Third party app id. 
     */
    tpa_id?: string;
}
export namespace AdminReportResponseAccountingExportSummary {
    export const StateEnum = {
        Complete: 'COMPLETE',
        Error: 'ERROR',
        InProgress: 'IN_PROGRESS',
        Skipped: 'SKIPPED',
        Initiated: 'INITIATED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


