/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdvanceRequestApprovalPartial } from './advanceRequestApprovalPartial';
import { UserPartial } from './userPartial';
import { EmployeeResponseEmbed } from './employeeResponseEmbed';
import { CustomField } from './customField';
import { ProjectPartial } from './projectPartial';
import { AdvanceResponseEmbed } from './advanceResponseEmbed';


export interface AdvanceRequestResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly user_id?: string;
    user?: UserPartial;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency?: string;
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_id?: string | null;
    advance?: AdvanceResponseEmbed | null;
    /**
     * This is user visible identifier for an advance request. This field can be used as reference in UI. 
     */
    seq_num?: string;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * Optional descriptive notes which can be added to an advance request. 
     */
    notes?: string | null;
    /**
     * Descriptive purpose which is added to an advance request. 
     */
    purpose?: string | null;
    /**
     * The name of the client app from which this advance was created. if its a thrid party app, it prefixed with TPA_. Ex - If you pass SLACK_APP, it will be saved as TPA_SLACK_APP. If not passed, source is saved as TPA. 
     */
    source?: string | null;
    /**
     * State of the advance request. 
     */
    state?: AdvanceRequestResponse.StateEnum;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    project_id?: number | null;
    project?: ProjectPartial | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField>;
    /**
     * Signifies if and when this advance request was approved. 
     */
    last_approved_at?: string | null;
    /**
     * List of advance request approval objects 
     */
    approvals?: Array<AdvanceRequestApprovalPartial>;
    /**
     * Determines whether this advance request has been exported to external accounting system or not. 
     */
    is_exported?: boolean | null;
    /**
     * This id provided by Fyle to uniquely identify an employee within an organization. This id is always prefixed with `ou`. 
     */
    employee_id?: string;
    employee?: EmployeeResponseEmbed;
}
export namespace AdvanceRequestResponse {
    export const StateEnum = {
        Draft: 'DRAFT',
        ApprovalPending: 'APPROVAL_PENDING',
        Approved: 'APPROVED',
        SentBack: 'SENT_BACK',
        PulledBack: 'PULLED_BACK',
        Rejected: 'REJECTED',
        Paid: 'PAID'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


