/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartial } from './userPartial';


export interface AdvanceRequestApprovalPartial { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    approver_user_id?: string;
    approver_user?: UserPartial;
    /**
     * State of this advance request approval 
     */
    state?: AdvanceRequestApprovalPartial.StateEnum;
}
export namespace AdvanceRequestApprovalPartial {
    export const StateEnum = {
        ApprovalPending: 'APPROVAL_PENDING',
        ApprovalDisabled: 'APPROVAL_DISABLED',
        ApprovalDone: 'APPROVAL_DONE'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


