/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdvanceResponseEmbed { 
    /**
     * This id provided by Fyle to uniquely identify an advances. This id is always prefixed with `adv`. 
     */
    readonly id?: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency?: string;
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_request_id?: string | null;
    /**
     * This is user visible identifier for an advances. This field can be used as reference in UI. 
     */
    seq_num?: string;
}

