/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdvanceRequestResponseEmbed { 
    /**
     * This id provided by Fyle to uniquely identify an advance requests. This id is always prefixed with `adr`. 
     */
    readonly id?: string;
    /**
     * Signifies if and when this advance request was approved. 
     */
    last_approved_at?: string | null;
    /**
     * This is user visible identifier for an advance request. This field can be used as reference in UI. 
     */
    seq_num?: string;
}

