/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdvanceRequestResponseEmbed } from './advanceRequestResponseEmbed';
import { UserPartial } from './userPartial';
import { EmployeeResponseEmbed } from './employeeResponseEmbed';
import { CustomField } from './customField';
import { ProjectPartial } from './projectPartial';
import { UserPartialNullable } from './userPartialNullable';


export interface AdvanceResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly user_id?: string;
    user?: UserPartial;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency?: string;
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency?: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount?: number | null;
    payment_mode?: AdvanceResponse.PaymentModeEnum;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_request_id?: string | null;
    advance_request?: AdvanceRequestResponseEmbed | null;
    /**
     * This id is provided by Fyle to identify an object. 
     * @deprecated
     */
    advance_account_id?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_wallet_id?: string | null;
    /**
     * This is user visible identifier for an advances. This field can be used as reference in UI. 
     */
    seq_num?: string;
    /**
     * Descriptive purpose which is added to an advance. 
     */
    purpose?: string | null;
    /**
     * The name of the client app from which this advance was created. if its a thrid party app, it prefixed with TPA_. Ex - If you pass SLACK_APP, it will be saved as TPA_SLACK_APP. If not passed, source is saved as TPA. 
     */
    source?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    project_id?: number | null;
    project?: ProjectPartial | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * Signifies if and when this advance was issued. 
     */
    issued_at?: string | null;
    card_number?: string | null;
    /**
     * Determines whether this advance has been exported to external accounting system or not. 
     */
    is_exported?: boolean | null;
    /**
     * signifies when this advance was exported to an external accounting system.
     */
    last_exported_at?: string | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField>;
    /**
     * This id provided by Fyle to uniquely identify an employee within an organization. This id is always prefixed with `ou`. 
     */
    employee_id?: string;
    employee?: EmployeeResponseEmbed;
    creator_user?: UserPartialNullable | null;
}
export namespace AdvanceResponse {
    export const PaymentModeEnum = {
        Card: 'CARD',
        BankTransfer: 'BANK_TRANSFER',
        ChequeDd: 'CHEQUE_DD',
        Forex: 'FOREX',
        Cash: 'CASH'
    } as const;
    export type PaymentModeEnum = typeof PaymentModeEnum[keyof typeof PaymentModeEnum];
}


