/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomField } from './customField';


export interface AdvanceRequestPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency?: string;
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * Optional descriptive notes which can be added to an advance request. 
     */
    notes?: string | null;
    /**
     * Descriptive purpose which is added to an advance request. 
     */
    purpose?: string | null;
    /**
     * The name of the client app from which this advance was created. if its a thrid party app, it prefixed with TPA_. Ex - If you pass SLACK_APP, it will be saved as TPA_SLACK_APP. If not passed, source is saved as TPA. 
     */
    source?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    project_id?: number | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField>;
}

