/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdvanceRefundPayload { 
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency: string;
    /**
     * amount of money 
     */
    amount: number;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency?: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount?: number | null;
    payment_mode: AdvanceRefundPayload.PaymentModeEnum;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * Optional descriptive notes which can be added to an advance refund. 
     */
    notes?: string | null;
    /**
     * The name of the client app from which this advance refund was created. if its a thrid party app, it prefixed with TPA_. Ex - If you pass SLACK_APP, it will be saved as TPA_SLACK_APP. If not passed, source is saved as TPA. 
     */
    source?: string | null;
    card_number?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_wallet_id: string;
}
export namespace AdvanceRefundPayload {
    export const PaymentModeEnum = {
        Card: 'CARD',
        BankTransfer: 'BANK_TRANSFER',
        ChequeDd: 'CHEQUE_DD',
        Forex: 'FOREX',
        Cash: 'CASH'
    } as const;
    export type PaymentModeEnum = typeof PaymentModeEnum[keyof typeof PaymentModeEnum];
}


