/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdvanceRefundsStatsPayload { 
    /**
     * This field contains the query param string similar to the query params passed in advance_refunds GET call for displaying advance_refunds in the list view. 
     */
    query_params?: string;
}

