/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StateWiseGroupedStatsInner1 } from './stateWiseGroupedStatsInner1';
import { OverallStats1 } from './overallStats1';


/**
 * @type AdvanceRequestsStatsOut
 * @export
 */
export type AdvanceRequestsStatsOut = Array<StateWiseGroupedStatsInner1> | OverallStats1;

