/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomField } from './customField';


export interface AdvancePayload { 
    /**
     * The unique id of an user to which the object is associated. 
     */
    user_id: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency: string;
    /**
     * amount of money 
     */
    amount: number;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency?: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount?: number | null;
    payment_mode: AdvancePayload.PaymentModeEnum;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_request_id?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     * @deprecated
     */
    advance_account_id?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_wallet_id?: string | null;
    /**
     * Descriptive purpose which is added to an advances. 
     */
    purpose?: string | null;
    /**
     * The name of the client app from which this advance was created. if its a thrid party app, it prefixed with TPA_. Ex - If you pass SLACK_APP, it will be saved as TPA_SLACK_APP. If not passed, source is saved as TPA. 
     */
    source?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    project_id?: number | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    card_number?: string | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField>;
}
export namespace AdvancePayload {
    export const PaymentModeEnum = {
        BankTransfer: 'BANK_TRANSFER',
        ChequeDd: 'CHEQUE_DD',
        Forex: 'FOREX',
        Cash: 'CASH'
    } as const;
    export type PaymentModeEnum = typeof PaymentModeEnum[keyof typeof PaymentModeEnum];
}


