/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdvanceRefundsStatsResponse { 
    /**
     * This field represents the total number of advance_refunds that match the criteria specified in the query_params within the body of the refund. 
     */
    count?: number;
    /**
     * This field indicates the sum of amount of advance_refunds that match the criteria specified in the query_params within the body of the refund. 
     */
    total_amount?: number;
}

