/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdvancesStatsPayload { 
    /**
     * This field contains the query param string similar to the query params passed in advances GET call for displaying advances in the list view. 
     */
    query_params?: string;
}

