/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleConfig } from './scheduleConfig';


export interface AutomateReportSubmissionPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * A human readable identifier for the automate report submission 
     */
    description?: string;
    schedule_config?: ScheduleConfig;
}

