/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleConfig } from './scheduleConfig';
import { UserPartial } from './userPartial';


export interface AutomateReportSubmissionResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * A human readable identifier for the automate report submission 
     */
    description: string;
    schedule_config: ScheduleConfig;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly creator_user_id: string;
    creator_user: UserPartial;
}

