/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetType } from './budgetType';


export interface BudgetResponseEmbed { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * This represents the name of the resource. This should be unique in an organization 
     */
    name?: string;
    type?: BudgetType;
    /**
     * amount of money 
     */
    amount_limit?: number;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
}
export namespace BudgetResponseEmbed {
}


