/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetType } from './budgetType';


export interface BudgetPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled: boolean;
    /**
     * This represents the name of the resource. This should be unique in an organization 
     */
    name: string;
    type: BudgetType;
    /**
     * amount of money 
     */
    amount_limit: number;
    alert_threshold?: number | null;
    /**
     * List of department ids 
     */
    department_ids: Array<string>;
    /**
     * List of project ids 
     */
    project_ids: Array<number>;
    /**
     * List of cost center ids 
     */
    cost_center_ids: Array<number>;
    /**
     * List of category ids 
     */
    category_ids: Array<number>;
    observer_ids: Array<string>;
    /**
     * Month number of start of fisical year
     */
    fiscal_year_start_month: number;
}
export namespace BudgetPayload {
}


