/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetResponseBudgetCreator } from './budgetResponseBudgetCreator';
import { BudgetType } from './budgetType';


export interface BudgetResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * This represents the name of the resource. This should be unique in an organization 
     */
    name?: string;
    type?: BudgetType;
    /**
     * amount of money 
     */
    amount_limit?: number;
    alert_threshold?: number | null;
    /**
     * List of department ids 
     */
    department_ids?: Array<string>;
    /**
     * List of project ids 
     */
    project_ids?: Array<number>;
    /**
     * List of cost center ids 
     */
    cost_center_ids?: Array<number>;
    /**
     * List of category ids 
     */
    category_ids?: Array<number>;
    observer_ids?: Array<string>;
    /**
     * Month number of start of fiscal year
     */
    fiscal_year_start_month?: number;
    /**
     * Start date of the current budget interval
     */
    budget_start_date?: string | null;
    /**
     * End date of the current budget interval
     */
    budget_end_date?: string | null;
    budget_creator?: BudgetResponseBudgetCreator;
    /**
     * Amount spent from the budget interval
     */
    amount_spent?: number | null;
    /**
     * Amount remaining in the budget interval
     */
    amount_remaining?: number | null;
    /**
     * Utilisation percentage of the budget interval
     */
    utilisation_percentage?: number | null;
}
export namespace BudgetResponse {
}


