/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of budgets 
 */
export const BudgetType = {
    Weekly: 'WEEKLY',
    Monthly: 'MONTHLY',
    Quarterly: 'QUARTERLY',
    HalfYearly: 'HALF_YEARLY',
    Yearly: 'YEARLY',
    OneTime: 'ONE_TIME'
} as const;
export type BudgetType = typeof BudgetType[keyof typeof BudgetType];

