/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetResponseEmbed } from './budgetResponseEmbed';


export interface BudgetUsageResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    org_id?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    budget_id: string;
    /**
     * Start date of the cycle of the budget
     */
    start_date?: string | null;
    /**
     * End date of the cycle of the budget
     */
    end_date?: string | null;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    budget_observer_ids: Array<string>;
    /**
     * amount of money 
     */
    spent: number;
    /**
     * amount of money 
     */
    amount_limit: number;
    /**
     * List of department ids 
     */
    budget_department_ids?: Array<string>;
    /**
     * List of project ids 
     */
    budget_project_ids?: Array<number>;
    budget: BudgetResponseEmbed;
}

