/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkErrorDataInnerKey } from './bulkErrorDataInnerKey';


export interface BulkErrorDataInner { 
    /**
     * This holds the info of which row contains bad data. 
     */
    row?: number;
    key?: BulkErrorDataInnerKey;
    /**
     * This explains what the error is in `human readable` text 
     */
    message?: string;
}

