/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PreviewFromStatementPayloadStatementMapping } from './previewFromStatementPayloadStatementMapping';
import { CardMappingInInner } from './cardMappingInInner';


export interface CardTransactionFromStatementPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    statement_mapping: PreviewFromStatementPayloadStatementMapping;
    /**
     * This specifies list of statement line items to be ignored in the statement. 
     */
    ignored_line_item_ids: Array<string>;
    /**
     * This specifies list of statement line items which are to be created as RTF missing transactions. 
     */
    rtf_missing_line_item_ids?: Array<string>;
    card_mapping?: Array<CardMappingInInner>;
}

