/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CardMappingInInner { 
    /**
     * Card number from statement 
     */
    statement_card_number?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    corporate_card_id?: string;
}

