/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CardStatsResponseMissingCorporateCardDetailsInner } from './cardStatsResponseMissingCorporateCardDetailsInner';


export interface CardStatsResponse { 
    /**
     * Number of transactions in the statement that are from cards that dont exist on Fyle/are not RTF enrolled. 
     */
    missing_transactions_count: number;
    /**
     * Indicates whether the statement has atleast one card enrolled in RTF. 
     */
    is_rtf_statement: boolean;
    /**
     * Card network of the statement if the statement has atleast one card enrolled in RTF. 
     */
    rtf_card_network?: string | null;
    missing_corporate_card_details?: Array<CardStatsResponseMissingCorporateCardDetailsInner>;
}

