/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CardStatsResponseMissingCorporateCardDetailsInner { 
    /**
     * Specifies the card number on the statement. 
     */
    card_number: string;
    /**
     * Specifies if the card exists on Fyle. 
     */
    is_present: boolean;
    /**
     * Specifies if the card is enrolled for Visa. 
     */
    is_visa_enrolled: boolean;
    /**
     * Specifies if the card is enrolled for Mastercard. 
     */
    is_mastercard_enrolled: boolean;
}

