/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryPayloadOnlyId } from './categoryPayloadOnlyId';


export interface CategoryDeleteSummaryResponseData { 
    /**
     * Count of categories that could be deleted from input categories.
     */
    delete_count?: number;
    /**
     * Categories that could be deleted.
     */
    categories?: Array<CategoryPayloadOnlyId>;
}

