/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CategoryPartial { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * Represents the name of the system_category.
     */
    system_category?: string | null;
    /**
     * Represents the name of the category.
     */
    name?: string;
    /**
     * Represents the name of the sub_category.
     */
    sub_category?: string | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This is a combination of name and sub_category separated by a / and spaces. In case if no sub_category is present it is same as name of the category. 
     */
    display_name?: string;
}

