/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CategoryPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * Represents the name of the category.
     */
    name: string;
    /**
     * Represents the sub category of the category. Note that the name and sub category cannot be same.
     */
    sub_category?: string | null;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * Represents the name of the system_category.
     */
    system_category?: string | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * List of project ids for which this category can be used. If project_ids is null, then this category can be used for any project 
     */
    restricted_project_ids?: Array<number> | null;
    /**
     * - List of IDs of users who can access this category. Default value is `[]`. - `null` value indicates that all users in the org can access this category. - `[]` value indicates that no users in the org can access this category. 
     */
    restricted_spender_user_ids?: Array<string> | null;
}

