/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommuteLocation } from './commuteLocation';


/**
 * Commute details of the employee. This is used to deduct daily commute from the employee\'s mileage expenses. 
 */
export interface CommuteDetails { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number | null;
    /**
     * Home location of the employee. 
     */
    home_location?: CommuteLocation | null;
    /**
     * Work location of the employee. 
     */
    work_location?: CommuteLocation | null;
    /**
     * Distance between home and work location of the employee. 
     */
    distance?: number | null;
    /**
     * Unit of distance. 
     */
    distance_unit?: CommuteDetails.DistanceUnitEnum | null;
}
export namespace CommuteDetails {
    export const DistanceUnitEnum = {
        Km: 'KM',
        Miles: 'MILES'
    } as const;
    export type DistanceUnitEnum = typeof DistanceUnitEnum[keyof typeof DistanceUnitEnum];
}


