/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Value signifying the operator for the field 
 */
export const ContainsOperator = {
    In: 'IN',
    NotIn: 'NOT_IN'
} as const;
export type ContainsOperator = typeof ContainsOperator[keyof typeof ContainsOperator];

