/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CorporateCardPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Specifies the name of bank who issued the card. 
     */
    bank_name: string;
    /**
     * Specifies the masked number of the card. Add only masked card-numbers, last four digits of the card. 
     */
    card_number: string;
    /**
     * String denoting the card holder\'s name 
     */
    cardholder_name?: string | null;
    /**
     * signifies the source of how card is added and how further card transactions could be synced 
     */
    data_feed_source?: string | null;
    /**
     * Id given by external systems like Gmail. To identify whether that entity has been already added to Fyle or not. 
     */
    code?: string | null;
    /**
     * Signifies when this card was last synced. 
     */
    last_synced_at?: string | null;
    /**
     * Signifies the unique nickname assigned to the card 
     */
    nickname?: string | null;
}

