/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserOutNullableExampleNull } from './userOutNullableExampleNull';


export interface CorporateCardUnassignResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id: string;
    /**
     * The unique id of an user to whom the card is assigned 
     */
    user_id: string | null;
    user: UserOutNullableExampleNull | null;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at: string;
    /**
     * Specifies the name of bank who issued the card. 
     */
    bank_name: string;
    /**
     * Specifies the masked number of the card. Add only masked card-numbers, last four digits of the card. 
     */
    card_number: string;
    /**
     * String denoting the card holder\'s name 
     */
    cardholder_name: string | null;
    /**
     * signifies the source of how card is added and how further card transactions could be synced 
     */
    data_feed_source: string | null;
    /**
     * Id given by external systems like Gmail. To identify whether that entity has been already added to Fyle or not. 
     */
    code: string | null;
    /**
     * Signifies when this card was last synced. 
     */
    last_synced_at: string | null;
    /**
     * Signifies when this card was last assigned. 
     */
    last_assigned_at: string | null;
    /**
     * The unique id of an user who assigned the card. 
     */
    assignor_user_id: string | null;
    /**
     * If the card is a test card 
     */
    is_dummy: boolean;
    /**
     * Signifies when the card was ready to be verified 
     */
    last_ready_for_verification_at: string | null;
    /**
     * If the card is enrolled with real time feed from visa 
     */
    is_visa_enrolled: boolean;
    /**
     * If the card is enrolled with realtime feed from Mastercard 
     */
    is_mastercard_enrolled: boolean;
    /**
     * If the card is enrolled with realtime feed from Capital One 
     */
    is_capitalone_enrolled: boolean | null;
    /**
     * Signifies when the last card verification was attempted 
     */
    last_verification_attempt_at: string | null;
    /**
     * Verification status of the corporate card 
     */
    verification_status: string;
    /**
     * Signifies when the card was verified 
     */
    last_verified_at: string | null;
    /**
     * The unique id of the virtual card, if the card is created from virtual card. 
     */
    virtual_card_id: string | null;
    /**
     * Status of the virtual card 
     */
    virtual_card_state: CorporateCardUnassignResponse.VirtualCardStateEnum | null;
    /**
     * Unique nickname assigned to the card 
     */
    nickname: string | null;
    /**
     * The total number of transactions for the card, in Fyle 
     */
    total_transactions_count: number;
    /**
     * The total number of unassigned transactions for the card, in Fyle 
     */
    unassigned_transactions_count: number;
}
export namespace CorporateCardUnassignResponse {
    export const VirtualCardStateEnum = {
        Active: 'ACTIVE',
        Preactive: 'PREACTIVE',
        Inactive: 'INACTIVE',
        Expired: 'EXPIRED',
        Deleted: 'DELETED',
        Used: 'USED'
    } as const;
    export type VirtualCardStateEnum = typeof VirtualCardStateEnum[keyof typeof VirtualCardStateEnum];
}


