/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CorporateCardStatsResponse { 
    /**
     * This field indicates the total count of cards. 
     */
    count?: number;
    /**
     * This field indicates the total count of transactions, present for the cards. 
     */
    transactions_count?: number;
}

