/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CorporateCardTransactionMetadata } from './corporateCardTransactionMetadata';


export interface CorporateCardTransactionPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * amount of money 
     */
    amount: number;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency: string;
    /**
     * signifies when this card transaction was made. This date cannot be in future. 
     */
    spent_at: string | null;
    /**
     * signifies post date of a card transaction. This date cannot be in future. 
     */
    post_date?: string | null;
    /**
     * Holds the description of the card transaction 
     */
    description?: string | null;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency?: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount?: number | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * String denoting the name of the vendor to which the card transaction was made. Note: This is not same as the merchant added in Fyle but just a string 
     */
    merchant?: string | null;
    /**
     * String denoting the category of the card transaction Note: This is not same as the category added in Fyle but just a string 
     */
    category?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    mcc?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    corporate_card_id: string;
    metadata?: CorporateCardTransactionMetadata | null;
}

