/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CorporateCardTransactionMetadata } from './corporateCardTransactionMetadata';
import { CorporateCardResponseEmbed } from './corporateCardResponseEmbed';
import { MatchedExpenseResponseEmbed } from './matchedExpenseResponseEmbed';
import { UserPartialNullable } from './userPartialNullable';


export interface CorporateCardTransactionPostResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id: string;
    /**
     * The unique id of an user to whom the card transaction is assigned. 
     */
    readonly user_id: string | null;
    user: UserPartialNullable | null;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at: string;
    /**
     * amount of money 
     */
    amount: number;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency: string;
    /**
     * signifies when this card transaction was made. This date cannot be in future. 
     */
    spent_at: string;
    /**
     * signifies post date of a card transaction. This date cannot be in future. 
     */
    post_date: string | null;
    /**
     * Holds the description of the card transaction 
     */
    description: string | null;
    /**
     * If the transaction is created by statement uploaded then this key refers to the source statement. 
     */
    statement_id: string | null;
    /**
     * Determines whether this card transaction can be deleted or not. 
     */
    can_delete: boolean | null;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount: number | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code: string | null;
    /**
     * String denoting the name of the vendor to which the card transaction was made. Note: This is not same as the merchant added in Fyle but just a string 
     */
    merchant: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    mcc?: string | null;
    /**
     * String denoting the category of the card transaction Note: This is not same as the category added in Fyle but just a string 
     */
    category: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    corporate_card_id: string;
    corporate_card: CorporateCardResponseEmbed;
    /**
     * The unique id of an user who assigned the card transaction. 
     */
    assignor_user_id: string | null;
    assignor_user: UserPartialNullable | null;
    /**
     * Determines whether this card transaction is assigned. 
     */
    is_assigned: boolean;
    /**
     * Signifies when this card transaction was last assigned. 
     */
    last_assigned_at: string | null;
    /**
     * Determines whether this card transaction is marked as personal transaction made on the corporate card. 
     */
    is_marked_personal: boolean;
    /**
     * Signifies when this card transaction was last marked personal. 
     */
    last_marked_personal_at: string | null;
    /**
     * Determines whether this card transaction is dismissed. 
     */
    is_dismissed: boolean;
    /**
     * Signifies when this card transaction was last dismissed. 
     */
    last_dismissed_at: string | null;
    /**
     * Signifies when this card transaction is auto_matched. 
     */
    is_auto_matched: boolean;
    /**
     * Holds the expense ids which are automatically suggested to be matched by the system 
     */
    auto_suggested_expense_ids: Array<string>;
    /**
     * signifies when this expense was auto matched. 
     */
    last_auto_matched_at: string | null;
    /**
     * Holds the expense ids which are matched to this card transaction 
     */
    matched_expense_ids: Array<string>;
    matched_expenses: Array<MatchedExpenseResponseEmbed>;
    /**
     * signifies when this expense was last matched by user. 
     */
    last_user_matched_at: string | null;
    /**
     * Determines whether this CCC transaction has been exported to external accounting system or not. 
     */
    is_exported: boolean | null;
    metadata: CorporateCardTransactionMetadata | null;
}

