/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CorporateCardResponseEmbed { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Specifies the name of bank who issued the card. 
     */
    bank_name?: string;
    /**
     * Specifies the masked number of the card. Add only masked card-numbers, last four digits of the card. 
     */
    card_number?: string;
    /**
     * Unique nickname assigned to the card 
     */
    nickname?: string | null;
    /**
     * String denoting the card holder\'s name 
     */
    cardholder_name?: string | null;
    /**
     * Specifies the last 4 digits of the card number. 
     */
    masked_number?: string;
    /**
     * String denoting the card holder\'s full name 
     */
    user_full_name?: string | null;
    /**
     * String denoting the card holder\'s email 
     */
    user_email?: string | null;
}

