/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportsExportConfigSeparateLineItemsEntry } from './reportsExportConfigSeparateLineItemsEntry';
import { CorporateCardTransactionsExportConfigColumnsInner } from './corporateCardTransactionsExportConfigColumnsInner';


export interface CorporateCardTransactionsExportConfig { 
  [key: string]: any | any;


    /**
     * Type of the export file. 
     */
    type?: CorporateCardTransactionsExportConfig.TypeEnum;
    /**
     * Whether to show the header in the export file. Only required for CSV and XLSX exports. 
     */
    is_header_visible?: boolean;
    separate_line_items_entry?: ReportsExportConfigSeparateLineItemsEntry;
    /**
     * Configure the columns to show in the export file. Only required for CSV and XLSX exports. 
     */
    columns?: Array<CorporateCardTransactionsExportConfigColumnsInner>;
}
export namespace CorporateCardTransactionsExportConfig {
    export const TypeEnum = {
        Xlsx: 'xlsx',
        Csv: 'csv'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


