/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensesExportConfigColumnFormulaParametersInner } from './expensesExportConfigColumnFormulaParametersInner';


/**
 * Export column formula is a expression that is used to transform the data. Refer https://www.fylehq.com/help/en/articles/4422306-advanced-export-formulas for more details. 
 */
export interface CorporateCardTransactionsExportConfigColumnFormula { 
    'function'?: string;
    parameters?: Array<ExpensesExportConfigColumnFormulaParametersInner>;
}

