/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CorporateCardTransactionsDeleteSummaryResponse { 
    /**
     * This field indicates the count of corporate card transactions that can be deleted. 
     */
    delete_count?: number;
    /**
     * This field indicates the sum of amount of the corporate card transactions that can be deleted. 
     */
    delete_amount?: number;
}

