/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CorporateCardTransactionMatchPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    expense_ids: Array<string>;
}

