/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CorporateCardTransactionsStatsResponse { 
    /**
     * This field indicates the count of corporate card transactions. 
     */
    count?: number;
    /**
     * This field indicates the sum of amount of the debit type corporate card transactions. 
     */
    debit_amount?: number;
    /**
     * This field indicates the sum of amount of the credit type corporate card transactions. 
     */
    credit_amount?: number;
}

