/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CorporateCardStatsPayload { 
    /**
     * This field contains the query param string, which can be used to fetch data for assigned and unassigned cards. 
     */
    query_params?: string;
}

