/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Additional data that can optionally be stored. Some example details are added for reference. 
 */
export interface CorporateCardTransactionMetadata { 
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    merchant_category_code?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    flight_merchant_category_code?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    flight_supplier_name?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    flight_travel_agency_name?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    flight_ticket_number?: string | null;
    /**
     * Additional floating point numeric details of the card transaction. Same as double precision.
     */
    flight_total_fare?: number | null;
    /**
     * Additional details of the card transaction. <a href=\"https://tools.ietf.org/html/rfc3339#section-5.6\">RFC 3339, section 5.6 compliant timestamp.</a> 
     */
    flight_travel_date?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    flight_service_class?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    flight_carrier_code?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    flight_fare_base_code?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    flight_trip_leg_number?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    hotel_merchant_category_code?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    hotel_supplier_name?: string | null;
    /**
     * Additional details of the card transaction. <a href=\"https://tools.ietf.org/html/rfc3339#section-5.6\">RFC 3339, section 5.6 compliant timestamp.</a> 
     */
    hotel_checked_in_at?: string | null;
    /**
     * Additional integer details of the card transaction.
     */
    hotel_nights?: number | null;
    /**
     * Additional details of the card transaction. <a href=\"https://tools.ietf.org/html/rfc3339#section-5.6\">RFC 3339, section 5.6 compliant timestamp.</a> 
     */
    hotel_checked_out_at?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    hotel_country?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    hotel_city?: string | null;
    /**
     * Additional floating point numeric details of the card transaction. Same as double precision.
     */
    hotel_total_fare?: number | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    fleet_product_merchant_category_code?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    fleet_product_supplier_name?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    fleet_service_merchant_category_code?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    fleet_service_supplier_name?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    car_rental_merchant_category_code?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    car_rental_supplier_name?: string | null;
    /**
     * Additional details of the card transaction. <a href=\"https://tools.ietf.org/html/rfc3339#section-5.6\">RFC 3339, section 5.6 compliant timestamp.</a> 
     */
    car_rental_started_at?: string | null;
    /**
     * Additional integer details of the card transaction.
     */
    car_rental_days?: number | null;
    /**
     * Additional details of the card transaction. <a href=\"https://tools.ietf.org/html/rfc3339#section-5.6\">RFC 3339, section 5.6 compliant timestamp.</a> 
     */
    car_rental_ended_at?: string | null;
    /**
     * Additional details of the card transaction. <a href=\"https://tools.ietf.org/html/rfc3339#section-5.6\">RFC 3339, section 5.6 compliant timestamp.</a> 
     */
    general_ticket_issued_at?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    general_ticket_number?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    general_issuing_carrier?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    general_travel_agency_name?: string | null;
    /**
     * Additional string details of the card transaction. Can hold details upto 256 characters in length.
     */
    general_travel_agency_code?: string | null;
    /**
     * Additional floating point numeric details of the card transaction. Same as double precision.
     */
    general_ticket_total_fare?: number | null;
    /**
     * Additional floating point numeric details of the card transaction. Same as double precision.
     */
    general_ticket_total_tax?: number | null;
    /**
     * Additional text details of the card transaction.
     */
    merchant_address?: string | null;
}

