/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CostCenterPayloadRestrictedSpenderUserGroup } from './costCenterPayloadRestrictedSpenderUserGroup';


export interface CostCenterPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * This represents the name of the cost center. 
     */
    name: string;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This represents the description of the resource. 
     */
    description?: string | null;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * - List of IDs of users who can access this object. - `null` value indicates that all users in the org can access this object. - `[]` value indicates that no users in the org can access this object. - **Note:**   - _Either `restricted_spender_user_ids` or `restricted_spender_user_group` key can be used to set restrictions. Both the keys can\'t be used together._   - _While creating cost_centers, if both `restricted_spender_user_ids` and `restricted_spender_user_group` keys are not set, restrictions defaults to `\"restricted_spender_user_group\": {\"with_no_cost_center_restrictions\": \"true\"}`_   - _While updating cost_centers, if both `restricted_spender_user_ids` and `restricted_spender_user_group` keys are not set, restrictions remains unchanged._ 
     */
    restricted_spender_user_ids?: Array<string> | null;
    restricted_spender_user_group?: CostCenterPayloadRestrictedSpenderUserGroup;
}

