/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CostCenterPayloadRestrictedSpenderUserGroup { 
    /**
     * - If you want the cost_center to be visible to all the users in the org with no cost center restrictions,   you can set this key to True. <br> **Note:**   - _Either `restricted_spender_user_ids` or `restricted_spender_user_group` key can be used to set restrictions. Both the keys can\'t be used together._   - _While creating cost_centers, if both `restricted_spender_user_ids` and `restricted_spender_user_group` keys are not set, restrictions defaults to `\"restricted_spender_user_group\": {\"with_no_cost_center_restrictions\": \"true\"}`_   - _While updating cost_centers, if both `restricted_spender_user_ids` and `restricted_spender_user_group` keys are not set, restrictions remains unchanged._ 
     */
    with_no_cost_center_restrictions: boolean;
}

