/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Delegatees { 
    /**
     * Delegation id. 
     */
    id?: number;
    /**
     * Type of delegation. 
     */
    type?: Delegatees.TypeEnum;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly user_id?: string;
    /**
     * Email of the delegatee. 
     */
    email?: string;
    /**
     * Full name of the delegatee. 
     */
    full_name?: string;
    /**
     * Date and time from which the delegation is active. 
     */
    start_at?: string;
    /**
     * Date and time till which the delegation is active. If null, delegation is active indefinitely. 
     */
    end_at?: string | null;
}
export namespace Delegatees {
    export const TypeEnum = {
        ShortTerm: 'SHORT_TERM',
        Permanent: 'PERMANENT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


