/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Delegatee { 
    /**
     * User ID of the delegatee. 
     */
    user_id?: string;
    /**
     * Date and time from which the delegation is active. 
     */
    start_at?: string;
    /**
     * Date and time till which the delegation is active. If null, delegation is active indefinitely. 
     */
    end_at?: string | null;
}

