/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DepartmentPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * This represents the name of the resource. This should be unique in an organization 
     */
    name: string;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This represents the description of the resource. 
     */
    description?: string | null;
    sub_department?: string | null;
    /**
     * List of IDs of users who are head of the department. 
     */
    department_head_user_ids?: Array<string | null>;
    /**
     * Link to an external document that would be shared with employees 
     */
    doc_url?: string | null;
}

