/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartial } from './userPartial';


export interface DepartmentResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * This represents the name of the resource. This should be unique in an organization 
     */
    name?: string;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This represents the description of the resource. 
     */
    description?: string | null;
    sub_department?: string | null;
    /**
     * List of IDs of users who are head of the department. 
     */
    department_head_user_ids?: Array<string | null>;
    /**
     * List of users who are head of the department. 
     */
    department_head_users?: Array<UserPartial> | null;
    /**
     * This is a combination of name and sub_department separated by a / and spaces. In case if no sub_department is present it is same as name of the department. 
     */
    display_name?: string;
    /**
     * Link to an external document that would be shared with employees 
     */
    doc_url?: string | null;
}

