/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DepartmentResponseEmbed { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This represents the name of the resource. This should be unique in an organization 
     */
    name?: string;
    sub_department?: string | null;
    /**
     * This is a combination of name and sub_department separated by a / and spaces. In case if no sub_department is present it is same as name of the department. 
     */
    display_name?: string;
}

