/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldValue } from './customFieldValue';


/**
 * Dependent expense fields details 
 */
export interface DependentExpenseFields { 
    /**
     * This id provided by Fyle to identify the parent expense field. 
     */
    parent_expense_field_id?: number;
    /**
     * This id provided by Fyle to identify the dependent expense field. 
     */
    dependent_expense_field_id?: number;
    /**
     * This id provided by Fyle to identify dependent field value. 
     */
    dependent_expense_field_value_id?: number;
    /**
     * This represents the name of the dependent expense field. 
     */
    name?: string;
    value?: CustomFieldValue | null;
}

