/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DependentExpenseFieldValuesPreviewResponse { 
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * This specifies the `id` of the parent expense field. 
     */
    parent_expense_field_id?: number;
    /**
     * This specifies the `id` of the dependent expense field. 
     */
    expense_field_id?: number;
    /**
     * This specifies the text value of the parent expense field. 
     */
    parent_expense_field_value?: string;
    /**
     * This specifies the text values of the dependent expense field upto 20 items. 
     */
    expense_field_values?: Array<string>;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
}

