/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DependentExpenseFieldValuesUploadPayload { 
    /**
     * This specifies the `id` of the parent expense field. 
     */
    parent_expense_field_id: number;
    /**
     * This specifies the `id` of the dependent expense field. 
     */
    expense_field_id: number;
    /**
     * File `id` of the uploaded excel file. 
     */
    file_id: string;
}

