/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Unit of distance travelled.
 */
export const DistanceUnit = {
    Km: 'KM',
    Miles: 'MILES'
} as const;
export type DistanceUnit = typeof DistanceUnit[keyof typeof DistanceUnit];

