/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartial } from './userPartial';
import { UserPartialNullable } from './userPartialNullable';


export interface EmployeeSummaryResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    user_id?: string | null;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    user?: UserPartial;
    /**
     * List of users who are approvers for this employee. 
     */
    approver_users?: Array<UserPartialNullable> | null;
    /**
     * Total amount of all expenses in the COMPLETE state. 
     */
    unreported_expenses_total?: number | null;
    /**
     * Total amount of all reports in the APPROVER_PENDING state. 
     */
    unapproved_reports_total?: number | null;
    /**
     * Total amount of reimbursable expenses. 
     */
    reimbursable_amount?: number | null;
    /**
     * List of advance wallet IDs associated with the employee. 
     */
    advance_account_ids?: Array<string> | null;
    /**
     * Total amount of all advance wallets associated with the employee. 
     */
    advance_accounts_balance?: number | null;
    /**
     * Total liability payable to the employee. 
     */
    liability_amount?: number | null;
}

