/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeesUploadResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly user_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    file_id?: string;
    /**
     * State of this upload. 
     */
    state?: EmployeesUploadResponse.StateEnum;
    /**
     * File `id` of the error excel file generated after processing the uploaded file. 
     */
    error_file_id?: string | null;
}
export namespace EmployeesUploadResponse {
    export const StateEnum = {
        Pending: 'PENDING',
        Processing: 'PROCESSING',
        Success: 'SUCCESS',
        Error: 'ERROR'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


