/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartial } from './userPartial';
import { DepartmentResponseEmbed } from './departmentResponseEmbed';


export interface EmployeeResponseEmbed { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly user_id?: string;
    user?: UserPartial;
    /**
     * This field refers to any string that the client programs can use to refer to an employee\'s unique id. This could be any field such as an UUID from an Active Directory server or employee id in a HRMS system. 
     */
    code?: string | null;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    department_id?: string | null;
    department?: DepartmentResponseEmbed | null;
}

