/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeFieldPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * This specifies the name of the employee field. 
     */
    name: string;
    /**
     * This specifies the option values of the employee field in case on SELECT or MULTI_SELECT type. 
     */
    options?: Array<string>;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled: boolean;
    /**
     * This specifies if the employee field is mandatory or not. 
     */
    is_mandatory: boolean;
    /**
     * This field specifies the type of the employee field. 
     */
    type: EmployeeFieldPayload.TypeEnum;
}
export namespace EmployeeFieldPayload {
    export const TypeEnum = {
        Text: 'TEXT',
        Number: 'NUMBER',
        Select: 'SELECT',
        Boolean: 'BOOLEAN',
        MultiSelect: 'MULTI_SELECT',
        Location: 'LOCATION',
        Date: 'DATE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


