/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeesDownloadResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * File `id` of the excel file generated after processing the download request. 
     */
    file_id?: string | null;
    /**
     * State of this download. 
     */
    state?: EmployeesDownloadResponse.StateEnum;
}
export namespace EmployeesDownloadResponse {
    export const StateEnum = {
        Success: 'SUCCESS',
        Error: 'ERROR',
        Pending: 'PENDING',
        Processing: 'PROCESSING'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


