/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Locale } from './locale';
import { EmployeeResponseAchAccount } from './employeeResponseAchAccount';
import { PerDiemRateResponseEmbed } from './perDiemRateResponseEmbed';
import { UserPartial } from './userPartial';
import { JoinedAt } from './joinedAt';
import { LevelResponseEmbed } from './levelResponseEmbed';
import { MileageSettings } from './mileageSettings';
import { MileageRateResponseEmbed } from './mileageRateResponseEmbed';
import { DepartmentResponseEmbed } from './departmentResponseEmbed';
import { Role } from './role';
import { CategoryPartial } from './categoryPartial';
import { Delegatees } from './delegatees';
import { CustomField } from './customField';
import { FlattenedCustomField } from './flattenedCustomField';
import { ProjectPartial } from './projectPartial';
import { CostCenterPartial } from './costCenterPartial';


export interface EmployeeResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    user_id?: string | null;
    user?: UserPartial;
    business_unit?: string | null;
    /**
     * This field refers to any string that the client programs can use to refer to an employee\'s unique id. This could be any field such as an UUID from an Active Directory server or employee id in a HRMS system. 
     */
    code?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    department_id?: string | null;
    department?: DepartmentResponseEmbed | null;
    /**
     * This field indicates whether the employee is enabled in the org. 
     */
    is_enabled?: boolean;
    joined_at?: JoinedAt | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    level_id?: string | null;
    level?: LevelResponseEmbed | null;
    location?: string | null;
    roles?: Array<Role>;
    special_email?: string;
    title?: string | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField>;
    flattened_custom_field?: FlattenedCustomField;
    /**
     * List of project ids that this employee is allowed to access. 
     */
    project_ids?: Array<number>;
    /**
     * List of projects that this employee is allowed to access. 
     */
    projects?: Array<ProjectPartial>;
    /**
     * List of cost center ids that this employee is allowed to access. [] (empty array) means access to all cost centers. 
     */
    cost_center_ids?: Array<number>;
    /**
     * List of cost_ enters that this employee is allowed to access. [] (empty array) means access to all cost centers. 
     */
    cost_centers?: Array<CostCenterPartial>;
    /**
     * List of per diem rate ids that this employee is allowed to access. 
     */
    per_diem_rate_ids?: Array<number>;
    /**
     * List of per diem rates that this employee is allowed to access. 
     */
    per_diem_rates?: Array<PerDiemRateResponseEmbed>;
    /**
     * List of mileage rate ids that this employee is allowed to access. 
     */
    mileage_rate_ids?: Array<number>;
    /**
     * List of mileage rates that this employee is allowed to access. 
     */
    mileage_rates?: Array<MileageRateResponseEmbed>;
    /**
     * List of IDs of users who are approvers for this employee. Maximum 3. 
     */
    approver_user_ids?: Array<string> | null;
    /**
     * List of users who are approvers for this employee. 
     */
    approver_users?: Array<UserPartial> | null;
    /**
     * This boolean field represents whether the employee has accepted the current org\'s invite by verifying his/her email or not. 
     */
    has_accepted_invite?: boolean;
    /**
     * The Account number of the bank account of the Employee. 
     */
    branch_account?: Array<string> | null;
    /**
     * IFSC code of the bank account of the Employee. Must be a 11 digit alphanumeric code. 
     */
    branch_ifsc?: Array<string> | null;
    /**
     * Mobile number of the employee 
     */
    mobile?: Array<string> | null;
    /**
     * Flag which indicates if mobile is verified or not. 
     */
    is_mobile_verified?: boolean | null;
    locale?: Locale | null;
    mileage_settings?: MileageSettings | null;
    ach_account?: EmployeeResponseAchAccount | null;
    /**
     * List of users who are delegatees for this employee. 
     */
    delegatees?: Array<Delegatees> | null;
    /**
     * List of category ids that this employee is allowed to access. 
     */
    category_ids?: Array<number>;
    /**
     * List of categories that this employee is allowed to access. 
     */
    categories?: Array<CategoryPartial>;
}

