/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ACH account details of the employee. 
 */
export interface EmployeeResponseAchAccount { 
    /**
     * This field indicates whether employee has added ach account 
     */
    added?: boolean | null;
    /**
     * This field indicates whether employee\'s ach account is verified. 
     */
    verified?: boolean | null;
}

