/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartial } from './userPartial';
import { EmployeeResponseEmbedForReportAchAccount } from './employeeResponseEmbedForReportAchAccount';
import { JoinedAt } from './joinedAt';
import { LevelResponseEmbed } from './levelResponseEmbed';
import { DepartmentResponseEmbed } from './departmentResponseEmbed';


export interface EmployeeResponseEmbedForReport { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly user_id?: string;
    user?: UserPartial;
    /**
     * This field refers to any string that the client programs can use to refer to an employee\'s unique id. This could be any field such as an UUID from an Active Directory server or employee id in a HRMS system. 
     */
    code?: string | null;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * This represents the name of the organization. This should be unique for all organizations 
     */
    org_name?: string;
    department_id?: string | null;
    department?: DepartmentResponseEmbed | null;
    level?: LevelResponseEmbed | null;
    ach_account?: EmployeeResponseEmbedForReportAchAccount;
    business_unit?: string | null;
    location?: string | null;
    title?: string | null;
    /**
     * This boolean field represents whether the employee has accepted the current org\'s invite by verifying his/her email or not. 
     */
    has_accepted_invite?: boolean;
    /**
     * This field indicates whether the employee is enabled in the org. 
     */
    is_enabled?: boolean;
    /**
     * Mobile number of the employee 
     */
    mobile?: Array<string> | null;
    joined_at?: JoinedAt | null;
}

