/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeFiltersPayload { 
    /**
     * This represents the name of the filter. 
     */
    name: string;
    /**
     * This indicates if the filter should be shared with others in the org. 
     */
    is_shared?: boolean | null;
    /**
     * This represents a query string which will be used to filter the data. 
     */
    query_string: string;
}

