/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountMinimal } from './accountMinimal';


export interface EmployeeAccountSummaryResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    org_currency?: string;
    /**
     * An immutable field that represents the email address of the employee. Must be compliant with <a href=\'https://www.ietf.org/rfc/rfc822.txt\'>RFC 822.</a> 
     */
    user_email?: string;
    /**
     * This represents the full name of the employee 
     */
    user_full_name?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    cash_account_id?: string;
    cash_account?: AccountMinimal;
    /**
     * amount of money 
     */
    cash_account_balance?: number;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    ccc_account_id?: string;
    ccc_account?: AccountMinimal;
    /**
     * amount of money 
     */
    ccc_account_balance?: number;
    advance_account_ids?: Array<string>;
    advance_accounts?: Array<AccountMinimal>;
    /**
     * amount of money 
     */
    advance_accounts_balance?: number;
    /**
     * This indicates whether the user\'s accounts can be settled or not. 
     */
    is_settleable?: boolean;
}

