/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MissingMandatoryFields } from './missingMandatoryFields';
import { ExpenseResponseReportLastApprovedAt } from './expenseResponseReportLastApprovedAt';
import { ReportApprovalPartial } from './reportApprovalPartial';
import { MileageRateResponseEmbedForExpense } from './mileageRateResponseEmbedForExpense';
import { PolicyChecks } from './policyChecks';
import { ActivityDetails } from './activityDetails';
import { ExpenseCustomField } from './expenseCustomField';
import { ExpenseRuleDataPayload } from './expenseRuleDataPayload';
import { ExpenseVerificationPartial } from './expenseVerificationPartial';
import { ExpenseResponseAccountingExportSummary } from './expenseResponseAccountingExportSummary';
import { PerDiemRateResponseEmbed } from './perDiemRateResponseEmbed';
import { ReportResponseEmbed } from './reportResponseEmbed';
import { FileResponseEmbed } from './fileResponseEmbed';
import { UserPartial } from './userPartial';
import { ExpenseResponseReportLastPaidAt } from './expenseResponseReportLastPaidAt';
import { CategoryPartial } from './categoryPartial';
import { ExtractedData } from './extractedData';
import { CommuteDetails } from './commuteDetails';
import { AccountResponseEmbed } from './accountResponseEmbed';
import { MatchedCorporateCardTransactionPartial } from './matchedCorporateCardTransactionPartial';
import { TaxGroup } from './taxGroup';
import { FlattenedCustomField } from './flattenedCustomField';
import { ProjectPartial } from './projectPartial';
import { CostCenterPartial } from './costCenterPartial';
import { EmployeeResponseEmbedForExpense } from './employeeResponseEmbedForExpense';
import { Location } from './location';


export interface ExpenseResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly user_id: string;
    user: UserPartial;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at: string;
    /**
     * signifies when this expense was made. This date cannot be in future. 
     */
    spent_at: string | null;
    /**
     * The name of the client app which is creating the expense. if its a thrid party app, it prefixed with TPA_. Ex - If you pass SLACK_APP, it will be saved as TPA_SLACK_APP. If not passed, source is saved as TPA. 
     */
    source: string;
    /**
     * String denoting the name of the merchant to which the Expense was made. 
     */
    merchant: string | null;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency: string;
    /**
     * The amount for which the expense was/will-be fyled. The amount will be in the currency that the organization\'s home currency.<br>  Note that, this field is calculated from admin_amount, policy_amount, claim_amount.  if admin_amount is present then this value will be same admin_amount. if policy_amount is present then this value will be same policy_amount. else this should be same as claim_amount. 
     */
    amount: number | null;
    /**
     * The expense amount as claimed by user. 
     */
    claim_amount: number | null;
    /**
     * The expense amount set by policy. 
     */
    policy_amount: number | null;
    /**
     * The expense amount which is modified by admin or approver. This could be null if admin or approver has not edited your expense. 
     */
    admin_amount: number | null;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount: number | null;
    purpose: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    cost_center_id: number | null;
    cost_center: CostCenterPartial | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    category_id: number | null;
    category: CategoryPartial | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    project_id: number | null;
    project: ProjectPartial | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    source_account_id: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_wallet_id: string | null;
    source_account: AccountResponseEmbed;
    /**
     * Tax amount as setup by your organization. - _Note:_   - Tax amount cannot be greater than the expense amount. 
     */
    tax_amount: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    tax_group_id: string | null;
    /**
     * This fields marks whether a given expense is billable a not.
     */
    is_billable: boolean | null;
    /**
     * This fields marks whether a given expense is reimbursable a not.
     */
    is_reimbursable: boolean;
    /**
     * Actual distance travelled by employee in travel related expenses.
     */
    distance: number | null;
    /**
     * Unit of distance travelled.
     */
    distance_unit: ExpenseResponse.DistanceUnitEnum | null;
    /**
     * Distance computed by Fyle in mileage expenses.
     */
    mileage_calculated_distance: number | null;
    /**
     * Amount computed by Fyle in mileage expenses.
     */
    mileage_calculated_amount: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    mileage_rate_id: number | null;
    mileage_rate: MileageRateResponseEmbedForExpense | null;
    /**
     * Flag stating whether this was a round trip or not.
     */
    mileage_is_round_trip: boolean | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    per_diem_rate_id: number | null;
    per_diem_rate: PerDiemRateResponseEmbed | null;
    /**
     * Specific to per diem related expenses, number of days for which per diem claim is made. 
     */
    per_diem_num_days: number | null;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    started_at: string | null;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    ended_at: string | null;
    /**
     * This field is applicable only for `Flight`, `Train`, `Bus`, `Taxi` category. index 0 holds onward journey class, index 1 holds return journey travel class. 
     */
    travel_classes: Array<string>;
    /**
     * This field is applicable for only `Hotel` category. 
     */
    hotel_is_breakfast_provided: boolean | null;
    /**
     * This field will be present for travel related categories. For travel between Place A to Place B, this array will contain two items, From location at array index 0 and To location at array index 1. For travel between Place A to Place c and stopping at Place B, this 
     */
    locations: Array<Location>;
    /**
     * Expense custom fields 
     */
    custom_fields: Array<ExpenseCustomField>;
    custom_fields_flattened?: FlattenedCustomField;
    /**
     * Id given by external systems like Gmail. To identify whether that entity has been already added to Fyle or not. 
     */
    code: string | null;
    /**
     * The state of the Expense.
     */
    state: ExpenseResponse.StateEnum;
    /**
     * readable state name
     */
    state_display_name: string;
    /**
     * This is user visible identifier for an expense. This field can be used as reference in UI. 
     */
    readonly seq_num: string;
    /**
     * Unique id given by Fyle to identify an Expense Report. 
     */
    report_id: string | null;
    /**
     * signifies when this expense was added to a report. If this expense is not added to a report, then this could be null. 
     */
    added_to_report_at: string | null;
    report: ReportResponseEmbed | null;
    /**
     * Determines whether this expense has been verified by a verifier. 
     */
    is_verified: boolean | null;
    /**
     * signifies when this expense was verified. 
     */
    last_verified_at: string | null;
    /**
     * Determines whether a receipt is missing for this expense when it is required. 
     */
    is_receipt_mandatory: boolean | null;
    /**
     * Determines whether this expense has been exported to external accounting system or not. 
     */
    is_exported: boolean | null;
    /**
     * signifies when this expense was exported to an external accounting system.
     */
    last_exported_at: string | null;
    file_ids: Array<string>;
    files: Array<FileResponseEmbed>;
    /**
     * List of report_approval objects 
     */
    approvals?: Array<ReportApprovalPartial>;
    /**
     * List of verification objects 
     */
    verifications?: Array<ExpenseVerificationPartial>;
    /**
     * This id provided by Fyle to uniquely identify an employee within an organization. This id is always prefixed with `ou`. 
     */
    employee_id?: string;
    employee: EmployeeResponseEmbedForExpense | null;
    /**
     * Signifies when this corporate card transaction is auto_matched. 
     */
    is_corporate_card_transaction_auto_matched: boolean;
    /**
     * Holds the corporate card transaction ids which are matched to this expense 
     */
    matched_corporate_card_transaction_ids: Array<string>;
    /**
     * Holds the corporate card transactions which are matched to this expense. NOTE: The data of this field is not realtime. It will get updated later even if `matched_corporate_card_transaction_ids` is already up-to-date. 
     */
    matched_corporate_card_transactions: Array<MatchedCorporateCardTransactionPartial>;
    /**
     * signifies when this expense was last settled. 
     */
    last_settled_at: string | null;
    missing_mandatory_fields: MissingMandatoryFields;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly creator_user_id: string;
    activity_details: ActivityDetails | null;
    extracted_data: ExtractedData | null;
    /**
     * This fields marks whether a given expense is manually flagged or not.
     */
    is_manually_flagged: boolean | null;
    /**
     * This fields marks whether a given expense is flagged by policy or not.
     */
    is_policy_flagged: boolean | null;
    /**
     * This id provided by Fyle to identify an object. 
     */
    split_group_id: string | null;
    /**
     * The amount of expense before splitting. 
     */
    split_group_amount?: number | null;
    /**
     * This fields marks if physical has been collected for the given expense. 
     */
    is_physical_bill_submitted: boolean | null;
    /**
     * Signifies if and when the physical bill for this report was submitted. 
     */
    physical_bill_submitted_at: string | null;
    /**
     * This id is provided by Fyle to identify an Expense Rule. 
     */
    expense_rule_id?: string | null;
    expense_rule_data?: ExpenseRuleDataPayload | null;
    /**
     * Whether the expense is split. 
     */
    is_split?: boolean | null;
    tax_group?: TaxGroup | null;
    /**
     * Comments added by approvers. NOTE: The data of this field is not realtime. It will get updated later even if rest of fields are already up-to-date. 
     */
    approver_comments?: Array<string>;
    /**
     * Comments added by verifiers. NOTE: The data of this field is not realtime. It will get updated later even if rest of fields are already up-to-date. 
     */
    verifier_comments?: Array<string>;
    policy_checks?: PolicyChecks;
    accounting_export_summary?: ExpenseResponseAccountingExportSummary;
    report_last_paid_at?: ExpenseResponseReportLastPaidAt | null;
    report_last_approved_at?: ExpenseResponseReportLastApprovedAt | null;
    /**
     * Invoice number of the expense. 
     */
    invoice_number: string | null;
    /**
     * Commute deduction type of the expense. 
     */
    commute_deduction?: ExpenseResponse.CommuteDeductionEnum | null;
    /**
     * Commute details id of the expense. This id is provided by Fyle to identify a commute details. 
     */
    commute_details_id?: number | null;
    commute_details?: CommuteDetails | null;
    /**
     * Whether duplicate expenses is detected for this expense or not. 
     */
    is_duplicate_present: boolean;
}
export namespace ExpenseResponse {
    export const DistanceUnitEnum = {
        Km: 'KM',
        Miles: 'MILES'
    } as const;
    export type DistanceUnitEnum = typeof DistanceUnitEnum[keyof typeof DistanceUnitEnum];
    export const StateEnum = {
        Complete: 'COMPLETE',
        Draft: 'DRAFT',
        Paid: 'PAID',
        PaymentProcessing: 'PAYMENT_PROCESSING',
        ApproverPending: 'APPROVER_PENDING',
        PaymentPending: 'PAYMENT_PENDING',
        Approved: 'APPROVED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
    export const CommuteDeductionEnum = {
        OneWay: 'ONE_WAY',
        RoundTrip: 'ROUND_TRIP',
        NoDeduction: 'NO_DEDUCTION'
    } as const;
    export type CommuteDeductionEnum = typeof CommuteDeductionEnum[keyof typeof CommuteDeductionEnum];
}


