/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpensesDuplicateSetsStatsResponse { 
    /**
     * This field represents the total number of expense duplicate sets that match the criteria specified in the query_params within the body of the request. 
     */
    count?: number;
}

