/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Summary of accounting export for this expense. 
 */
export interface ExpenseResponseAccountingExportSummary { 
    state?: ExpenseResponseAccountingExportSummary.StateEnum;
    error_type?: ExpenseResponseAccountingExportSummary.ErrorTypeEnum | null;
    /**
     * URL Endpoint for exported / failed expense
     */
    url?: string;
    /**
     * Third party app id. 
     */
    tpa_id?: string;
}
export namespace ExpenseResponseAccountingExportSummary {
    export const StateEnum = {
        Complete: 'COMPLETE',
        Error: 'ERROR',
        InProgress: 'IN_PROGRESS',
        Skipped: 'SKIPPED',
        Initiated: 'INITIATED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
    export const ErrorTypeEnum = {
        AccountingIntegrationError: 'ACCOUNTING_INTEGRATION_ERROR',
        Mapping: 'MAPPING'
    } as const;
    export type ErrorTypeEnum = typeof ErrorTypeEnum[keyof typeof ErrorTypeEnum];
}


