/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensePolicyFinalDesiredState } from './expensePolicyFinalDesiredState';
import { ExpensePolicyPayloaddividualDesiredStates } from './expensePolicyPayloaddividualDesiredStates';


export interface ExpensePolicyStatesResponse { 
    /**
     * This represents the id of the expense. 
     */
    expense_id?: string;
    individual_desired_states?: Array<ExpensePolicyPayloaddividualDesiredStates>;
    final_desired_state?: ExpensePolicyFinalDesiredState;
}

