/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Operator for the employee_custom_fields. <br> _Format -> field_name: operator_ <br> _Example -> \"Employee Age\": \"GREATER_THAN_EQUAL_TO\"_ <br><br> Supported values based on field type: <br> `Boolean`: `IS`, `NOT_IS` <br> `Date`: `LESS_THAN_EQUAL_TO`, `GREATER_THAN_EQUAL_TO` <br> `Location`: `IN`, `NOT_IN` <br> `Number`: `LESS_THAN_EQUAL_TO`, `GREATER_THAN_EQUAL_TO` <br> `String`: `CONTAINS`, `EQUALS` <br> `Select`: `IN`, `NOT_IN`<br> _Note: This field is mandatory if the field `employee_custom_fields` is present in the request body._ 
 */
export interface ExpensePolicyPayloadEmployeeCustomFieldsOp { 
    field_name?: string;
}

