/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensePolicyExpensesQueryObjectParams } from './expensePolicyExpensesQueryObjectParams';


/**
 * An expense may be violating an expense policy rule due to a group of other expenses. These query params can be used to fetch those expenses because of which this expense is causing a violation. <br> Below params should be ANDed to get the correct list of violating expenses. 
 */
export interface ExpensePolicyExpensesQueryObject { 
    /**
     * Spend start date query param to find the list of violating expenses. 
     */
    limit_start_date?: string;
    /**
     * Spend end date query param to find the list of violating expenses. 
     */
    limit_end_date?: string;
    params?: ExpensePolicyExpensesQueryObjectParams;
}

