/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensePolicyExpensesQueryObject } from './expensePolicyExpensesQueryObject';
import { ExpensePolicyRuleEmbed } from './expensePolicyRuleEmbed';
import { ExpensePolicyPayloaddividualDesiredStatesAmount } from './expensePolicyPayloaddividualDesiredStatesAmount';


export interface ExpenseCheckPoliciesIndividualDesiredStates { 
    /**
     * List of approver ids that the policy calculation suggests adding to report that contains this expense. 
     */
    add_approver_user_ids?: Array<string> | null;
    /**
     * This represents the order of the approver policy related to this individual desired state record. If the policy does not add any approver, this field will be null. 
     */
    approver_policy_order?: number | null;
    /**
     * This represents the type of approver(source) that was added by the approver policy related to this individual desired state record. If the policy does not add any approver, this field will be null. 
     */
    approver_source?: ExpenseCheckPoliciesIndividualDesiredStates.ApproverSourceEnum | null;
    /**
     * This represents the id of the expense policy rule. 
     */
    expense_policy_rule_id?: string;
    expense_policy_rule?: ExpensePolicyRuleEmbed;
    /**
     * This represents the status of policy computation for the input expense object against the policy represented by `expense_policy_rule_id`. If the state is `UNVIOLATED`, it means that the expense is not violating this policy. If the state is `VIOLATION_ACTION_SUCCESS`, it means that the expense is violating this policy and action stated in the object will be applied to the expense when it is saved. However, if the state is `VIOLATION_ACTION_FAILURE`, it means that this policy is violated for the expense but since some approver was missing or not set up properly, it will fail to take action on the expense when it is saved. 
     */
    run_status?: ExpenseCheckPoliciesIndividualDesiredStates.RunStatusEnum;
    /**
     * List of human-readable action summaries that the policy calculation suggests for this expense. Note that, in case some approver was not setup properly for the given violation, this array will contain description of missing approvers. For example, Department approver, Project head, etc. 
     */
    run_result?: Array<string>;
    amount?: ExpensePolicyPayloaddividualDesiredStatesAmount | null;
    expenses_query_object_params?: ExpensePolicyExpensesQueryObject;
}
export namespace ExpenseCheckPoliciesIndividualDesiredStates {
    export const ApproverSourceEnum = {
        PrimaryApprover: 'PRIMARY_APPROVER',
        SecondaryApprover1: 'SECONDARY_APPROVER_1',
        SecondaryApprover2: 'SECONDARY_APPROVER_2',
        ProjectApprover1: 'PROJECT_APPROVER_1',
        ProjectApprover2: 'PROJECT_APPROVER_2',
        DepartmentHeadApprover: 'DEPARTMENT_HEAD_APPROVER',
        EmailApprover: 'EMAIL_APPROVER'
    } as const;
    export type ApproverSourceEnum = typeof ApproverSourceEnum[keyof typeof ApproverSourceEnum];
    export const RunStatusEnum = {
        ViolatedActionSuccess: 'VIOLATED_ACTION_SUCCESS',
        ViolatedActionFailure: 'VIOLATED_ACTION_FAILURE',
        Unviolated: 'UNVIOLATED'
    } as const;
    export type RunStatusEnum = typeof RunStatusEnum[keyof typeof RunStatusEnum];
}


