/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensesExportConfig } from './expensesExportConfig';


export interface ExpensesExportsPayload { 
    /**
     * This field contains the query param string similar to the query params passed in GET call for displaying data in the list view. 
     */
    query_params: string;
    /**
     * List of emails to notify when the export is ready. 
     */
    notify_emails: Array<string>;
    /**
     * Configuration for the export. 
     */
    config: ExpensesExportConfig;
}

