/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensesExportConfigColumnFormula } from './expensesExportConfigColumnFormula';


export interface ExpensesExportConfigColumnsInner { 
    /**
     * Name of the column. 
     */
    name?: string;
    /**
     * Formula to transform the data in the column. 
     */
    formula?: ExpensesExportConfigColumnFormula;
}

