/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseRuleIfPayload } from './expenseRuleIfPayload';
import { ExpenseRulePayloadSet } from './expenseRulePayloadSet';


export interface ExpenseRulePayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    'if': ExpenseRuleIfPayload;
    set: ExpenseRulePayloadSet;
}

