/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseDismissDuplicatesPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * List of expense IDs that needs to be dismissed as a duplicate from the target expense 
     */
    duplicate_expense_ids: Array<string>;
}

