/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Amount that the policy calculation suggests for this expense. 
 */
export interface ExpensePolicyPayloaddividualDesiredStatesAmount { 
}

