/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseFieldResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    seq?: number;
    /**
     * This specifies the name of the expense field. 
     */
    field_name?: string;
    /**
     * This specifies the name of column to which this expense field mapped to. 
     */
    column_name?: string;
    /**
     * This field specifies the type of the expense field. 
     */
    type?: string;
    /**
     * This specifies the option values of the expense field in case on SELECT or MULTI_SELECT type. 
     */
    options?: Array<string>;
    /**
     * This specifies the default value of the expense fields. 
     */
    default_value?: string | null;
    /**
     * This specifies the placeholder of the expense field. 
     */
    placeholder?: string | null;
    /**
     * List of category ids. 
     */
    category_ids?: Array<number>;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * This field indicates if the expense field is custom or not. 
     */
    is_custom?: boolean;
    /**
     * This specifies if the expense field is mandatory or not. 
     */
    is_mandatory?: boolean;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This specifies the `id` of the parent expense field and denotes that the expense field is a dependent custom field. NOTE: `type` must be `DEPENDENT_SELECT`. 
     */
    parent_field_id?: number | null;
}

