/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Configure how to show the double rows for each line item in the export file, if enabled. 
 */
export interface ExpensesExportConfigSeparateLineItemsEntry { 
    /**
     * Whether to show the double rows for each line item in the export file. 
     */
    enabled?: boolean;
    /**
     * Configure which columns to show for debit entries. 
     */
    debit_entries_only?: Array<string>;
    /**
     * Configure which columns to show for credit entries. 
     */
    credit_entries_only?: Array<string>;
}

