/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpensePermissionsResponse { 
    /**
     * Indicates whether the user has permission to delete this expense. 
     */
    can_delete: boolean;
    /**
     * Indicates whether the user has permission to edit this expense. 
     */
    can_edit: boolean;
    /**
     * Indicates whether the user has permission to verify this expense. 
     */
    can_verify: boolean;
    /**
     * Indicates whether the user has permission to remove this expense from a report. 
     */
    can_remove_from_report: boolean;
    /**
     * Indicates whether the user has permission to assign this expense to another user. 
     */
    can_assign: boolean;
    /**
     * Indicates whether the user has permission to add this expense to a report. 
     */
    can_add_to_report: boolean;
}

