/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensePolicyResponseExpenseCustomFieldsOp } from './expensePolicyResponseExpenseCustomFieldsOp';
import { ExpensePolicyResponseExpenseAmountMin } from './expensePolicyResponseExpenseAmountMin';
import { CustomField } from './customField';
import { ExpensePolicyResponseExpenseAmountMax } from './expensePolicyResponseExpenseAmountMax';
import { ExpensePolicyResponseExpenseCurrency } from './expensePolicyResponseExpenseCurrency';
import { ExpensePolicyResponseExpenseVehicleType } from './expensePolicyResponseExpenseVehicleType';
import { ContainsOperator } from './containsOperator';
import { ExpensePolicyResponseEmployeeCustomFieldsOp } from './expensePolicyResponseEmployeeCustomFieldsOp';
import { ExpensePolicyResponseExpenseLimitType } from './expensePolicyOutExpenseLimitType';
import { Location } from './location';
import { UserPartialNullable } from './userPartialNullable';


export interface ExpensePolicyResponse { 
  [key: string]: any | any;


    /**
     * This represents the id of the expense policy rule. 
     */
    id?: string;
    /**
     * This represents the description of the expense policy rule. 
     */
    description?: string | null;
    /**
     * This represents the source of the expense policy rule, i.e. from where it was created. 
     */
    source?: ExpensePolicyResponse.SourceEnum;
    /**
     * Whether the policy rule is active or not. 
     */
    is_enabled?: boolean;
    /**
     * Whether the policy rule is retired and can\'t be made active again. 
     */
    is_retired?: boolean;
    /**
     * Whether the policy rule adds an approver to the expense on violation. 
     */
    is_approver_policy?: boolean;
    /**
     * This number indicates the order of the approver expense policy rule in the defined approval sequence. For non-approver policies, this field will be null. 
     */
    approver_order?: number | null;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    expense_limit_type?: ExpensePolicyResponseExpenseLimitType | null;
    expense_currency?: ExpensePolicyResponseExpenseCurrency | null;
    expense_amount_max?: ExpensePolicyResponseExpenseAmountMax | null;
    expense_amount_min?: ExpensePolicyResponseExpenseAmountMin | null;
    /**
     * Month number of start of fiscal year. 
     */
    expense_fiscal_start_month?: number | null;
    /**
     * If an expense\'s distance exceeds this value, this policy rule will be violated for that expense. 
     */
    expense_distance_max?: number | null;
    /**
     * If an expense\'s distance falls behind this value, this policy rule will be violated for that expense. 
     */
    expense_distance_min?: number | null;
    /**
     * List of category ids considered by this policy rule. 
     */
    expense_category_ids?: Array<number> | null;
    /**
     * - If it is set to IN, this policy rule will be applicable to all the expenses that belong to any of the categories listed in the field `expense_category_ids`. - If it is set to NOT_IN, this policy rule will be applicable to all the expenses that do not belong to any of the categories listed in the field `expense_category_ids`. 
     */
    expense_category_ids_op?: ContainsOperator | null;
    /**
     * List of project ids considered by this policy rule. 
     */
    expense_project_ids?: Array<number> | null;
    /**
     * - If it is set to IN, this policy rule will be applicable to all the expenses that belong to any of the projects listed in the field `expense_project_ids`. - If it is set to NOT_IN, this policy rule will be applicable to all the expenses that do not belong to any of the projects listed in the field `expense_project_ids`. 
     */
    expense_project_ids_op?: ContainsOperator | null;
    /**
     * List of cost centers ids considered by this policy rule. 
     */
    expense_cost_center_ids?: Array<number> | null;
    /**
     * - If it is set to IN, this policy rule will be applicable to all the expenses that belong to any of the cost centers listed in the field `expense_cost_center_ids`. - If it is set to NOT_IN, this policy rule will be applicable to all the expenses that do not belong to any of the cost centers listed in the field `expense_cost_center_ids`. 
     */
    expense_cost_center_ids_op?: ContainsOperator | null;
    /**
     * Allowed percentage difference for exchange rates beyond which this policy rule will be violated. 
     */
    expense_allowed_exchange_rate_difference_percentage?: number | null;
    /**
     * Allowed distance percentage difference beyond which this policy rule will be violated. 
     */
    expense_allowed_distance_difference_percentage?: number | null;
    /**
     * Custom fields (if any) 
     */
    expense_custom_fields?: Array<CustomField>;
    expense_custom_fields_op?: ExpensePolicyResponseExpenseCustomFieldsOp | null;
    /**
     * Location of expense considered by this policy rule. 
     */
    expense_locations?: Array<Location> | null;
    expense_locations_op?: ContainsOperator | null;
    /**
     * This value decides how delayed an expense creation can be. If the expense is created after this many days of spend date, this policy rule will be violated. 
     */
    expense_creation_delay_days_max?: number | null;
    /**
     * If this is set to false, then for all such expenses that doesn\'t have receipt, this policy rule will be violated. 
     */
    expense_without_receipt_allowed?: boolean;
    /**
     * If an expense\'s spend date exceeds this value, this policy rule will be violated for that expense. 
     */
    expense_spent_at_max?: string | null;
    /**
     * If an expense\'s spend date falls behind this value, this policy rule will be violated for that expense. 
     */
    expense_spent_at_min?: string | null;
    /**
     * Payment mode for expense to be considered by the policy rule. 
     */
    expense_payment_modes?: Array<ExpensePolicyResponse.ExpensePaymentModesEnum> | null;
    expense_payment_modes_op?: ContainsOperator | null;
    /**
     * If this is set to false, then for all such expenses that are not matched to corporate credit card transaction, this policy rule will be violated. 
     */
    expense_without_ccc_match_allowed?: boolean;
    /**
     * If this is set to true, then for all such expenses that are created in foreign currency, this policy rule will be applicable. 
     */
    expense_include_foreign_currency?: boolean;
    /**
     * This field is applicable only for Flight category. <br> List of travel classes considered by this policy rule. 
     */
    expense_flight_travel_class?: Array<string> | null;
    /**
     * This field is applicable only for Train category. <br> List of travel classes considered by this policy rule. 
     */
    expense_train_travel_class?: Array<string> | null;
    expense_vehicle_type?: ExpensePolicyResponseExpenseVehicleType | null;
    /**
     * If an expense\'s annual distance exceeds this value, this policy rule will be violated for that expense. 
     */
    expense_annual_distance_max?: number | null;
    /**
     * Employee level ids considered by this policy rule. 
     */
    employee_level_ids?: Array<string> | null;
    employee_level_ids_op?: ContainsOperator | null;
    /**
     * Custom fields (if any) 
     */
    employee_custom_fields?: Array<CustomField>;
    employee_custom_fields_op?: ExpensePolicyResponseEmployeeCustomFieldsOp | null;
    /**
     * Employee department ids considered by this policy rule. 
     */
    employee_department_ids?: Array<string> | null;
    employee_department_ids_op?: ContainsOperator | null;
    /**
     * Location of employees considered by this policy rule. <br> If this is set, then for all such employees whose location is in `employee_locations`, this policy rule will be applicable. 
     */
    employee_locations?: Array<Location> | null;
    employee_locations_op?: ContainsOperator | null;
    /**
     * Employee user ids considered by this policy rule. 
     */
    employee_user_ids?: Array<string> | null;
    employee_user_ids_op?: ContainsOperator | null;
    /**
     * Employee titles considered by this policy rule. 
     */
    employee_titles?: Array<string> | null;
    employee_titles_op?: ContainsOperator | null;
    /**
     * If it is set to true, then the expense(s) violating this policy rule, will be flagged. 
     */
    action_flag?: boolean;
    /**
     * If it is set to true, then a warning is shown to the employee, whenever he attempts to create an expense that violates this policy rule. 
     */
    action_show_warning?: boolean;
    /**
     * If it is set to true, then the expense(s) violating this policy rule, will be made unreportable. <br> (Expense will be created but employee will not be able to add it to report). 
     */
    action_make_unreportable?: boolean;
    /**
     * If this is set to true, then the employee\'s first approver will be removed from the report that contains expense(s) violating this policy rule. 
     */
    action_remove_employee_approver1?: boolean;
    /**
     * If this is set to true, then the employee\'s second approver will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_employee_approver2?: boolean;
    /**
     * If this is set to true, then the employee\'s third approver will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_employee_approver3?: boolean;
    /**
     * If this is set to true, then the project\'s first approver will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_project_approver1?: boolean;
    /**
     * If this is set to true, then the project\'s second approver will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_project_approver2?: boolean;
    /**
     * If this is set to true, then the employee\'s department approver will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_department_head_approver?: boolean;
    /**
     * If it is set to true, then expense\'s amount will be capped to `expense_amount_max` when the expense(s) violates this policy rule. 
     */
    action_cap_amount?: boolean;
    /**
     * List of approver user ids that will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_approver_user_ids?: Array<string> | null;
    /**
     * When annual mileage distance limit exceeds `expense_annual_distance_max` for `expense_vehicle_type`, this rate will be applied afterwards. 
     */
    action_override_distance_slab_rate?: number | null;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly creator_user_id?: string;
    creator_user?: UserPartialNullable | null;
}
export namespace ExpensePolicyResponse {
    export const SourceEnum = {
        WebappPolicyForm: 'WEBAPP_POLICY_FORM',
        WebappPolicyJson: 'WEBAPP_POLICY_JSON',
        WebappExpenseReceiptAmountLimit: 'WEBAPP_EXPENSE_RECEIPT_AMOUNT_LIMIT',
        WebappExpenseMileageSlabRate: 'WEBAPP_EXPENSE_MILEAGE_SLAB_RATE',
        WebappProjectApproval: 'WEBAPP_PROJECT_APPROVAL',
        DefaultPrimaryApproverPolicy: 'DEFAULT_PRIMARY_APPROVER_POLICY'
    } as const;
    export type SourceEnum = typeof SourceEnum[keyof typeof SourceEnum];
    export const ExpensePaymentModesEnum = {
        PersonalCashAccount: 'PERSONAL_CASH_ACCOUNT',
        PersonalCorporateCreditCardAccount: 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
        CompanyAccount: 'COMPANY_ACCOUNT'
    } as const;
    export type ExpensePaymentModesEnum = typeof ExpensePaymentModesEnum[keyof typeof ExpensePaymentModesEnum];
}


