/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartialNullable } from './userPartialNullable';


export interface ExpenseCommentsResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * comment on the report
     */
    comment: string;
    /**
     * Expense action for which comment is added.
     */
    action: ExpenseCommentsResponse.ActionEnum;
    /**
     * Data related to expense action.
     */
    action_data: object | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    expense_id: string;
    /**
     * Describes whether the comment is system-generated or User made.
     */
    creator_type: ExpenseCommentsResponse.CreatorTypeEnum;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly creator_user_id?: string | null;
    creator_user?: UserPartialNullable | null;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id: string;
}
export namespace ExpenseCommentsResponse {
    export const ActionEnum = {
        AdminApproved: 'ADMIN_APPROVED',
        Approved: 'APPROVED',
        ApproverRemoved: 'APPROVER_REMOVED',
        AutoMatched: 'AUTO_MATCHED',
        AutoMerged: 'AUTO_MERGED',
        Commented: 'COMMENTED',
        DataExtracted: 'DATA_EXTRACTED',
        EjectedFromReport: 'EJECTED_FROM_REPORT',
        ExpenseRuleApplied: 'EXPENSE_RULE_APPLIED',
        FileAttached: 'FILE_ATTACHED',
        FileDeleted: 'FILE_DELETED',
        InvalidExpenseFieldRemoved: 'INVALID_EXPENSE_FIELD_REMOVED',
        Matched: 'MATCHED',
        Paid: 'PAID',
        PartiallyApproved: 'PARTIALLY_APPROVED',
        PolicyResultApplied: 'POLICY_RESULT_APPLIED',
        Unmatched: 'UNMATCHED'
    } as const;
    export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];
    export const CreatorTypeEnum = {
        System: 'SYSTEM',
        Policy: 'POLICY',
        User: 'USER'
    } as const;
    export type CreatorTypeEnum = typeof CreatorTypeEnum[keyof typeof CreatorTypeEnum];
}


