/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseFiltersPayload { 
    /**
     * This represents the name of the filter. 
     */
    name: string;
    /**
     * This indicates if the filter should be shared with others in the org. 
     */
    is_shared?: boolean | null;
    /**
     * This represents a query string which will be used to filter the data. 
     */
    query_string: string;
    /**
     * This field can be used to setup a collection of filters. For example, if you have multiple filters for a single page, this can be used as an identifier to fetch all the filters for that page. <br> **Note: Only combination of alphabets, numbers and _(underscore) is allowed** 
     */
    sub_feature?: string | null;
}

