/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpensePolicyExpensesQueryObjectParams { 
    /**
     * Category ids query param to find the list of expenses. 
     */
    category_id?: string;
    /**
     * Project ids query param to find the list of expenses. 
     */
    project_id?: string;
    /**
     * Cost center ids query param to find the list of expenses. 
     */
    cost_center_id?: string;
    /**
     * Currency query param to find the list of expenses. 
     */
    currency?: string;
    /**
     * Mileage rate query param to find the list of expenses. 
     */
    mileage_rate_id?: string;
    /**
     * Employee id query param to find the list of expenses. 
     */
    employee_id?: string;
}

