/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensePolicyLimitType } from './expensePolicyLimitType';


/**
 * Value signifying the limit type of the expense policy. 
 */
/**
 * @type ExpensePolicyResponseExpenseLimitType
 * Value signifying the limit type of the expense policy. 
 * @export
 */
export type ExpensePolicyResponseExpenseLimitType = ExpensePolicyLimitType;

