/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OverallStats } from './overallStats';
import { StateWiseGroupedStatsInner } from './stateWiseGroupedStatsInner';


/**
 * @type ExpensesStatsOut
 * @export
 */
export type ExpensesStatsOut = Array<StateWiseGroupedStatsInner> | OverallStats;

