/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseRuleIfPayload { 
    /**
     * substring to check in merchant for applying this expense rule
     */
    merchant_contains: string;
    /**
     * List of department ids 
     */
    department_ids?: Array<string> | null;
}

