/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ExpensePolicyLimitType = {
    Individual: 'INDIVIDUAL',
    Daily: 'DAILY',
    Nightly: 'NIGHTLY',
    Weekly: 'WEEKLY',
    Monthly: 'MONTHLY',
    Quarterly: 'QUARTERLY',
    HalfYearly: 'HALF_YEARLY',
    Yearly: 'YEARLY',
    Lifetime: 'LIFETIME'
} as const;
export type ExpensePolicyLimitType = typeof ExpensePolicyLimitType[keyof typeof ExpensePolicyLimitType];

