/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensePolicyPayloaddividualDesiredStatesAmount } from './expensePolicyPayloaddividualDesiredStatesAmount';


export interface ExpenseCheckPoliciesFinalDesiredState { 
    /**
     * A true value here means, that as per policy calculation this expense should be flagged. 
     */
    flag?: boolean;
    amount?: ExpensePolicyPayloaddividualDesiredStatesAmount | null;
    /**
     * A true value here means, that as per policy calculation this expense requires receipt. 
     */
    is_receipt_mandatory?: boolean;
    /**
     * List of approver ids that the policy calculation suggests adding to report that contains this expense. 
     */
    add_approver_user_ids?: Array<string> | null;
    /**
     * A true value here means, that as per policy calculation, the employee\'s first approver should be removed from the report that contains this expense. 
     */
    remove_employee_approver1?: boolean;
    /**
     * This represent the run status of the policy. 
     */
    run_status?: ExpenseCheckPoliciesFinalDesiredState.RunStatusEnum;
    /**
     * List of human-readable action summaries that the policy calculation suggests for this expense. 
     */
    run_summary?: Array<string>;
}
export namespace ExpenseCheckPoliciesFinalDesiredState {
    export const RunStatusEnum = {
        Success: 'SUCCESS',
        Failure: 'FAILURE'
    } as const;
    export type RunStatusEnum = typeof RunStatusEnum[keyof typeof RunStatusEnum];
}


