/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseCheckPoliciesIndividualDesiredStates } from './expenseCheckPoliciesIndividualDesiredStates';
import { ExpenseCheckPoliciesFinalDesiredState } from './expenseCheckPoliciesFinalDesiredState';


export interface ExpenseCheckPoliciesResponse { 
    individual_desired_states?: Array<ExpenseCheckPoliciesIndividualDesiredStates>;
    final_desired_state?: ExpenseCheckPoliciesFinalDesiredState;
}

