/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpensesDuplicateSetsStatsPayload { 
    /**
     * This field contains the query param string similar to the query params passed in GET call. Currently we don\'t  process this field, this is added for future use cases. Currently empty string value should be passed. 
     */
    query_params?: string;
}

