/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartial } from './userPartial';


export interface ExpenseVerificationPartial { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    verifier_user_id?: string;
    verifier_user?: UserPartial;
}

