/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpensePermissionsPayload { 
    /**
     * Expense ID of the expense to check permissions for. 
     */
    id: string;
}

