/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensesExportConfigColumnsInner } from './expensesExportConfigColumnsInner';
import { ExpensesExportConfigSeparateLineItemsEntry } from './expensesExportConfigSeparateLineItemsEntry';


export interface ExpensesExportConfig { 
  [key: string]: any | any;


    /**
     * Type of the export file. 
     */
    type?: ExpensesExportConfig.TypeEnum;
    /**
     * Whether to show the header in the export file. 
     */
    is_header_visible?: boolean;
    separate_line_items_entry?: ExpensesExportConfigSeparateLineItemsEntry;
    /**
     * Configure the columns to show in the export file. 
     */
    columns?: Array<ExpensesExportConfigColumnsInner>;
}
export namespace ExpensesExportConfig {
    export const TypeEnum = {
        Xlsx: 'xlsx',
        Csv: 'csv'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


