/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleType } from './vehicleType';


/**
 * Vehicle type considered by this policy rule. 
 */
export interface ExpensePolicyResponseExpenseVehicleType { 
}

