/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * If an expense\'s amount exceeds this value, this policy rule will be violated for that expense. 
 */
export interface ExpensePolicyResponseExpenseAmountMax { 
}

