/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensePolicyLimitType } from './expensePolicyLimitType';


/**
 * Value signifying the limit type of the expense policy. <br><br> `INDIVIDUAL`: Amount limit will be checked against each expense. <br> `DAILY`: Amount limit will be checked against the total of all expenses in a day. <br> `NIGHTLY`: Amount limit will be checked against the hotel cost per night. <br> `WEEKLY`: Amount limit will be checked against the total of all expenses in a week. <br> `MONTHLY`: Amount limit will be checked against the total of all expenses in a month. <br> `QUARTERLY`: Amount limit will be checked against the total of all expenses in a financial quarter. <br> `HALF_YEARLY`: Amount limit will be checked against the total of all expenses in a financial half-year. <br> `YEARLY`: Amount limit will be checked against the total of all expenses in a financial year. <br> `LIFETIME`: Amount limit will be checked against the total amount of all expenses throughout employee duration in the organisation. <br><br> **Note: If this field is set(to any value), then the following fields are mandatory in the request body:** <br> - `expense_currency` - Either `expense_amount_max` or `expense_amount_min` <br> **Note: If this field is set to QUARTERLY, HALF_YEARLY or YEARLY, then the following additional fields are mandatory in the request body:** <br> - `expense_fiscal_start_month` 
 */
/**
 * @type ExpensePolicyPayloadExpenseLimitType
 * Value signifying the limit type of the expense policy. <br><br> `INDIVIDUAL`: Amount limit will be checked against each expense. <br> `DAILY`: Amount limit will be checked against the total of all expenses in a day. <br> `NIGHTLY`: Amount limit will be checked against the hotel cost per night. <br> `WEEKLY`: Amount limit will be checked against the total of all expenses in a week. <br> `MONTHLY`: Amount limit will be checked against the total of all expenses in a month. <br> `QUARTERLY`: Amount limit will be checked against the total of all expenses in a financial quarter. <br> `HALF_YEARLY`: Amount limit will be checked against the total of all expenses in a financial half-year. <br> `YEARLY`: Amount limit will be checked against the total of all expenses in a financial year. <br> `LIFETIME`: Amount limit will be checked against the total amount of all expenses throughout employee duration in the organisation. <br><br> **Note: If this field is set(to any value), then the following fields are mandatory in the request body:** <br> - `expense_currency` - Either `expense_amount_max` or `expense_amount_min` <br> **Note: If this field is set to QUARTERLY, HALF_YEARLY or YEARLY, then the following additional fields are mandatory in the request body:** <br> - `expense_fiscal_start_month` 
 * @export
 */
export type ExpensePolicyPayloadExpenseLimitType = ExpensePolicyLimitType;

