/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldValue } from './customFieldValue';
import { ExpenseCustomFieldIsEnabled } from './expenseCustomFieldIsEnabled';


/**
 * Expense custom field 
 */
export interface ExpenseCustomField { 
    name?: string;
    value?: CustomFieldValue | null;
    /**
     * This field specifies the type of the expense field. 
     */
    type?: ExpenseCustomField.TypeEnum | null;
    is_enabled?: ExpenseCustomFieldIsEnabled | null;
}
export namespace ExpenseCustomField {
    export const TypeEnum = {
        Text: 'TEXT',
        Number: 'NUMBER',
        Select: 'SELECT',
        Boolean: 'BOOLEAN',
        MultiSelect: 'MULTI_SELECT',
        Location: 'LOCATION',
        UserList: 'USER_LIST',
        Date: 'DATE',
        DependentSelect: 'DEPENDENT_SELECT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


