/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomField } from './customField';
import { DependentExpenseFields } from './dependentExpenseFields';


export interface ExpenseRulePayloadSet { 
    /**
     * String denoting the name of the merchant to which the Expense was made. 
     */
    merchant?: string | null;
    /**
     * This field marks whether a given expense is billable or not.
     */
    is_billable?: boolean | null;
    purpose?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    category_id?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    project_id?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    cost_center_id?: number | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField> | null;
    /**
     * Dependent expense fields 
     */
    dependent_fields?: Array<DependentExpenseFields> | null;
}

