/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomField } from './customField';


export interface ExpenseSplitObject { 
    /**
     * It signifies when this expense was made. This date cannot be in future. - **Note:**   - This field is required while creating an expense.   - _Not required when updating an expense, but is non-nullable_.  
     */
    spent_at?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    category_id?: number | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount?: number | null;
    purpose?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    project_id?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    cost_center_id?: number | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField>;
}

