/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseCheckMandatoryFieldsResponse { 
    /**
     * If this is set to true, then you need to send amount field with expense object. 
     */
    missing_amount: boolean;
    /**
     * If this is set to true, then you need to send currency field with expense object. 
     */
    missing_currency: boolean;
    /**
     * If this is set to true, then you need to attach receipt to the expense. 
     */
    missing_receipt: boolean;
    /**
     * List of IDs of expense fields which are mandatory but are missing. 
     */
    missing_expense_field_ids: Array<number | null>;
}

