/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpensePolicyPayloadExpenseCustomFieldsOp } from './expensePolicyPayloadExpenseCustomFieldsOp';
import { VehicleType } from './vehicleType';
import { CustomField } from './customField';
import { ExpensePolicyPayloadEmployeeCustomFieldsOp } from './expensePolicyPayloadEmployeeCustomFieldsOp';
import { ContainsOperator } from './containsOperator';
import { ExpensePolicyPayloadExpenseLimitType } from './expensePolicyInExpenseLimitType';
import { Location } from './location';


export interface ExpensePolicyPayload { 
  [key: string]: any | any;


    /**
     * This represents the id of the expense policy rule.<br><br> _Note: When creating the policy rule, this field shouldn\'t be set._<br> _When updating, this field should be set._ 
     */
    id?: string;
    /**
     * This represents the description of the expense policy rule. 
     */
    description: string;
    /**
     * If this is set to false, then for all such expenses that doesn\'t have receipt, this policy rule will be violated. <br> **Note: If this field is set to false i.e. receipts are mandatory, only following conditions & actions are allowed =>** - expense_category_ids - expense_category_ids_op - expense_project_ids - expense_project_ids_op - expense_cost_center_ids - expense_cost_center_ids_op - expense_limit_type (only `INIDIVIDUAL` type is allowed) - expense_currency - expense_amount_max - expense_payment_modes - expense_payment_modes_op - expense_without_ccc_match_allowed - employee_department_ids - employee_department_ids_op - employee_locations - employee_user_ids - employee_user_ids_op - employee_titles - employee_titles_op - action_flag - action_show_warning - action_make_unreportable - description 
     */
    expense_without_receipt_allowed?: boolean;
    expense_limit_type?: ExpensePolicyPayloadExpenseLimitType;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>.<br> _Note: `expense_amount_max` or `expense_amount_min` is mandatory if the field `expense_currency` is present in the request body._ 
     */
    expense_currency?: string;
    /**
     * amount of money 
     */
    expense_amount_max?: number;
    /**
     * amount of money 
     */
    expense_amount_min?: number;
    /**
     * Month number of start of fiscal year.<br> _Note: This fields is required when `expense_limit_type` is QUARTERLY, HALF_YEARLY or YEARLY._ 
     */
    expense_fiscal_start_month?: number;
    /**
     * If an expense\'s distance exceeds this value, this policy rule will be violated for that expense.<br> _Note: `expense_category_ids` with mileage category is mandatory if the field `expense_distance_max` is present in the request body._ 
     */
    expense_distance_max?: number | null;
    /**
     * If an expense\'s distance falls behind this value, this policy rule will be violated for that expense.<br> _Note: `expense_category_ids` with mileage category is mandatory if the field `expense_distance_min` is present in the request body._ 
     */
    expense_distance_min?: number | null;
    /**
     * List of category ids considered by this policy rule. <br> _Note: You need to use field `expense_category_ids_op` along with this field._ 
     */
    expense_category_ids?: Array<number>;
    /**
     * - If it is set to IN, this policy rule will be applicable to all the expenses that belong to any of the categories listed in the field `expense_category_ids`. - If it is set to NOT_IN, this policy rule will be applicable to all the expenses that do not belong to any of the categories listed in the field `expense_category_ids`. 
     */
    expense_category_ids_op?: ContainsOperator | null;
    /**
     * List of project ids considered by this policy rule. <br> _Note: You need to use field `expense_project_ids_op` along with this field._ 
     */
    expense_project_ids?: Array<number>;
    /**
     * - If it is set to IN, this policy rule will be applicable to all the expenses that belong to any of the projects listed in the field `expense_project_ids`. - If it is set to NOT_IN, this policy rule will be applicable to all the expenses that do not belong to any of the projects listed in the field `expense_project_ids`. 
     */
    expense_project_ids_op?: ContainsOperator | null;
    /**
     * List of cost centers ids considered by this policy rule. <br> _Note: You need to use field `expense_cost_center_ids_op` along with this field._ 
     */
    expense_cost_center_ids?: Array<number>;
    /**
     * - If it is set to IN, this policy rule will be applicable to all the expenses that belong to any of the cost centers listed in the field `expense_cost_center_ids`. - If it is set to NOT_IN, this policy rule will be applicable to all the expenses that do not belong to any of the cost centers listed in the field `expense_cost_center_ids`. 
     */
    expense_cost_center_ids_op?: ContainsOperator | null;
    /**
     * Allowed percentage difference for exchange rates beyond which this policy rule will be violated. 
     */
    expense_allowed_exchange_rate_difference_percentage?: number;
    /**
     * Allowed distance percentage difference beyond which this policy rule will be violated.<br> _Note: `expense_category_ids` with mileage category is mandatory if the field `expense_allowed_distance_difference_percentage` is present in the request body._ 
     */
    expense_allowed_distance_difference_percentage?: number;
    /**
     * Custom fields (if any)<br> _Example -> \"No. of days\": 5_ <br> _Note: You need to use field `expense_custom_fields_op` along with this field._ 
     */
    expense_custom_fields?: Array<CustomField>;
    expense_custom_fields_op?: ExpensePolicyPayloadExpenseCustomFieldsOp;
    /**
     * Location of expense considered by this policy rule. <br> If this is set, then for all such expenses that have a location - like expenses of category Flight, Train, Bus, Hotel, etc. - this policy rule will be applicable. <br> _Note: You need to use field `expense_locations_op` along with this field._ 
     */
    expense_locations?: Array<Location>;
    /**
     * _Note: This field is mandatory if the field `expense_locations` is present in the request body._ 
     */
    expense_locations_op?: ContainsOperator | null;
    /**
     * This value decides how delayed an expense creation can be. If the expense is created after this many days of spend date, this policy rule will be violated. 
     */
    expense_creation_delay_days_max?: number;
    /**
     * If an expense\'s spend date exceeds this value, this policy rule will be violated for that expense. 
     */
    expense_spent_at_max?: string | null;
    /**
     * If an expense\'s spend date falls behind this value, this policy rule will be violated for that expense 
     */
    expense_spent_at_min?: string | null;
    /**
     * Payment mode for expense to be considered by the policy rule. <br> _Note: You need to use field `expense_payment_modes_op` along with this field._ 
     */
    expense_payment_modes?: Array<ExpensePolicyPayload.ExpensePaymentModesEnum> | null;
    /**
     * _Note: This field is mandatory if the field `expense_payment_modes` is present in the request body._ 
     */
    expense_payment_modes_op?: ContainsOperator | null;
    /**
     * If this is set to false, then for all such expenses that are not matched to corporate credit card transaction, this policy rule will be violated. 
     */
    expense_without_ccc_match_allowed?: boolean;
    /**
     * If this is set to true, then for all such expenses that are created in foreign currency, this policy rule will be applicable. 
     */
    expense_include_foreign_currency?: boolean;
    /**
     * This field is applicable only for Train category. <br> List of travel classes considered by this policy rule. _Note: `expense_category_ids` with train category is mandatory if the field `expense_train_travel_class` is present in the request body._ 
     */
    expense_flight_travel_class?: Array<string>;
    /**
     * This field is applicable only for Train category. <br> List of travel classes considered by this policy rule. _Note: `expense_category_ids` with train category is mandatory if the field `expense_train_travel_class` is present in the request body._ 
     */
    expense_train_travel_class?: Array<string>;
    /**
     * Vehicle type considered by this policy rule. <br> _Note: `expense_annual_distance_max` and `action_override_distance_slab_rate` is mandatory if the field `expense_vehicle_type` is present in the request body._ 
     */
    expense_vehicle_type?: VehicleType;
    /**
     * If an expense\'s annual distance exceeds this value, this policy rule will be violated for that expense.<br> _Note: `expense_vehicle_type` and `action_override_distance_slab_rate` is mandatory if the field `expense_annual_distance_max` is present in the request body._ 
     */
    expense_annual_distance_max?: number;
    /**
     * Employee level ids considered by this policy rule. <br> _Note: You need to use field `employee_level_ids_op` along with this field._ 
     */
    employee_level_ids?: Array<string>;
    /**
     * Note: This field is mandatory if the field `employee_level_ids` is present in the request payload/body. 
     */
    employee_level_ids_op?: ContainsOperator | null;
    /**
     * Custom fields (if any)<br> _Example -> \"Employee Age\": 30_ <br> _Note: You need to use field `employee_custom_fields_op` along with this field._ 
     */
    employee_custom_fields?: Array<CustomField>;
    employee_custom_fields_op?: ExpensePolicyPayloadEmployeeCustomFieldsOp;
    /**
     * Employee department ids considered by this policy rule. <br> _Note: You need to use field `employee_department_ids_op` along with this field._ 
     */
    employee_department_ids?: Array<string>;
    /**
     * _Note: This field is mandatory if the field `employee_department_ids` is present in the request body._ 
     */
    employee_department_ids_op?: ContainsOperator | null;
    /**
     * Location of employees considered by this policy rule. <br> If this is set, then for all such employees whose location is in `employee_locations`, this policy rule will be applicable. <br> _Note: You need to use field `employee_locations_op` along with this field._ 
     */
    employee_locations?: Array<Location>;
    /**
     * _Note: This field is mandatory if the field `employee_locations` is present in the request body._ 
     */
    employee_locations_op?: ContainsOperator | null;
    /**
     * Employee user ids considered by this policy rule. <br> _Note: You need to use field `employee_user_ids_op` along with this field._ 
     */
    employee_user_ids?: Array<string>;
    /**
     * _Note: This field is mandatory if the field `employee_user_ids` is present in the request body._ 
     */
    employee_user_ids_op?: ContainsOperator | null;
    /**
     * Employee titles considered by this policy rule. <br> _Note: You need to use field `employee_titles_op` along with this field._ 
     */
    employee_titles?: Array<string>;
    /**
     * _Note: This field is mandatory if the field `employee_titles` is present in the request body._ 
     */
    employee_titles_op?: ContainsOperator | null;
    /**
     * If it is set to true, then the expense(s) violating this policy rule, will be flagged. 
     */
    action_flag?: boolean;
    /**
     * If it is set to true, then a warning is shown to the employee, whenever he attempts to create an expense that violates this policy rule. 
     */
    action_show_warning?: boolean;
    /**
     * If it is set to true, then the expense(s) violating this policy rule, will be made unreportable. <br> (Expense will be created but employee will not be able to add it to report). 
     */
    action_make_unreportable?: boolean;
    /**
     * If this is set to true, then the employee\'s first approver will be removed from the report that contains expense(s) violating this policy rule. 
     */
    action_remove_employee_approver1?: boolean;
    /**
     * If this is set to true, then the employee\'s second approver will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_employee_approver2?: boolean;
    /**
     * If this is set to true, then the employee\'s third approver will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_employee_approver3?: boolean;
    /**
     * If this is set to true, then the project\'s first approver will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_project_approver1?: boolean;
    /**
     * If this is set to true, then the project\'s second approver will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_project_approver2?: boolean;
    /**
     * If this is set to true, then the employee\'s department approver will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_department_head_approver?: boolean;
    /**
     * If it is set to true, then expense\'s amount will be capped to `expense_amount_max` when the expense(s) violates this policy rule. 
     */
    action_cap_amount?: boolean;
    /**
     * List of approver user ids that will be added to the report that contains expense(s) violating this policy rule. 
     */
    action_add_approver_user_ids?: Array<string>;
    /**
     * When annual mileage distance limit exceeds `expense_annual_distance_max` for `expense_vehicle_type`, this rate will be applied afterwards.<br> _Note: `expense_vehicle_type` and `expense_annual_distance_max` is mandatory if the field `action_override_distance_slab_rate` is present in the request body._ 
     */
    action_override_distance_slab_rate?: number;
}
export namespace ExpensePolicyPayload {
    export const ExpensePaymentModesEnum = {
        PersonalCashAccount: 'PERSONAL_CASH_ACCOUNT',
        PersonalCorporateCreditCardAccount: 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
        CompanyAccount: 'COMPANY_ACCOUNT'
    } as const;
    export type ExpensePaymentModesEnum = typeof ExpensePaymentModesEnum[keyof typeof ExpensePaymentModesEnum];
}


