/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseFieldPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * This specifies the name of the expense field. 
     */
    field_name: string;
    /**
     * This field  specifies the type of the expense field. 
     */
    type: ExpenseFieldPayload.TypeEnum;
    /**
     * This specifies the option values of the expense field in case on SELECT or MULTI_SELECT type. Sets to empty array by default if null is passed. 
     */
    options?: Array<string> | null;
    /**
     * This specifies the default value of the expense fields. 
     */
    default_value?: string | null;
    /**
     * This specifies the placeholder of the expense field. Sets to empty string by default if null is passed. 
     */
    placeholder?: string | null;
    /**
     * List of category ids for which this expense field is applicable. If null is passed, the default value is all category ids of the org as array.
     */
    category_ids?: Array<number> | null;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled: boolean;
    /**
     * This specifies if the expense field is mandatory or not. 
     */
    is_mandatory: boolean;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This specifies the `id` of the parent expense field and denotes that the expense field is a dependent custom field. NOTE: `type` must be `DEPENDENT_SELECT`. 
     */
    parent_field_id?: number | null;
}
export namespace ExpenseFieldPayload {
    export const TypeEnum = {
        Text: 'TEXT',
        Number: 'NUMBER',
        Select: 'SELECT',
        Boolean: 'BOOLEAN',
        MultiSelect: 'MULTI_SELECT',
        Location: 'LOCATION',
        UserList: 'USER_LIST',
        Date: 'DATE',
        DependentSelect: 'DEPENDENT_SELECT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


