/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpensePolicyRuleEmbed { 
    /**
     * This represents the id of the expense policy rule that is violated for this expense.
     */
    id?: string;
    /**
     * This represents the description of the resource. 
     */
    description?: string | null;
    /**
     * A true value here means that policy calculation suggests showing a warning when the user attempts to create an expense that violates this expense policy rule. 
     */
    action_show_warning?: boolean;
}

