/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExtractedData { 
    amount?: number | null;
    vendor_name?: string | null;
    currency?: string | null;
    category?: string | null;
    date?: string | null;
}

