/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeatureConfigPayload { 
    /**
     * This specifies the target client of the feature config. 
     */
    target_client: string;
    /**
     * This specifies the feature name. 
     */
    feature: string;
    /**
     * This specifies the sub feature name. 
     */
    sub_feature?: string | null;
    /**
     * This specifies the key of the feature config. 
     */
    key: string;
    value: string | null;
    /**
     * This specifies whether the feature config is shared or not. 
     */
    is_shared: boolean;
}

