/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileResponseEmbed { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Name of the uploaded file. 
     */
    name?: string;
    /**
     * Indicates whether this file original size or encrypted or its thumbnail image. 
     */
    type?: FileResponseEmbed.TypeEnum;
    content_type?: string;
}
export namespace FileResponseEmbed {
    export const TypeEnum = {
        Integration: 'INTEGRATION',
        Receipt: 'RECEIPT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


