/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    user_id?: string | null;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * Name of the uploaded file. 
     */
    name?: string;
    /**
     * Indicates whether this file original size or encrypted or its thumbnail image. 
     */
    type?: FileResponse.TypeEnum;
    content_type?: string;
    /**
     * Link to download this file 
     */
    download_url?: string;
    /**
     * Link to upload contents of this file 
     */
    upload_url?: string | null;
}
export namespace FileResponse {
    export const TypeEnum = {
        Integration: 'INTEGRATION',
        Receipt: 'RECEIPT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


