/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileGenerateUrlsActionResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Name of the uploaded file. 
     */
    name?: string;
    content_type?: string;
    /**
     * Link to download this file 
     */
    download_url?: string;
    /**
     * Link to upload contents of this file 
     */
    upload_url?: string | null;
}

