/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlattenedCustomFieldCf1 } from './flattenedCustomFieldCf1';


/**
 * Custom fields in object format with keys as the name of the custom field and value as the value of the custom field. This is done to make it easier to query the custom fields.  Example: `[{\"name\": \"Custom Field 1\", \"value\": \"Value 1\"}]` is flattened to `{\"custom_field_1\": \"Value 1\"}`  NOTE: Key name is converted to snake case and spaces are replaced with underscores. 
 */
export interface FlattenedCustomField { 
  [key: string]: any | any;


    cf1?: FlattenedCustomFieldCf1 | null;
}

