/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location } from './location';


/**
 * @type FlattenedCustomFieldCf1
 * @export
 */
export type FlattenedCustomFieldCf1 = Array<string> | Location | boolean | number | string;

