/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Locale } from './locale';
import { Delegatee } from './delegatee';
import { CustomField } from './customField';
import { MileageSettings } from './mileageSettings';


export interface InvitationPayload { 
    /**
     * An immutable field that represents the email address of the employee. Must be compliant with <a href=\'https://www.ietf.org/rfc/rfc822.txt\'>RFC 822.</a> 
     */
    user_email: string;
    /**
     * Represents the full name of the Employee. Must be at least 3 characters.  Is required when creating a new employee 
     */
    user_full_name?: string;
    business_unit?: string | null;
    /**
     * This field refers to any string that the client programs can use to refer to an employee\'s unique id. This could be any field such as an UUID from an Active Directory server or employee id in a HRMS system. 
     */
    code?: string | null;
    /**
     * This represents the name of the resource. This should be unique in an organization 
     */
    department_name?: string | null;
    /**
     * This represents the name of the resource. This should be unique in an organization 
     */
    sub_department?: string | null;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    joined_at?: string | null;
    /**
     * This represents the name of the resource. This should be unique in an organization 
     */
    level?: string | null;
    location?: string | null;
    title?: string | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField>;
    /**
     * List of emails of employees that are approvers for this employee. Use null in case of no approver or to remove the approver. 
     */
    approver_emails?: Array<string>;
    /**
     * List of project names that this employee is allowed to access. If null, then there are no restrictions. Individual list item should be in the format of `project_name / sub_project`. If there is no sub project, then simply pass `project_name`. 
     */
    project_names?: Array<string>;
    /**
     * List of cost center names that this employee is allowed to access. [] (empty array) means access to all cost centers. 
     */
    cost_center_names?: Array<string>;
    /**
     * List of per diem rate names that this employee is allowed to access. 
     */
    per_diem_rate_names?: Array<string>;
    /**
     * List of category names that this employee is allowed to access. 
     */
    category_names?: Array<string>;
    /**
     * List of mileage rate\'s vehicle types that this employee is allowed to access. If null, then there are no restrictions 
     */
    vehicle_types?: Array<string> | null;
    /**
     * The Account number of the bank account of the Employee. 
     */
    branch_account?: Array<string> | null;
    /**
     * IFSC code of the bank account of the Employee. Must be a 11 digit alphanumeric code. 
     */
    branch_ifsc?: Array<string> | null;
    /**
     * Mobile number of the employee 
     */
    mobile?: Array<string> | null;
    locale?: Locale | null;
    mileage_settings?: MileageSettings | null;
    /**
     * This key is in the process of being deprecated. It is recommended to use `delegatees` key instead. 
     * @deprecated
     */
    delegatee_emails?: Array<string>;
    /**
     * List of delegatees for this employee. 
     */
    delegatees?: Array<Delegatee>;
}

