/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LevelResponseEmbed { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * Level name of the employees 
     */
    name: string;
    /**
     * Band in which this level belongs to, you can group multiple levels into a single band. 
     */
    band: string | null;
}

