/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LevelPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Level name of the employees 
     */
    name: string;
    /**
     * Band in which this level belongs to, you can group multiple levels into a single band. 
     */
    band?: string | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * Description of the level 
     */
    description?: string | null;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled: boolean;
}

