/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LevelResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at: string;
    /**
     * Level name of the employees 
     */
    name: string;
    /**
     * Band in which this level belongs to, you can group multiple levels into a single band. 
     */
    band: string | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code: string | null;
    /**
     * Description of the level 
     */
    description: string | null;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled: boolean;
}

