/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LocationsInner { 
    city?: string | null;
    state?: string | null;
    display?: string | null;
    country?: string | null;
    formatted_address?: string | null;
    latitude?: number | null;
    longitude?: number | null;
}

