/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Location and timezone settings of the employee. 
 */
export interface Locale { 
    /**
     * Represents the abbreviation of the employee\'s locale. 
     */
    abbreviation?: string;
    /**
     * Represents the offset of the employee\'s timezone from UTC. 
     */
    offset?: string;
    /**
     * Represents the timezone of the employee. 
     */
    timezone?: string;
}

