/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarkPaidBulkPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * This field indicates when should user receive notification regarding reimbursement 
     */
    paid_notify_at?: string;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
}

