/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MatchingCardsResponseMatchingCardsInner } from './matchingCardsResponseMatchingCardsInner';


export interface MatchingCardsResponse { 
    /**
     * Card number from statement 
     */
    statement_card_number?: string;
    matching_cards?: Array<MatchingCardsResponseMatchingCardsInner>;
}

