/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MatchedCorporateCardTransactionPartial { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    corporate_card_id: string;
    /**
     * Specifies the masked number of the card. Add only masked card-numbers, last four digits of the card. 
     */
    corporate_card_number: string;
    /**
     * Unique nickname assigned to the card 
     */
    corporate_card_nickname?: string | null;
    /**
     * String denoting the card holder\'s name 
     */
    corporate_card_cardholder_name?: string | null;
    /**
     * Last four digits of capitalone virtual card. 
     */
    capitalone_virtual_card_last_four?: string | null;
    /**
     * Specifies the masked number of the card. Add only masked card-numbers, last four digits of the card. 
     */
    masked_corporate_card_number?: string;
    /**
     * Specifies the name of bank who issued the card. 
     */
    bank_name?: string;
    /**
     * String denoting the card holder\'s full name 
     */
    corporate_card_user_full_name?: string | null;
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency?: string;
    /**
     * Signifies spent date of a card transaction. This date cannot be in future. 
     */
    spent_at?: any;
    /**
     * Signifies post date of a card transaction. This date cannot be in future. 
     */
    posted_at?: string | null;
    /**
     * Signifies status of a card transaction. 
     */
    status?: MatchedCorporateCardTransactionPartial.StatusEnum | null;
    /**
     * Holds the description of the card transaction 
     */
    description?: string | null;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency?: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount?: number | null;
    /**
     * String denoting the name of the vendor to which the card transaction was made. Note: This is not same as the merchant added in Fyle but just a string 
     */
    merchant?: string | null;
    /**
     * String denoting the category of the card transaction Note: This is not same as the category added in Fyle but just a string 
     */
    category?: string | null;
    /**
     * String denoting the email of the user who matched the card transaction to an expense. 
     */
    matched_by?: string | null;
}
export namespace MatchedCorporateCardTransactionPartial {
    export const StatusEnum = {
        Pending: 'PENDING',
        Posted: 'POSTED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


