/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MatchedExpenseResponseEmbed { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency: string;
    /**
     * amount of money 
     */
    amount: number;
    /**
     * signifies when this expense was made. This date cannot be in future. 
     */
    spent_at: string | null;
    /**
     * String denoting the name of the merchant to which the Expense was made. 
     */
    merchant: string | null;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount: number | null;
    purpose: string | null;
    /**
     * The state of the Expense.
     */
    state: MatchedExpenseResponseEmbed.StateEnum;
    /**
     * This is user visible identifier for an expense. This field can be used as reference in UI. 
     */
    readonly seq_num: string;
    /**
     * Number of files attached to the expense. 
     */
    no_of_files: number;
    /**
     * Category of the expense. 
     */
    category_display_name: string;
}
export namespace MatchedExpenseResponseEmbed {
    export const StateEnum = {
        Complete: 'COMPLETE',
        Draft: 'DRAFT',
        Paid: 'PAID',
        PaymentProcessing: 'PAYMENT_PROCESSING',
        ApproverPending: 'APPROVER_PENDING',
        PaymentPending: 'PAYMENT_PENDING',
        Approved: 'APPROVED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


