/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartialNullable } from './userPartialNullable';


export interface MatchingCardsResponseMatchingCardsInner { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Specifies the masked number of the card. Add only masked card-numbers, last four digits of the card. 
     */
    card_number?: string;
    /**
     * If the card is enrolled with real time feed from visa 
     */
    is_visa_enrolled?: boolean;
    /**
     * If the card is enrolled with realtime feed from Mastercard 
     */
    is_mastercard_enrolled?: boolean;
    /**
     * Unique nickname assigned to the card 
     */
    nickname?: string | null;
    user?: UserPartialNullable | null;
}

