/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Mileage settings of the employee. 
 */
export interface MileageSettings { 
    mileage_rate_labels?: Array<string> | null;
    annual_mileage_of_user_before_joining_fyle?: Array<object> | null;
}

