/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MileageRateResponseSlabRatesInner } from './mileageRateResponseSlabRatesInner';


export interface MileageRateResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    unit?: MileageRateResponse.UnitEnum;
    vehicle_type?: string;
    /**
     * Amount (in Home currency) per unit.
     */
    rate?: number | null;
    slab_rates?: Array<MileageRateResponseSlabRatesInner>;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
}
export namespace MileageRateResponse {
    export const UnitEnum = {
        Km: 'KM',
        Miles: 'MILES'
    } as const;
    export type UnitEnum = typeof UnitEnum[keyof typeof UnitEnum];
}


