/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MileageRatePayloadSlabRatesInner } from './mileageRatePayloadSlabRatesInner';


export interface MileageRatePayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    unit: MileageRatePayload.UnitEnum;
    vehicle_type: string;
    /**
     * Amount (in Home currency) per unit.
     */
    rate: number | null;
    slab_rates?: Array<MileageRatePayloadSlabRatesInner>;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled: boolean;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
}
export namespace MileageRatePayload {
    export const UnitEnum = {
        Km: 'KM',
        Miles: 'MILES'
    } as const;
    export type UnitEnum = typeof UnitEnum[keyof typeof UnitEnum];
}


