/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This object contains all the fields which are mandatory bu tare missing in the expense. 
 */
export interface MissingMandatoryFields { 
    /**
     * List of IDs of expense fields which are mandatory but are missing. 
     */
    expense_field_ids?: Array<number | null>;
    /**
     * This field shows whether the amount field is present in the expense or not 
     */
    amount?: boolean;
    /**
     * This field shows whether the currency field is present in the expense or not 
     */
    currency?: boolean;
}

