/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrgBankDetailsResponse { 
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * This field specifies the bank account number of the organisation.
     */
    bank_account_number?: string | null;
    /**
     * This field specifies the branch IFSC code of the bank.
     */
    bank_branch_ifsc?: string | null;
    /**
     * This field contains the unique identifier of the dwolla account connected to the organisation.
     */
    dwolla_customers_metadata_id?: string | null;
}

