/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrgResponse { 
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly id: string;
    /**
     * Represents the name of the org.
     */
    name: string;
    /**
     * This field specifies the domain with which the organisation is registered.
     */
    domain: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at: string;
    /**
     * A boolean flag indicating whether the organisation is the current organisation the user is logged into.
     */
    is_current?: boolean;
    /**
     * A boolean flag indicating whether the organisation is the primary organisation of the user.
     */
    is_primary?: boolean;
}

