/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Overall stats without state grouping (response for older mobile app versions).
 */
export interface OverallStats2 { 
    /**
     * Total number of matching reports.
     */
    count: number;
    /**
     * Total sum of amounts for all matching reports.
     */
    total_amount: number;
    /**
     * Sum of reimbursable amounts for reports in processing state.
     */
    processing_amount: number | null;
    /**
     * Count of reports in processing state.
     */
    processing_count: number | null;
    /**
     * Sum of reimbursable amounts for reports in processing state with ACH failures.
     */
    failed_amount: number | null;
    /**
     * Count of reports in processing state with ACH failures.
     */
    failed_count: number | null;
}

