/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Overall stats without state grouping
 */
export interface OverallStats { 
    /**
     * Total number of matching expenses
     */
    count: number;
    /**
     * Sum of amounts for all matching expenses
     */
    total_amount: number;
}

