/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PerDiemRateResponseEmbed { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * This represents the name of the resource. This should be unique in an organization 
     */
    name?: string;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
}

