/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PolicyChecksViolationsInner } from './policyChecksViolationsInner';


/**
 * Policy checks details. NOTE: The data of this field is not realtime. It will get updated later even if rest of fields are already up-to-date. 
 */
export interface PolicyChecks { 
    /**
     * A true value here means, that as per policy calculation this expense amount is capped based on the policy calculation. 
     */
    is_amount_limit_applied?: boolean;
    /**
     * A true value here means, approvers are added to the expense based on the policy calculation. 
     */
    are_approvers_added?: boolean;
    /**
     * A true value here means, that as per policy calculation this expense is flagged. 
     */
    is_flagged_ever?: boolean;
    /**
     * List of policy violations on this expense. 
     */
    violations?: Array<PolicyChecksViolationsInner> | null;
}

