/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PolicyChecksViolationsInner { 
    /**
     * Description of the policy rule. 
     */
    policy_rule_description?: string;
    /**
     * ID of the policy rule. 
     */
    policy_rule_id?: string;
}

