/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PreviewResponseTransactionsInner { 
    /**
     * Specifies the description of the transaction on the statement. 
     */
    description: string | null;
    /**
     * Specifies the bank name of the statement 
     */
    bank_name: string;
    /**
     * Specifies the merchant of the statement 
     */
    merchant: string;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    transaction_date: string | null;
    /**
     * Specifies the amount on the statement. 
     */
    amount: string;
    /**
     * Specifies the card number on the statement. 
     */
    card_number: string;
    /**
     * Specifies the unique code / transaction id on the statement. 
     */
    unique_id: string;
    /**
     * Specifies the foreign amount on the statement. 
     */
    foreign_amount: string | null;
    /**
     * Specifies the foreign currency on the statement. 
     */
    foreign_currency: string | null;
    /**
     * Specifies the transaction id / unique id on the statement. 
     */
    transaction_id: string | null;
    /**
     * Specifies the transaction type of the transactions on the statement (credit / debit). 
     */
    transaction_type?: string;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    post_date: string | null;
}

