/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PreviewFromStatementPayloadStatementMapping { 
    /**
     * Specifies the mapping of description column on the statement 
     */
    description_column: string | null;
    /**
     * Specifies the mapping of transaction date on the statement. 
     */
    transaction_date_column: string;
    /**
     * Specifies the mapping of transaction id / unique id on the statement. 
     */
    transaction_id_column: string | null;
    /**
     * Specifies the mapping of amount on the statement. 
     */
    amount_column: string;
    /**
     * Specifies the mapping of card number on the statement. 
     */
    card_number_column: string;
    /**
     * Specifies the mapping of merchant on the statement. 
     */
    merchant_column: string;
    /**
     * Specifies the mapping of foreign amount on the statement. 
     */
    foreign_amount_column: string | null;
    /**
     * Specifies the mapping of foreign currency on the statement. 
     */
    foreign_currency_column: string | null;
    /**
     * Specifies the header name of the post date column in the statement. 
     */
    post_date_column: string | null;
    /**
     * Specifies the bank name of the statement 
     */
    bank_name: string;
    /**
     * Specifies the representation of the the amount in the statement, if true then the amount represented by | positive sign are debits, and if false then the amount represented by negative sign are debits. 
     */
    is_debit_positive: boolean;
    /**
     * Specifies the mapping name. 
     */
    name: string | null;
    /**
     * Specifies the credit card network used by the card 
     */
    card_network: string | null;
}

