/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PreviewResponseTransactionsInner } from './previewResponseTransactionsInner';


export interface PreviewResponse { 
    /**
     * Number of debit transactions in the statement uploaded by the user. 
     */
    no_of_debit: number | null;
    /**
     * Number of credit transactions in the statement uploaded by the user. 
     */
    no_of_credit: number | null;
    /**
     * Number of transactions in the statement uploaded by the user. 
     */
    no_of_transactions: number;
    transactions: Array<PreviewResponseTransactionsInner>;
}

