/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProcessSummaryResponse { 
  [key: string]: any | any;


    /**
     * This field indicates the final reimbursable amount. 
     */
    selected_reimbursable_amount?: number;
    /**
     * This field indicates the count of selected reports. 
     */
    selected_count?: number;
    /**
     * This field indicates the count of unverified reports. 
     */
    unverified_count?: number;
    /**
     * This field indicates the total amount of unverified reports. 
     */
    unverified_amount?: number;
    /**
     * This field indicates the count of reports with missing users bank account details. 
     */
    missing_bank_details_count?: number;
    /**
     * This field indicates the total amount of reports with missing users bank account details. 
     */
    missing_bank_details_amount?: number;
    /**
     * This field indicates the count of employees with missing users bank account details. 
     */
    missing_bank_details_employee_count?: number;
    /**
     * This field contains list of employee_ids whose bank accounts are missing. 
     */
    missing_bank_details_employee_ids?: Array<string>;
    /**
     * This field indicates the total amount of reports that are in payment_processing and ach_initiated state. 
     */
    payment_initiated_amount?: number;
    /**
     * This field indicates the count of reports that are in payment_processing and ach_initiated state. 
     */
    payment_initiated_count?: number;
    /**
     * This field indicates the Final amount to be reimbursement.  
     */
    reimbursable_amount?: number;
    /**
     * This field contains list of reimbursable report_ids.  
     */
    reimbursable_report_ids?: Array<string>;
    /**
     * This field contains list of report_ids that can directly be closed(with reimbursable amount as 0).  
     */
    closable_report_ids?: Array<string>;
}

