/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectPayloadOnlyId } from './projectPayloadOnlyId';


export interface ProjectDeleteSummaryResponseData { 
    /**
     * Count of projects that could be deleted from input projects.
     */
    delete_count?: number;
    /**
     * Projects that could be deleted.
     */
    projects?: Array<ProjectPayloadOnlyId>;
}

