/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * Represents the name of the project.
     */
    name: string;
    /**
     * Represents the name of the sub_project.
     */
    sub_project?: string | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This represents the description of the resource. 
     */
    description?: string | null;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    /**
     * - List of IDs of users who can access this object. - `null` value indicates that all users in the org can access this object. - `[]` value indicates that no users in the org can access this object. - **Note:**   - **_When the `restrict employee to their own projects` feature is disabled, only `null` value is accepted._**   - _If the `restrict employee to their own projects` feature is **disabled**, then the default value while creating project  is `null`._   - _If the `restrict employee to their own projects` feature is **enabled**, then the default value while creating project is `[]`._ 
     */
    restricted_spender_user_ids?: Array<string> | null;
    /**
     * - List of IDs of users who are approvers of the project. - Either `approver_user_ids` or `approver_emails` can be used but not both. - The default value for approver_user_ids is `[]` and it is applicable only when creating the project. 
     */
    approver_user_ids?: Array<string | null>;
    /**
     * - List of emails of employees that are approvers for the project. - Either `approver_user_ids` or `approver_emails` can be used but not both. - The default value for approver_emails is `[]` and it is applicable only when creating the project. 
     */
    approver_emails?: Array<string | null>;
    /**
     * - List of IDs of categories which can be used with the project. - `null` value indicates that all categories in the org are applicable for the project. - `[]` value indicates that no category in the org is applicable for the project. - The default value of `category_ids` is `null` 
     */
    category_ids?: Array<number> | null;
}

