/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectPartial { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: number;
    /**
     * Represents the name of the project.
     */
    name?: string;
    /**
     * Represents the name of the sub_project.
     */
    sub_project?: string | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This is a combination of name and sub_project separated by a / and spaces. In case if no sub_project is present it is same as name of the project. 
     */
    display_name?: string;
}

