/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeResponseEmbed } from './employeeResponseEmbed';


export interface ReimbursementResponse { 
    /**
     * This id provided by Fyle to uniquely identify a reimbursement. This id is always prefixed with `reim`. 
     */
    readonly id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * A unique, organization wide identifier for a particular reimbursement.<br> This id is always prefixed with `P/`. 
     */
    reimbursement_number?: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly creator_user_id?: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly user_id?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency?: string;
    /**
     * amount of money 
     */
    amount?: number;
    is_paid?: boolean;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    paid_at?: string | null;
    /**
     * Mode of creation of this reimbursement. 
     */
    mode?: ReimbursementResponse.ModeEnum;
    /**
     * Details about purpose of this reimbursement. 
     */
    purpose?: string;
    /**
     * Determines whether this reimbursement has been exported to external accounting system or not. 
     */
    is_exported?: boolean | null;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
    /**
     * This id provided by Fyle to uniquely identify an employee within an organization. This id is always prefixed with `ou`. 
     */
    employee_id?: string;
    employee?: EmployeeResponseEmbed;
}
export namespace ReimbursementResponse {
    export const ModeEnum = {
        Ach: 'ACH',
        Offline: 'OFFLINE'
    } as const;
    export type ModeEnum = typeof ModeEnum[keyof typeof ModeEnum];
}


