/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReimbursementInMinimal { 
    /**
     * This id provided by Fyle to uniquely identify a reimbursement. This id is always prefixed with `reim`. 
     */
    id?: string;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
}

