/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AchTransfer } from './achTransfer';


export interface ReimbursementResponseMinimal { 
    /**
     * This id provided by Fyle to uniquely identify a reimbursement. This id is always prefixed with `reim`. 
     */
    id?: string;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    currency?: string;
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * Mode of creation of this reimbursement. 
     */
    mode?: ReimbursementResponseMinimal.ModeEnum;
    ach_transfer?: AchTransfer;
}
export namespace ReimbursementResponseMinimal {
    export const ModeEnum = {
        Ach: 'ACH',
        Offline: 'OFFLINE'
    } as const;
    export type ModeEnum = typeof ModeEnum[keyof typeof ModeEnum];
}


