/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReinvitationPayload { 
    /**
     * This id provided by Fyle to uniquely identify an employee within an organization. This id is always prefixed with `ou`. 
     */
    id: string;
}

