/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReminderScheduleConfigWhen } from './reminderScheduleConfigWhen';


/**
 * description of weekly/monthly schedule for sending scheduled reminder
 */
export interface ReminderScheduleConfig { 
    type?: ReminderScheduleConfig.TypeEnum;
    when?: ReminderScheduleConfigWhen;
}
export namespace ReminderScheduleConfig {
    export const TypeEnum = {
        Cron: 'cron'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


