/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReminderScheduleConfig } from './reminderScheduleConfig';
import { ReminderType } from './reminderType';


export interface ReminderResponse { 
    /**
     * This id provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    type?: ReminderType;
    /**
     * The custom message which the admin wants to send alongside the reminder 
     */
    message?: string;
    schedule_config?: ReminderScheduleConfig | null;
    /**
     * Signifies the time when this reminder was sent. In case of scheduled reminders, signifies when the last reminder was sent. Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    last_reminded_at?: string | null;
    /**
     * Only valid for scheduled reminders. Signifies the time when the next reminder will be sent according to the schedule_config. Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    next_reminder_at?: string | null;
    /**
     * Determines whether this reminder will be added as an event in the google calendar of receiver. 
     */
    add_to_calendar?: boolean;
    /**
     * List of IDs of users to whom this reminder will be sent. 
     */
    receiver_user_ids?: Array<string> | null;
}
export namespace ReminderResponse {
}


