/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReminderScheduleConfigWhen { 
    /**
     * day of month (1-31)
     */
    day?: number;
    /**
     * name of weekday
     */
    day_of_week?: ReminderScheduleConfigWhen.DayOfWeekEnum;
    /**
     * hour of the day in 24-hr format (0-23)
     */
    hour?: number;
    /**
     * minute of the hour
     */
    minute?: number;
}
export namespace ReminderScheduleConfigWhen {
    export const DayOfWeekEnum = {
        Mon: 'mon',
        Tue: 'tue',
        Wed: 'wed',
        Thu: 'thu',
        Fri: 'fri',
        Sat: 'sat',
        Sun: 'sun'
    } as const;
    export type DayOfWeekEnum = typeof DayOfWeekEnum[keyof typeof DayOfWeekEnum];
}


