/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReminderScheduleConfig } from './reminderScheduleConfig';
import { ReminderType } from './reminderType';


export interface ReminderPayload { 
    /**
     * This id provided by Fyle to identify an object. 
     */
    id?: string;
    type?: ReminderType;
    /**
     * The custom message which the admin wants send alongside the reminder 
     */
    message?: string;
    schedule_config?: ReminderScheduleConfig | null;
    /**
     * Determines whether this reminder will be added as an event in the google calendar of receiver. 
     */
    add_to_calendar?: boolean;
    /**
     * List of IDs of users to whom this reminder will be sent. 
     */
    receiver_user_ids?: Array<string> | null;
}
export namespace ReminderPayload {
}


