/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the type of reminder.
 */
export const ReminderType = {
    FyleExpenses: 'FYLE_EXPENSES',
    ReportExpenses: 'REPORT_EXPENSES',
    ApproveReports: 'APPROVE_REPORTS',
    VerifyEmployees: 'VERIFY_EMPLOYEES',
    MatchCorporateCardTransactions: 'MATCH_CORPORATE_CARD_TRANSACTIONS',
    ApproveAdvanceRequests: 'APPROVE_ADVANCE_REQUESTS',
    ResubmitAdvanceRequests: 'RESUBMIT_ADVANCE_REQUESTS',
    MatchAdvances: 'MATCH_ADVANCES',
    VerifyEmployees2: 'VERIFY_EMPLOYEES',
    AddCorporateCards: 'ADD_CORPORATE_CARDS',
    ConnectVisaRtf: 'CONNECT_VISA_RTF',
    VerifyVisaCard: 'VERIFY_VISA_CARD',
    ConnectMastercardRtf: 'CONNECT_MASTERCARD_RTF',
    ProcessReports: 'PROCESS_REPORTS',
    VerifyReports: 'VERIFY_REPORTS'
} as const;
export type ReminderType = typeof ReminderType[keyof typeof ReminderType];

