/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReminderDeletePayload { 
    /**
     * ID of the reminder that needs to be deleted. 
     */
    id: string;
}

