/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An unique ID, generated by Fyle, for identifying the Reimbursement. 
 */
export interface ReportResponseEmbedReimbursementId { 
}

