/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartialNullable } from './userPartialNullable';


export interface ReportCommentsResponseEmbed { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * comment on the report
     */
    comment: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    creator_user_id: string;
    creator_user: UserPartialNullable | null;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
}

