/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportsExportConfigColumnsInner } from './reportsExportConfigColumnsInner';
import { ReportsExportConfigSeparateLineItemsEntry } from './reportsExportConfigSeparateLineItemsEntry';


export interface ReportsExportConfig { 
  [key: string]: any | any;


    /**
     * Type of the export file. 
     */
    type?: ReportsExportConfig.TypeEnum;
    /**
     * Whether to include receipts in the export file or not. Only required for PDF exports. 
     */
    include_receipts?: boolean;
    /**
     * Whether to show the header in the export file. Only required for CSV and XLSX exports. 
     */
    is_header_visible?: boolean;
    separate_line_items_entry?: ReportsExportConfigSeparateLineItemsEntry;
    /**
     * Configure the columns to show in the export file. Only required for CSV and XLSX exports. 
     */
    columns?: Array<ReportsExportConfigColumnsInner>;
}
export namespace ReportsExportConfig {
    export const TypeEnum = {
        Xlsx: 'xlsx',
        Csv: 'csv',
        Pdf: 'pdf'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


