/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportsExportConfig } from './reportsExportConfig';
import { ExpensesExportsResponseFileId } from './expensesExportsResponseFileId';


export interface ReportsExportsResponse { 
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at?: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id?: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly user_id?: string;
    /**
     * This field contains the query param string similar to the query params passed in GET call for displaying data in the list view. 
     */
    query_params?: string;
    notify_emails?: Array<string>;
    config?: ReportsExportConfig;
    file_id?: ExpensesExportsResponseFileId | null;
    /**
     * Status of the export. 
     */
    state?: ReportsExportsResponse.StateEnum;
}
export namespace ReportsExportsResponse {
    export const StateEnum = {
        Pending: 'PENDING',
        Processing: 'PROCESSING',
        Success: 'SUCCESS',
        Error: 'ERROR'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


