/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportResponseSubscriptionsAdminData } from './reportResponseSubscriptionsAdminData';


export interface ReportResponseSubscriptionsAdmin { 
    resource: string;
    action: ReportResponseSubscriptionsAdmin.ActionEnum;
    data: ReportResponseSubscriptionsAdminData;
    reason: string;
}
export namespace ReportResponseSubscriptionsAdmin {
    export const ActionEnum = {
        AccountingExportPayloaditiated: 'ACCOUNTING_EXPORT_INITIATED',
        Approved: 'APPROVED',
        AdminApproved: 'ADMIN_APPROVED',
        StateChangePaymentProcessing: 'STATE_CHANGE_PAYMENT_PROCESSING',
        MarkPaid: 'MARK_PAID'
    } as const;
    export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];
}


