/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportCommentsPayload { 
    /**
     * id of the report, on which need to add comment 
     */
    id: string;
    /**
     * comment on the report 
     */
    comment: string;
}

