/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OverallStats2 } from './overallStats2';
import { StateWiseGroupedStatsInner2 } from './stateWiseGroupedStatsInner2';


/**
 * @type ReportsStatsOut
 * @export
 */
export type ReportsStatsOut = Array<StateWiseGroupedStatsInner2> | OverallStats2;

