/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportPermissionsResponse { 
    can_edit: boolean;
    can_admin_or_approver_edit: boolean;
    can_delete: boolean;
    can_submit: boolean;
    can_export: boolean;
    can_resubmit: boolean;
    can_approve: boolean;
    can_admin_approve: boolean;
    can_send_back: boolean;
    can_verify: boolean;
    can_move_to_payment_pending: boolean;
    can_add_approver: boolean;
    can_remove_approver: boolean;
}

