/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportsStatsPayload { 
    /**
     * Query param string similar to reports GET call. Use group_by_state=eq.true to get state-wise grouping of stats. 
     */
    query_params?: string;
}

