/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportActionWithExpensesIdsToEject { 
    /**
     * id of report, from which the expenses are to be ejected 
     */
    id: string;
    expense_ids: Array<string>;
}

