/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportActionRemoveApproverPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * An immutable field that represents the email address of the employee. Must be compliant with <a href=\'https://www.ietf.org/rfc/rfc822.txt\'>RFC 822.</a> 
     */
    approver_email: string;
}

