/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPartial } from './userPartial';


export interface ReportApprovalPartial { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    approver_user_id?: string;
    approver_user?: UserPartial;
    /**
     * State of this report_approval 
     */
    state?: ReportApprovalPartial.StateEnum;
    /**
     * This number inidicates the order of the approver in the approval sequence for the report. The approver with the lowest approver_order is the first approver in the sequence. 
     */
    approver_order?: number;
}
export namespace ReportApprovalPartial {
    export const StateEnum = {
        ApprovalPending: 'APPROVAL_PENDING',
        ApprovalDisabled: 'APPROVAL_DISABLED',
        ApprovalDone: 'APPROVAL_DONE'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


