/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportResponseEmbedId } from './reportResponseEmbedId';
import { ReportApprovalPartial } from './reportApprovalPartial';
import { ReportResponseEmbedReimbursementId } from './reportResponseEmbedReimbursementId';
import { ReportResponseEmbedLastSubmittedAt } from './reportResponseEmbedLastSubmittedAt';
import { ReportResponseEmbedLastApprovedAt } from './reportResponseEmbedLastApprovedAt';
import { ReportResponseEmbedLastVerifiedAt } from './reportResponseEmbedLastVerifiedAt';
import { ReportResponseEmbedLastPaidAt } from './reportResponseEmbedLastPaidAt';
import { ReportResponseEmbedAmount } from './reportResponseEmbedAmount';


export interface ReportResponseEmbed { 
    id: ReportResponseEmbedId | null;
    last_approved_at: ReportResponseEmbedLastApprovedAt | null;
    last_submitted_at: ReportResponseEmbedLastSubmittedAt | null;
    /**
     * A unique human readable identifier for the report 
     */
    seq_num: string | null;
    /**
     * purpose for creating the report
     */
    title: string | null;
    state: ReportResponseEmbed.StateEnum | null;
    amount?: ReportResponseEmbedAmount | null;
    last_paid_at: ReportResponseEmbedLastPaidAt | null;
    last_verified_at?: ReportResponseEmbedLastVerifiedAt | null;
    reimbursement_id: ReportResponseEmbedReimbursementId | null;
    /**
     * A unique, organization wide identifier for a particular reimbursement.<br> This id is always prefixed with `P/`. 
     */
    reimbursement_seq_num: string | null;
    /**
     * List of report_approval objects 
     */
    approvals?: Array<ReportApprovalPartial> | null;
}
export namespace ReportResponseEmbed {
    export const StateEnum = {
        Draft: 'DRAFT',
        ApproverPending: 'APPROVER_PENDING',
        ApproverInquiry: 'APPROVER_INQUIRY',
        PaymentProcessing: 'PAYMENT_PROCESSING',
        Approved: 'APPROVED',
        PaymentPending: 'PAYMENT_PENDING',
        Paid: 'PAID'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


