/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Roles are assigned by Admin. 
 */
export const Role = {
    Fyler: 'FYLER',
    Approver: 'APPROVER',
    Accountant: 'ACCOUNTANT',
    TravelAdmin: 'TRAVEL_ADMIN',
    Verifier: 'VERIFIER',
    PaymentProcessor: 'PAYMENT_PROCESSOR',
    Finance: 'FINANCE',
    Admin: 'ADMIN',
    TravelAgent: 'TRAVEL_AGENT',
    Owner: 'OWNER',
    Auditor: 'AUDITOR',
    Hod: 'HOD',
    Hop: 'HOP'
} as const;
export type Role = typeof Role[keyof typeof Role];

