/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RtfMissingTransactionFromStatementResponseMissingRtfTransactionsInner } from './rtfMissingTransactionFromStatementResponseMissingRtfTransactionsInner';


export interface RtfMissingTransactionFromStatementResponse { 
    /**
     * Error message if any error occurred while processing the statement. 
     */
    error?: string | null;
    missing_rtf_transactions?: Array<RtfMissingTransactionFromStatementResponseMissingRtfTransactionsInner>;
    /**
     * RTF Confidence percentage - `rtf_count` to the `total_count`, indicates what % of statement transactions are already existing in Fyle via RTF. 
     */
    rtf_confidence?: string;
    /**
     * Number of transactions in the statement that are already existing in Fyle via RTF. 
     */
    rtf_count?: number;
    /**
     * Total number of transactions in the statement. 
     */
    total_count?: number;
    /**
     * Status of the statement reconciliation. 
     */
    status?: RtfMissingTransactionFromStatementResponse.StatusEnum;
}
export namespace RtfMissingTransactionFromStatementResponse {
    export const StatusEnum = {
        Initialized: 'INITIALIZED',
        Processing: 'PROCESSING',
        Success: 'SUCCESS',
        Error: 'ERROR'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


