/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PreviewFromStatementPayloadStatementMapping } from './previewFromStatementPayloadStatementMapping';
import { CardMappingInInner } from './cardMappingInInner';


export interface RtfMissingTransactionFromStatementPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    statement_mapping: PreviewFromStatementPayloadStatementMapping;
    /**
     * This specifies list of statement line items to be ignored in the statement. 
     */
    ignored_line_item_ids: Array<string>;
    /**
     * Specifies the reconciliation method to be used for the statement. 
     */
    reconciliation_method: RtfMissingTransactionFromStatementPayload.ReconciliationMethodEnum;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    start_date?: string | null;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    end_date?: string | null;
    card_mapping?: Array<CardMappingInInner>;
}
export namespace RtfMissingTransactionFromStatementPayload {
    export const ReconciliationMethodEnum = {
        PostDate: 'POST_DATE',
        TransactionDate: 'TRANSACTION_DATE'
    } as const;
    export type ReconciliationMethodEnum = typeof ReconciliationMethodEnum[keyof typeof ReconciliationMethodEnum];
}


