/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RtfStatsResponse { 
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    last_uploaded_at?: string | null;
    /**
     * RTF Confidence percentage indicates what % of the transactions in last uploaded statement are already existing in Fyle via RTF. 
     */
    rtf_confidence?: string;
}

