/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScheduleConfigWhenOneOf1 { 
    year?: string;
    month?: string;
    day?: string;
    week?: string;
    day_of_week?: string;
    hour?: string;
    minute?: string;
    second?: string;
    end_date?: string | null;
    start_date?: string | null;
}

