/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScheduleConfigWhenOneOf { 
    weeks?: number;
    days?: number;
    hours?: number;
    minutes?: number;
    seconds?: number;
    end_date?: string | null;
    start_date?: string | null;
    jitter?: number | null;
}

