/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleConfigWhenOneOf1 } from './scheduleConfigWhenOneOf1';
import { ScheduleConfigWhenOneOf } from './scheduleConfigWhenOneOf';
import { ScheduleConfigWhenOneOf2 } from './scheduleConfigWhenOneOf2';


/**
 * @type ScheduleConfigWhen
 * @export
 */
export type ScheduleConfigWhen = ScheduleConfigWhenOneOf | ScheduleConfigWhenOneOf1 | ScheduleConfigWhenOneOf2;

