/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleConfig } from './scheduleConfig';
import { EventPayload } from './eventPayload';


export interface SchedulePayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    event_payload?: EventPayload | null;
    config?: ScheduleConfig;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled?: boolean;
    event_name?: string | null;
}

