/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleConfigWhen } from './scheduleConfigWhen';


export interface ScheduleConfig { 
    type?: ScheduleConfig.TypeEnum;
    when?: ScheduleConfigWhen;
}
export namespace ScheduleConfig {
    export const TypeEnum = {
        Interval: 'interval',
        Date: 'date',
        Cron: 'cron'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


