/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpendOverviewByDepartmentDataResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    department_id?: string;
    /**
     * String denoting the display name of a department. 
     */
    department_display_name?: string;
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * Percentage of spend which falls under this object/resource after filtering criteria is applied. 
     */
    percentage?: number;
    /**
     * Change in percentage of spend compared to spend in same time period one time interval ago, after filtering criteria is applied. 
     */
    change_percentage?: number;
}

