/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpendOverviewByCorporateCardDataResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    card_id?: string;
    /**
     * Specifies the masked number of the card. Add only masked card-numbers, last four digits of the card. 
     */
    card_number?: string;
    /**
     * String denoting the name on the corporate card. This can be null. 
     */
    card_holder_name?: string | null;
    /**
     * Unique nickname assigned to the card 
     */
    card_nickname?: string | null;
    /**
     * This id provided by Fyle to identify a user. This can be null if the corporate card is not assigned to any user. 
     */
    user_id?: string | null;
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * Percentage of spend which falls under this object/resource after filtering criteria is applied. 
     */
    percentage?: number;
    /**
     * Change in percentage of spend compared to spend in same time period one time interval ago, after filtering criteria is applied. 
     */
    change_percentage?: number;
}

