/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomField } from './customField';
import { LocationsInner } from './locationsInner';
import { DistanceUnit } from './distanceUnit';


export interface SpenderExpenseCheckMandatoryFieldsPayload { 
    /**
     * This represents the id of the expense.<br><br> _Note: This field is required when you are updating an already created expense and want to check it again for missing mandatory fields._ 
     */
    id?: string;
    /**
     * It signifies when this expense was made. This date cannot be in future.<br><br> _Note: This field is mandatory when you are creating an expense and want to check it again for missing mandatory fields._ 
     */
    spent_at?: any;
    /**
     * This value signifies the client from which this expense was created 
     */
    source?: string;
    /**
     * String denoting the name of the vendor to which the expense was made. 
     */
    merchant?: string | null;
    /**
     * The three-letter currency code following ISO standard <a href=\'https://www.iso.org/iso-4217-currency-codes.html\'>ISO 4217</a>. 
     */
    foreign_currency?: string | null;
    /**
     * Amount value of the object, in original currency i.e the currency in which the object was initially created. 
     */
    foreign_amount?: number | null;
    /**
     * The expense amount as claimed by user.<br><br> _Note: This field is mandatory when you are creating an expense and want to check it again for missing mandatory fields._ 
     */
    claim_amount?: number;
    purpose?: string;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    cost_center_id?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    category_id?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    project_id?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    source_account_id?: string | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    advance_wallet_id?: string | null;
    /**
     * Tax amount as setup by your organization. - _Note:_   - Tax amount cannot be greater than the expense amount. 
     */
    tax_amount?: number | null;
    /**
     * This id is provided by Fyle to identify an object. 
     */
    tax_group_id?: string | null;
    /**
     * This field marks whether a given expense is billable or not.
     */
    is_billable?: boolean | null;
    /**
     * This field marks whether a given expense is reimbursable or not.
     */
    is_reimbursable?: boolean | null;
    /**
     * Actual distance travelled by employee in travel related expenses.
     */
    distance?: number | null;
    distance_unit?: DistanceUnit | null;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    started_at?: string | null;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    ended_at?: string | null;
    /**
     * This field is applicable only for `Flight`, `Train`, `Bus` category. Index 0 holds onward journey travel class, index 1 holds return journey travel class. 
     */
    travel_classes?: Array<string> | null;
    /**
     * This field will be present for travel related categories. For travel between Place A to Place B, this array will contain two items. From location at array index i and To location at array index i+1. 
     */
    locations?: Array<LocationsInner> | null;
    /**
     * Custom fields 
     */
    custom_fields?: Array<CustomField>;
    /**
     * Number of files/reciepts attached to expense 
     */
    num_files?: number;
    /**
     * Invoice number of the expense. 
     */
    invoice_number?: string | null;
}
export namespace SpenderExpenseCheckMandatoryFieldsPayload {
}


