/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpendOverviewByMerchantDataResponse { 
    /**
     * String denoting the name of the vendor to which the expense was made. 
     */
    merchant_name?: string | null;
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * Percentage of spend which falls under this object/resource after filtering criteria is applied. 
     */
    percentage?: number;
    /**
     * Change in percentage of spend compared to spend in same time period one time interval ago, after filtering criteria is applied. 
     */
    change_percentage?: number;
}

