/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpendOverviewSummaryDataResponse { 
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * Representation of a point in time for which the sum of amount of expenses is calculated. Value depends of value of time_interval_granularity as follows : - for time_interval_granularity of `day`, value will be in date format YYYY-MM-DD. Example : 2021-01-01 - for time_interval_granularity of `month`, value will be in date format YYYY-MM. Example : 2021-01 - for time_interval_granularity of `quarter`, value will be in date format YYYY-QQ. Example : 2021-Q1 - for time_interval_granularity of `year`, value will be in date format YYYY. Example : 2021 
     */
    time_interval_marker?: string;
}

