/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpendOverviewByUserDataResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    user_id?: string;
    /**
     * String denoting the full name of an employee. 
     */
    user_full_name?: string;
    /**
     * An immutable field that represents the email address of the employee. Must be compliant with <a href=\'https://www.ietf.org/rfc/rfc822.txt\'>RFC 822.</a> 
     */
    user_email?: string;
    /**
     * amount of money 
     */
    amount?: number;
    /**
     * Percentage of spend which falls under this object/resource after filtering criteria is applied. 
     */
    percentage?: number;
    /**
     * Change in percentage of spend compared to spend in same time period one time interval ago, after filtering criteria is applied. 
     */
    change_percentage?: number;
}

