/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatementMappingsSuggestResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * Specifies the bank name of the statement. 
     */
    bank_name: string;
    /**
     * Specifies the representation of the the amount in the statement, if true then the amount represented by  positive sign are debits, and if false then the amount represented by negative sign are debits. 
     */
    is_debit_positive: boolean;
    /**
     * Specifies the header name of the transaction date column in the statement. 
     */
    transaction_date_column: string;
    /**
     * Specifies the header name of the merchant column in the statement. 
     */
    merchant_column: string;
    /**
     * Specifies the header name of the transaction id / unique id column in the statement. 
     */
    transaction_id_column: string | null;
    /**
     * Specifies the header name of the amount column in the statement. 
     */
    amount_column: string;
    /**
     * Specifies the mapping name. 
     */
    name: string;
    /**
     * Specifies the header name of the card number column in the statement. 
     */
    card_number_column: string;
    /**
     * Specifies the header name of the foreign amount column in the statement. 
     */
    foreign_amount_column: string | null;
    /**
     * Specifies the header name of the foreign currency column in the statement. 
     */
    foreign_currency_column: string | null;
    /**
     * Specifies the header name of the description column in the statement. 
     */
    description_column: string | null;
    /**
     * Specifies the header name of the post date column in the statement. 
     */
    post_date_column: string | null;
    /**
     * Helps to identify if a statement mapping got auto created or not 
     */
    is_auto_created: boolean;
    /**
     * Specifies the credit card network used by the card 
     */
    card_network: string | null;
}

