/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StateWiseGroupedStatsInner { 
    /**
     * Number of matching expenses in this state
     */
    count: number;
    /**
     * Sum of amounts for matching expenses in this state
     */
    total_amount: number;
    /**
     * Expense state
     */
    state: StateWiseGroupedStatsInner.StateEnum;
}
export namespace StateWiseGroupedStatsInner {
    export const StateEnum = {
        Complete: 'COMPLETE',
        Draft: 'DRAFT',
        ApproverPending: 'APPROVER_PENDING',
        Approved: 'APPROVED',
        PaymentPending: 'PAYMENT_PENDING',
        PaymentProcessing: 'PAYMENT_PROCESSING',
        Paid: 'PAID'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


