/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StateWiseGroupedStatsInner2 { 
    /**
     * Number of matching reports in this state.
     */
    count: number;
    /**
     * Sum of amounts for matching reports in this state.
     */
    total_amount: number;
    /**
     * Report state.
     */
    state: StateWiseGroupedStatsInner2.StateEnum;
    /**
     * Sum of reimbursable amount for ACH-failed reports, applicable only in PAYMENT_PROCESSING state.
     */
    failed_amount: number | null;
    /**
     * Count of ACH-failed reports, applicable only in PAYMENT_PROCESSING state.
     */
    failed_count: number | null;
    /**
     * Sum of reimbursable amount for processing reports, applicable only in PAYMENT_PROCESSING state.
     */
    processing_amount: number | null;
    /**
     * Count of processing reports, applicable only in PAYMENT_PROCESSING state.
     */
    processing_count: number | null;
    /**
     * Sum of reimbursable amounts for matching reports in this state.
     */
    reimbursable_amount: number;
}
export namespace StateWiseGroupedStatsInner2 {
    export const StateEnum = {
        ApproverPending: 'APPROVER_PENDING',
        Draft: 'DRAFT',
        PaymentProcessing: 'PAYMENT_PROCESSING',
        ApproverInquiry: 'APPROVER_INQUIRY',
        Approved: 'APPROVED',
        PaymentPending: 'PAYMENT_PENDING',
        Paid: 'PAID'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


