/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatementsResponseDuplicateStatementLineItemsInner } from './statementsResponseDuplicateStatementLineItemsInner';
import { UserPartialNullable } from './userPartialNullable';


export interface StatementsResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id: string;
    /**
     * The unique id of an user to which the object is associated. 
     */
    readonly creator_user_id: string;
    creator_user?: UserPartialNullable | null;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at: string;
    /**
     * Specifies the name of file uploaded by the user. 
     */
    file_name: string;
    /**
     * Specifies the size of file uploaded by the user. (The size is represented in bytes) 
     */
    file_size: number;
    /**
     * Number of debit transactions in the statement uploaded by the user. 
     */
    no_of_debit: number | null;
    /**
     * Number of credit transactions in the statement uploaded by the user. 
     */
    no_of_credit: number | null;
    /**
     * Number of transactions in the statement uploaded by the user. 
     */
    no_of_transactions: number;
    /**
     * This specifies headers of the statement uploaded by the user. 
     */
    all_statement_columns: Array<string>;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    start_date: string | null;
    /**
     * Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
     */
    end_date: string | null;
    /**
     * This specifies if the statement is complete duplicate of already uploaded statement or not. 
     */
    has_duplicate_statements: boolean | null;
    /**
     * Holds the list of statement_ids which are complete duplicate of the current statement
     */
    duplicate_statement_ids: Array<string>;
    /**
     * Indicates whether there are any line items in this statement are duplicates. 
     */
    has_duplicate_statement_line_items: boolean | null;
    duplicate_statement_line_items: Array<StatementsResponseDuplicateStatementLineItemsInner>;
    /**
     * Unique hash value that is used to identify the statement. 
     */
    unique_id: string;
    /**
     * File id of the uploaded statement. 
     */
    file_id: string | null;
    /**
     * Indicates whether the corporate card transactions are created out of the statement. 
     */
    is_processed: boolean;
    /**
     * Id of the mapping used to extract transaction from the statement. 
     */
    statement_mappings_id: string | null;
}

