/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StateWiseGroupedStatsInner1 { 
    /**
     * Number of matching advance requests in this state.
     */
    count: number;
    /**
     * Sum of amounts for matching advance requests in this state.
     */
    total_amount: number;
    /**
     * Advance request state.
     */
    state: StateWiseGroupedStatsInner1.StateEnum;
}
export namespace StateWiseGroupedStatsInner1 {
    export const StateEnum = {
        Draft: 'DRAFT',
        ApprovalPending: 'APPROVAL_PENDING',
        Approved: 'APPROVED',
        Cancelled: 'CANCELLED',
        Rejected: 'REJECTED',
        Paid: 'PAID',
        PulledBack: 'PULLED_BACK',
        SentBack: 'SENT_BACK'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


