/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatementsResponseDuplicateStatementLineItemsInner { 
    /**
     * Ids of the current statement line items which are duplicates
     */
    ids?: Array<string>;
    /**
     * Id of the existing duplicate statement 
     */
    duplicate_line_item_statement_id?: string | null;
}

