/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionsPayload { 
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled: boolean;
    /**
     * URL Endpoint for webhook 
     */
    webhook_url: string;
}

