/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tax group details. 
 */
export interface TaxGroup { 
    /**
     * Name of the tax group. 
     */
    name?: string | null;
    /**
     * Tax percentage. 
     */
    percentage?: number | null;
}

