/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaxGroupPayload { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id?: string;
    /**
     * Represents the name of the tax_group.
     */
    name: string;
    /**
     * percentage of tax levied.
     */
    percentage: number;
    /**
     * This indicates if the resource is enabled for use within the organisation. 
     */
    is_enabled: boolean;
    /**
     * This represents a code that is typically used for syncing with other systems. 
     */
    code?: string | null;
}

