/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The time duration by which to group expenses to aggregate sum of amount 
 */
export const TimeIntervalGranularity = {
    Day: 'day',
    Month: 'month',
    Quarter: 'quarter',
    Year: 'year'
} as const;
export type TimeIntervalGranularity = typeof TimeIntervalGranularity[keyof typeof TimeIntervalGranularity];

