/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const VehicleType = {
    Bicycle: 'bicycle',
    ElectricCar: 'electric_car',
    FourWheeler: 'four_wheeler',
    FourWheeler1: 'four_wheeler1',
    FourWheeler2: 'four_wheeler2',
    FourWheeler3: 'four_wheeler3',
    FourWheeler4: 'four_wheeler4',
    TwoWheeler: 'two_wheeler'
} as const;
export type VehicleType = typeof VehicleType[keyof typeof VehicleType];

