/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VirtualCardResponse { 
    /**
     * This id is provided by Fyle to identify an object. 
     */
    id: string;
    /**
     * The unique id of the Organization to which the object is associated. 
     */
    readonly org_id: string;
    /**
     * The unique id of an user to whom the card is assigned 
     */
    user_id: string;
    /**
     * Signifies when this object was created in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    created_at: string;
    /**
     * Signifies when this object was updated in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). 
     */
    updated_at: string;
    /**
     * Specifies the last 5 digits of the card. 
     */
    last_five: string;
    /**
     * Status of the virtual card 
     */
    state: VirtualCardResponse.StateEnum | null;
    /**
     * Specifies the expiry date of the card. 
     */
    expiry_date: string | null;
    /**
     * The unique id of the amex account to which the card is assigned 
     */
    amex_account_id: string;
    /**
     * Specifies the valid from date of the card, ie from when the card would be active. 
     */
    valid_from_at: string | null;
    /**
     * Specifies the valid till date of the card, ie till when the card would be active. 
     */
    valid_till_at: string | null;
    /**
     * The unique id of an user who created the card. 
     */
    creator_user_id: string;
    /**
     * This id refers to the virtual card user to whom the virtual card is assigned. 
     */
    virtual_card_user_id: string;
    /**
     * Represents user defined nick name associated with the virtual card for easier recognition. 
     */
    nick_name: string;
}
export namespace VirtualCardResponse {
    export const StateEnum = {
        Active: 'ACTIVE',
        Preactive: 'PREACTIVE',
        Inactive: 'INACTIVE',
        Expired: 'EXPIRED',
        Deleted: 'DELETED',
        Used: 'USED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


