/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VirtualCardsShowCardDetailsResponse { 
    /**
     * Full card number of the virtual card 
     */
    full_card_number: string;
    /**
     * Specifies the expiry date of the card. 
     */
    expiry_date: string | null;
    /**
     * CVV of the virtual card 
     */
    cvv: string;
}

