/**
 * Admin APIs
 *
 * Contact: support@fylehq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VirtualCardsGetCurrentBalanceResponse { 
    /**
     * The current balance amount of the virtual card 
     */
    current_amount: number;
}

