openapi: 3.0.3
info:
  version: '3.0'
  title: Common APIs
  contact:
    name: Integrations
    email: platform-beta@fylehq.com
servers:
  - url: 'https://$CLUSTER_DOMAIN$/platform/v1'
    description: Staging Server
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            '*': 'Grant all actions'

tags:
  - name: Currencies
    description: |
      These APIs gives you list of currencies supported by Fyle and their exchange rates.
  - name: Data Extraction
    description: |
      These APIs gives the expense relevant data from the reciepts.
  - name: Places
    description: |
      These APIs gives the places suggestions and geographic data of a place.

paths:
  /common/places/autocomplete:
    $ref: 'paths/common@places@autocomplete.yaml'
  /common/places:
    $ref: 'paths/common@places.yaml'
  /common/currency/list:
    $ref: 'paths/common@currencies.yaml'
  /common/expense_extract/v1:
    $ref: 'paths/common@expense_extract@v1.yaml'
