spender_automate_report_submission_next_at_out:
  type: object
  required:
    - next_at
  properties:
    next_at:
      type: string
      format: date-time
      nullable: True
      description:
        Signifies the time when the next automate report submission will run for the organization. Date-time in [ISO8601 format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
      example: '2021-06-01T13:14:54.804+00:00'
