automate_report_submission_in:
  type: object
  properties:
    id:
      $ref: './fields.yaml#/id_string'
    description:
      type: string
      description: |
        A human readable identifier for the automate report submission
      example: 'Expense Reports will be submitted automatically for approval on the Last Day, 7th and 24th of every month.'
    schedule_config:
      $ref: './fields.yaml#/automate_report_submission_schedule_config'

automate_report_submission_out:
  type: object
  required:
    - id
    - description
    - schedule_config
    - org_id
    - created_at
    - updated_at
    - creator_user_id
    - creator_user
  properties:
    id:
      $ref: './fields.yaml#/id_string'
    description:
      type: string
      description: |
        A human readable identifier for the automate report submission
      example: 'Expense Reports will be submitted automatically for approval on the Last Day, 7th and 24th of every month.'
    schedule_config:
      $ref: './fields.yaml#/automate_report_submission_schedule_config'
    org_id:
      $ref: './fields.yaml#/org_id'
    created_at:
      $ref: './fields.yaml#/created_at'
    updated_at:
      $ref: './fields.yaml#/updated_at'
    creator_user_id:
      $ref: './fields.yaml#/user_id'
    creator_user:
      $ref: ./user.yaml#/user_out_embed

delete_automate_report_submission_in:
  type: object
  required:
    - id
  properties:
    id:
      $ref: './fields.yaml#/id_string'
