dependent_expense_field_values_preview_out:
  type: object
  additionalProperties: false
  properties:
    org_id:
      $ref: ./fields.yaml#/org_id
    parent_expense_field_id:
      type: integer
      description: |
        This specifies the `id` of the parent expense field.
      example: 1234
    expense_field_id:
      type: integer
      description: |
        This specifies the `id` of the dependent expense field.
      example: 5678
    parent_expense_field_value:
      type: string
      description: |
        This specifies the text value of the parent expense field.
      example: Project 1
    expense_field_values:
      type: array
      nullable: false
      description: |
        This specifies the text values of the dependent expense field upto 20 items.
      items:
        type: string
        nullable: false
        description: |
          This specifies the text value of the dependent expense field.
        example: Cost Code 1
    is_enabled:
      $ref: ./fields.yaml#/is_enabled
