dependent_expense_field_values_out:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    org_id:
      $ref: ./fields.yaml#/org_id
    created_at:
      $ref: ./fields.yaml#/created_at
    updated_at:
      $ref: ./fields.yaml#/updated_at
    parent_expense_field_id:
      type: integer
      description: |
        This specifies the `id` of the parent expense field.
      example: 1234
    expense_field_id:
      type: integer
      description: |
        This specifies the `id` of the dependent expense field.
      example: 5678
    parent_expense_field_value:
      type: string
      description: |
        This specifies the text value of the parent expense field.
      example: Project 1
    expense_field_value:
      type: string
      description: |
        This specifies the text value of the dependent expense field.
      example: Cost Code 1
    is_enabled:
      $ref: ./fields.yaml#/is_enabled

dependent_expense_field_values_in:
  type: object
  additionalProperties: False
  required:
    - parent_expense_field_id
    - expense_field_id
    - parent_expense_field_value
    - expense_field_value
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    org_id:
      $ref: ./fields.yaml#/org_id
    created_at:
      $ref: ./fields.yaml#/created_at
    updated_at:
      $ref: ./fields.yaml#/updated_at
    parent_expense_field_id:
      type: integer
      description: |
        This specifies the `id` of the parent expense field.
      example: 1234
    expense_field_id:
      type: integer
      description: |
        This specifies the `id` of the dependent expense field.
      example: 5678
    parent_expense_field_value:
      type: string
      description: |
        This specifies the text value of the parent expense field.
      example: Project 1
    expense_field_value:
      type: string
      description: |
        This specifies the text value of the dependent expense field.
      example: Cost Code 1
    is_enabled:
      $ref: ./fields.yaml#/is_enabled
