dependent_expense_field_values_upload_out:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    org_id:
      $ref: ./fields.yaml#/org_id
    created_at:
      $ref: ./fields.yaml#/created_at
    updated_at:
      $ref: ./fields.yaml#/updated_at
    parent_expense_field_id:
      type: integer
      description: |
        This specifies the `id` of the parent expense field.
      example: 1234
    expense_field_id:
      type: integer
      description: |
        This specifies the `id` of the dependent expense field.
      example: 5678
    file_id:
      type: string
      nullable: false
      description: |
        File `id` of the uploaded excel file.
      example: fiit3pX9gzzP
    error_file_id:
      type: string
      nullable: true
      description: |
        File `id` of the error excel file generated after processing the uploaded file.
      example: fiit3pX9gzzQ
    state:
      type: string
      enum:
        - PENDING
        - PROCESSING
        - SUCCESS
        - ERROR
      example: PENDING

dependent_expense_field_values_upload_in:
  type: object
  additionalProperties: false
  required:
    - parent_expense_field_id
    - expense_field_id
    - file_id
  properties:
    parent_expense_field_id:
      type: integer
      description: |
        This specifies the `id` of the parent expense field.
      example: 1234
    expense_field_id:
      type: integer
      description: |
        This specifies the `id` of the dependent expense field.
      example: 5678
    file_id:
      type: string
      nullable: false
      description: |
        File `id` of the uploaded excel file.
      example: fiit3pX9gzzP
