spender_employee_settings_out:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: './fields.yaml#/id_string'
      example: ous7FnPJtFRmN
      description: Unique identifier for the employee settings
    employee_id:
      $ref: './fields.yaml#/id_string'
      example: ouLdnA486RYD
      description: Unique identifier of the employee
    org_id:
      $ref: './fields.yaml#/org_id'
      example: org123
      description: Unique identifier of the organization
    created_at:
      $ref: './fields.yaml#/created_at'
      example: '2019-10-18T07:01:55.756Z'
      description: Timestamp when the settings were created
    updated_at:
      $ref: './fields.yaml#/updated_at'
      example: '2025-04-20T04:14:26.820Z'
      description: Timestamp when the settings were last updated
    category_ids:
      type: array
      items:
        $ref: './fields.yaml#/id_string'
      example: []
      description: List of category ids that the employee has access to
    cost_center_ids:
      type: array
      items:
        $ref: './fields.yaml#/id_string'
      example: []
      description: List of cost centers that the employee has access to
    project_ids:
      type: array
      items:
        $ref: './fields.yaml#/id_string'
      example: []
      description: List of projects that the employee has access to
    per_diem_rate_ids:
      type: array
      items:
        $ref: './fields.yaml#/id_string'
      example: []
      description: List of per diem rates that the employee has access to
    mileage_rate_ids:
      type: array
      items:
        $ref: './fields.yaml#/id_string'
      example: []
      description: List of mileage rate ids that the employee has access to
    insta_fyle_settings:
      type: object
      nullable: true
      additionalProperties: false
      description: Settings for InstaFyle receipt scanning and data extraction
      properties:
        allowed:
          type: boolean
          nullable: true
          example: true
          description: Whether InstaFyle is allowed for the employee
        enabled:
          type: boolean
          nullable: true
          example: true
          description: Whether InstaFyle is enabled for the employee
        static_camera_overlay_enabled:
          type: boolean
          nullable: true
          example: true
          description: Whether static camera overlay is enabled for receipt scanning
        extract_fields:
          type: array
          nullable: true
          items:
            type: string
          example: ["AMOUNT", "CURRENCY", "CATEGORY", "TXN_DT"]
          description: List of fields to extract from receipts
    notification_settings:
      type: object
      nullable: true
      additionalProperties: false
      description: Settings for email and push notifications
      properties:
        email_allowed:
          type: boolean
          nullable: true
          example: true
          description: Whether email notifications are allowed
        email_enabled:
          type: boolean
          nullable: true
          example: true
          description: Whether email notifications are enabled
        email_unsubscribed_events:
          type: array
          nullable: true
          items:
            type: string
          example: []
          description: List of events for which email notifications are unsubscribed
        push_allowed:
          type: boolean
          nullable: true
          example: true
          description: Whether push notifications are allowed
        push_enabled:
          type: boolean
          nullable: true
          example: true
          description: Whether push notifications are enabled
        push_unsubscribed_events:
          type: array
          nullable: true
          items:
            type: string
          example: ["EADVANCE_REQUESTS_CREATED", "EADVANCE_REQUESTS_UPDATED", "EADVANCE_REQUESTS_INQUIRY"]
          description: List of events for which push notifications are unsubscribed
        notify_user:
          type: boolean
          nullable: true
          example: true
          description: Whether to notify the user about events
        notify_delegatee:
          type: boolean
          nullable: true
          example: true
          description: Whether to notify the delegatee about events
    mileage_settings:
      type: object
      nullable: true
      additionalProperties: false
      description: Settings for mileage tracking and rates
      properties:
        mileage_rate_labels:
          type: object
          nullable: true
          example: null
          description: Labels for different mileage rates
        annual_mileage_of_user_before_joining_fyle:
          type: object
          nullable: true
          example: {}
          description: Annual mileage limit for user before joining Fyle
    expense_form_autofills:
      type: object
      nullable: true
      additionalProperties: false
      description: Settings for automatic form filling in expenses
      properties:
        allowed:
          type: boolean
          nullable: true
          example: true
          description: Whether expense form autofill is allowed
        enabled:
          type: boolean
          nullable: true
          example: true
          description: Whether expense form autofill is enabled
    data_extractor_settings:
      type: object
      nullable: true
      additionalProperties: false
      description: Settings for data extraction from receipts
      properties:
        allowed:
          type: boolean
          nullable: true
          example: true
          description: Whether data extraction is allowed
        enabled:
          type: boolean
          nullable: true
          example: true
          description: Whether data extraction is enabled
    in_app_chat_settings:
      type: object
      nullable: true
      additionalProperties: false
      description: Settings for in-app chat functionality
      properties:
        allowed:
          type: boolean
          nullable: true
          example: true
          description: Whether in-app chat is allowed
        enabled:
          type: boolean
          nullable: true
          example: true
          description: Whether in-app chat is enabled
        restore_id:
          type: string
          nullable: true
          example: null
          description: ID for restoring chat session
    payment_mode_settings:
      type: object
      nullable: true
      additionalProperties: false
      description: Settings for payment modes
      properties:
        allowed:
          type: boolean
          nullable: true
          example: true
          description: Whether payment mode selection is allowed
        enabled:
          type: boolean
          nullable: true
          example: true
          description: Whether payment mode selection is enabled
        allowed_payment_modes:
          type: array
          nullable: true
          items:
            type: string
          example: ["PERSONAL_ACCOUNT", "COMPANY_ACCOUNT"]
          description: List of payment modes allowed for the employee
    locale:
      type: object
      nullable: true
      additionalProperties: false
      description: Settings for user's locale and timezone
      properties:
        timezone:
          type: string
          nullable: true
          example: "Asia/Kolkata"
          description: User's timezone
        abbreviation:
          type: string
          nullable: true
          example: "IST"
          description: Timezone abbreviation
        offset:
          type: string
          nullable: true
          example: "05:30:00"
          description: Timezone offset from UTC
    is_personal_cards_enabled:
      type: boolean
      example: true
      description: Whether personal card usage is enabled
    default_project_id:
      type: string
      nullable: true
      example: null
      description: Default project ID for expenses
    default_payment_mode:
      type: string
      nullable: true
      example: null
      description: Default payment mode for expenses
    default_vehicle_type:
      type: string
      nullable: true
      example: null
      description: Default vehicle type for mileage expenses

spender_employee_settings_in:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: './fields.yaml#/id_string'
      description: Unique identifier for the employee settings (optional)
    employee_id:
      $ref: './fields.yaml#/id_string'
      description: Unique identifier of the employee (optional)
    cost_center_ids:
      type: array
      items:
        $ref: './fields.yaml#/id_string'
      description: List of cost centers that the employee has access to
    project_ids:
      type: array
      items:
        $ref: './fields.yaml#/id_string'
      description: List of projects that the employee has access to
    per_diem_rate_ids:
      type: array
      items:
        $ref: './fields.yaml#/id_string'
      description: List of per diem rates that the employee has access to
    mileage_rate_ids:
      type: array
      items:
        $ref: './fields.yaml#/id_string'
      description: List of mileage rates that the employee has access to
    category_ids:
      type: array
      items:
        $ref: './fields.yaml#/id_string'
      description: List of categories that the employee has access to
    insta_fyle_settings:
      type: object
      additionalProperties: false
      description: Settings for InstaFyle receipt scanning and data extraction
      properties:
        allowed:
          type: boolean
          description: Whether InstaFyle is allowed for the employee
        enabled:
          type: boolean
          description: Whether InstaFyle is enabled for the employee
        static_camera_overlay_enabled:
          type: boolean
          description: Whether static camera overlay is enabled for receipt scanning
        extract_fields:
          type: array
          items:
            type: string
          description: List of fields to extract from receipts
    notification_settings:
      type: object
      additionalProperties: false
      description: Settings for email and push notifications
      properties:
        email_allowed:
          type: boolean
          description: Whether email notifications are allowed
        email_enabled:
          type: boolean
          description: Whether email notifications are enabled
        email_unsubscribed_events:
          type: array
          items:
            type: string
          description: List of events for which email notifications are unsubscribed
        push_allowed:
          type: boolean
          description: Whether push notifications are allowed
        push_enabled:
          type: boolean
          description: Whether push notifications are enabled
        push_unsubscribed_events:
          type: array
          items:
            type: string
          description: List of events for which push notifications are unsubscribed
        notify_user:
          type: boolean
          description: Whether to notify the user about events
        notify_delegatee:
          type: boolean
          description: Whether to notify the delegatee about events
    expense_form_autofills:
      type: object
      additionalProperties: false
      description: Settings for automatic form filling in expenses
      properties:
        allowed:
          type: boolean
          description: Whether expense form autofill is allowed
        enabled:
          type: boolean
          description: Whether expense form autofill is enabled
    data_extractor_settings:
      type: object
      additionalProperties: false
      description: Settings for data extraction from receipts
      properties:
        allowed:
          type: boolean
          description: Whether data extraction is allowed
        enabled:
          type: boolean
          description: Whether data extraction is enabled
    in_app_chat_settings:
      type: object
      additionalProperties: false
      description: Settings for in-app chat functionality
      properties:
        allowed:
          type: boolean
          description: Whether in-app chat is allowed
        enabled:
          type: boolean
          description: Whether in-app chat is enabled
        restore_id:
          type: string
          nullable: true
          description: ID for restoring chat session
    payment_mode_settings:
      type: object
      additionalProperties: false
      description: Settings for payment modes
      properties:
        allowed:
          type: boolean
          description: Whether payment mode selection is allowed
        enabled:
          type: boolean
          description: Whether payment mode selection is enabled
        allowed_payment_modes:
          type: array
          items:
            type: string
          description: List of payment modes allowed for the employee
    is_personal_cards_enabled:
      type: boolean
      description: Whether personal card usage is enabled
    default_project_id:
      type: string
      nullable: true
      description: Default project ID for expenses
    default_payment_mode:
      type: string
      nullable: true
      description: Default payment mode for expenses
    default_vehicle_type:
      type: string
      nullable: true
      description: Default vehicle type for mileage expenses
