feature_config_out:
  type: object
  additionalProperties: false
  properties:
    org_id:
      $ref: ./fields.yaml#/org_id
    user_id:
      $ref: ./fields.yaml#/user_id
    created_at:
      $ref: ./fields.yaml#/created_at
    updated_at:
      $ref: ./fields.yaml#/updated_at
    target_client:
      type: string
      nullable: false
      description: |
        This specifies the target client of the feature config.
      example: WEBAPP
    feature:
      type: string
      nullable: false
      description: |
        This specifies the feature name.
      example: ADMIN_EXPENSES
    sub_feature:
      type: string
      nullable: true
      description: |
        This specifies the sub feature name.
      example: ALL_EXPENSES
    key:
      type: string
      nullable: false
      description: |
        This specifies the key of the feature config.
      example: MANAGE_COLUMNS
    value:
      anyOf:
        - $ref: './fields.yaml#/any_type'
        - $ref: './fields.yaml#/null_field'
      nullable: true
      description: |
        This specifies the value of the feature config.
      example:
        columns:
          - id: Date
            is_visible: true
            order: 1
    is_shared:
      type: boolean
      nullable: false
      description: |
        This specifies whether the feature config is shared or not.
      example: true

feature_config_in:
  type: object
  additionalProperties: false
  required:
    - target_client
    - feature
    - key
    - value
    - is_shared
  properties:
    target_client:
      type: string
      nullable: false
      description: |
        This specifies the target client of the feature config.
      example: WEBAPP
    feature:
      type: string
      nullable: false
      description: |
        This specifies the feature name.
      example: ADMIN_EXPENSES
    sub_feature:
      type: string
      nullable: true
      description: |
        This specifies the sub feature name.
      example: ALL_EXPENSES
    key:
      type: string
      nullable: false
      description: |
        This specifies the key of the feature config.
      example: MANAGE_COLUMNS
    value:
      anyOf:
        - $ref: './fields.yaml#/any_type'
        - $ref: './fields.yaml#/null_field'
      nullable: true
      description: |
        This specifies the value of the feature config.
      example:
        columns:
          - id: Date
            is_visible: true
            order: 1
    is_shared:
      type: boolean
      nullable: false
      description: |
        This specifies whether the feature config is shared or not.
      example: true

feature_config_spender_in:
  type: object
  additionalProperties: false
  required:
    - target_client
    - feature
    - key
    - value
  properties:
    target_client:
      type: string
      nullable: false
      description: |
        This specifies the target client of the feature config.
      example: WEBAPP
    feature:
      type: string
      nullable: false
      description: |
        This specifies the feature name.
      example: ADMIN_EXPENSES
    sub_feature:
      type: string
      nullable: true
      description: |
        This specifies the sub feature name.
      example: ALL_EXPENSES
    key:
      type: string
      nullable: false
      description: |
        This specifies the key of the feature config.
      example: MANAGE_COLUMNS
    value:
      anyOf:
        - $ref: './fields.yaml#/any_type'
        - $ref: './fields.yaml#/null_field'
      nullable: true
      description: |
        This specifies the value of the feature config.
      example:
        columns:
          - id: Date
            is_visible: true
            order: 1