feature_config_out:
  type: object
  additionalProperties: false
  properties:
    org_id:
      $ref: ./fields.yaml#/org_id
    user_id:
      $ref: ./fields.yaml#/user_id
    created_at:
      $ref: ./fields.yaml#/created_at
    updated_at:
      $ref: ./fields.yaml#/updated_at
    key:
      type: string
      nullable: false
      description: |
        This specifies the key of the feature configuration.
      example: COMPANY_EXPENSE_MANAGE_COLUMNS
    value:
      anyOf:
        - $ref: './fields.yaml#/any_type'
        - $ref: './fields.yaml#/null_field'
      nullable: true
      description: |
        This specifies the value of the feature configuration.
      example: |
        {
          "columns": [
            {
              "id": "Date",
              "is_visible": true,
              "order": 1
            }
          ]
        }

feature_config_in:
  type: object
  additionalProperties: false
  required:
    - key
    - value
  properties:
    key:
      type: string
      nullable: false
      description: |
        This specifies the key of the feature configuration.
      example: COMPANY_EXPENSE_MANAGE_COLUMNS
    value:
      anyOf:
        - $ref: './fields.yaml#/any_type'
        - $ref: './fields.yaml#/null_field'
      nullable: true
      description: |
        This specifies the value of the feature configuration key.
      example: |
        {
          "columns": [
            {
              "id": "Date",
              "is_visible": true,
              "order": 1
            }
          ]
        }
