logo_file_generate_download_url_action_out:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: './fields.yaml#/id_string'
    name:
      type: string
      description: |
        Name of the uploaded file.
      example: uber_expenses_vmrpw.pdf
    content_type:
      type: string
      example: 'image/png'
    download_url:
      type: string
      description: |
        Link to download this file
