page_configuration_out:
  type: object
  additionalProperties: false
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    org_id:
      $ref: ./fields.yaml#/org_id
    user_id:
      $ref: ./fields.yaml#/org_id
    created_at:
      $ref: ./fields.yaml#/created_at
    updated_at:
      $ref: ./fields.yaml#/updated_at
    key:
      type: string
      description: |
        This specifies the key of the page configuration.
      example: COMPANY_EXPENSE_MANAGE_COLUMNS
    value:
      oneOf:
        - type: string
        - type: integer
        - type: number
        - type: boolean
        - type: object
        - type: array
      description: |
        This specifies the value of the page configuration.
      example: |
        {
          "columns": [
            {
              "id": "Date",
              "is_visible": true,
              "order": 1
            }
          ]
        }

page_configuration_in:
  type: object
  additionalProperties: false
  required:
    - key
    - value
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    key:
      type: string
      description: |
        This specifies the key of the page configuration.
      example: COMPANY_EXPENSE_MANAGE_COLUMNS
    value:
      oneOf:
        - type: string
        - type: integer
        - type: number
        - type: boolean
        - type: object
        - type: array
      description: |
        This specifies the value of the page configuration.
      example: |
        {
          "columns": [
            {
              "id": "Date",
              "is_visible": true,
              "order": 1
            }
          ]
        }
