project_out:
  type: object
  additionalProperties: False
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    org_id:
      $ref: ./fields.yaml#/org_id
    created_at:
      $ref: ./fields.yaml#/created_at
    updated_at:
      $ref: ./fields.yaml#/updated_at
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      type: string
      nullable: true
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    code:
      $ref: ./fields.yaml#/code
    display_name:
      type: string
      maxLength: 513
      description: |
        This is a combination of name and sub_project separated by a / and spaces.
        In case if no sub_project is present it is same as name of the project.
      example: Fast and Furious / Formula One

    description:
      $ref: ./fields.yaml#/description
    is_enabled:
      $ref: ./fields.yaml#/is_enabled
    category_ids:
      type: array
      nullable: True
      description: |
        Has the list of all category ids that are applicable for this project.
      items:
        type: integer

project_out_embed:
  type: object
  nullable: true
  additionalProperties: False
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      type: string
      nullable: true
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    code:
      $ref: ./fields.yaml#/code

project_in:
  type: object
  additionalProperties: False
  required:
    - name
    - sub_project
    - category_ids
    - is_enabled
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      nullable: True
      type: string
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    code:
      $ref: ./fields.yaml#/code
    description:
      $ref: ./fields.yaml#/description
    is_enabled:
      $ref: ./fields.yaml#/is_enabled
    category_ids:
      type: array
      nullable: True
      description: |
        Has the list of all category ids that are applicable for this project.
      items:
        type: integer
        example: 16570
    fyler_user_ids:
      $ref: './fields.yaml#/fyler_user_ids'

admin_project_out:
  allOf:
    - $ref: '#/project_out'
    - type: object
      properties:
        fyler_user_ids:
          $ref: './fields.yaml#/fyler_user_ids' 