project_out:
  type: object
  additionalProperties: False
  properties:
    id:
      allOf:
        - $ref: './fields.yaml#/id_integer'
      example: 2222
    org_id:
      $ref: ./fields.yaml#/org_id
    created_at:
      $ref: ./fields.yaml#/created_at
    updated_at:
      $ref: ./fields.yaml#/updated_at
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      type: string
      nullable: true
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    code:
      type: string
      maxLength: 255
      nullable: true
      description: |
        This represents the code of project.
      example: FF-032
    display_name:
      type: string
      maxLength: 513
      description: |
        This is a combination of name and sub_project separated by a / and spaces.
        In case if no sub_project is present it is same as name of the project.
      example: Fast and Furious / Formula One

    description:
      $ref: ./fields.yaml#/description
    is_enabled:
      $ref: ./fields.yaml#/is_enabled
    category_ids:
      type: array
      description: |
        Has the list of all category ids that are applicable for this project.
      items:
        type: integer

project_out_embed:
  type: object
  additionalProperties: False
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
      example: 3333
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      type: string
      nullable: true
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    code:
      type: string
      nullable: true
      maxLength: 255
      description: |
        This represents the code of project.
      example: FF-032

project_in:
  type: object
  additionalProperties: False
  required: ["name", "sub_project", "category_ids"]
  properties:
    id:
      $ref: './fields.yaml#/id_string'
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      type: string
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    code:
      nullable: true
      type: string
      maxLength: 255
      description: |
        This represents the code of project.
      example: FF-032
    description:
      $ref: ./fields.yaml#/description
    is_enabled:
      $ref: ./fields.yaml#/is_enabled
    category_ids:
      type: array
      description: |
        Has the list of all category ids that are applicable for this project.
      items:
        type: integer
        example: 16570
