project_out:
  type: object
  additionalProperties: False
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    org_id:
      $ref: ./fields.yaml#/org_id
    created_at:
      $ref: ./fields.yaml#/created_at
    updated_at:
      $ref: ./fields.yaml#/updated_at
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      type: string
      nullable: true
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    code:
      $ref: ./fields.yaml#/code
    display_name:
      type: string
      maxLength: 513
      description: |
        This is a combination of name and sub_project separated by a / and spaces.
        In case if no sub_project is present it is same as name of the project.
      example: Fast and Furious / Formula One
    description:
      $ref: ./fields.yaml#/description
    is_enabled:
      $ref: ./fields.yaml#/is_enabled
      items:
        type: integer

project_out_embed:
  type: object
  nullable: true
  additionalProperties: False
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      type: string
      nullable: true
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    code:
      $ref: ./fields.yaml#/code
    display_name:
      type: string 
      example: Fast and Furious / Formula One
      description: |
        This is a combination of name and sub_project separated by a / and spaces.
        In case if no sub_project is present it is same as name of the project.

project_in:
  type: object
  additionalProperties: False
  required:
    - name
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      nullable: True
      type: string
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    code:
      $ref: ./fields.yaml#/code
    description:
      $ref: ./fields.yaml#/description
    is_enabled:
      $ref: ./fields.yaml#/is_enabled
    restricted_spender_user_ids:
      $ref: './fields.yaml#/restricted_spender_user_ids'
    approver_user_ids:
      $ref: './fields.yaml#/approver_user_ids'

admin_approver_project_out:
  type: object
  additionalProperties: False
  properties:
    id:
      $ref: './fields.yaml#/id_integer'
    org_id:
      $ref: ./fields.yaml#/org_id
    created_at:
      $ref: ./fields.yaml#/created_at
    updated_at:
      $ref: ./fields.yaml#/updated_at
    name:
      type: string
      maxLength: 255
      description: Represents the name of the project.
      example: Fast and Furious
    sub_project:
      type: string
      nullable: true
      maxLength: 255
      description: Represents the name of the sub_project.
      example: Formula One
    code:
      $ref: ./fields.yaml#/code
    display_name:
      type: string
      maxLength: 513
      description: |
        This is a combination of name and sub_project separated by a / and spaces.
        In case if no sub_project is present it is same as name of the project.
      example: Fast and Furious / Formula One
    description:
      $ref: ./fields.yaml#/description
    is_enabled:
      $ref: ./fields.yaml#/is_enabled
    restricted_spender_user_ids:
      $ref: './fields.yaml#/restricted_spender_user_ids'
    approver_user_ids:
      $ref: './fields.yaml#/approver_user_ids'
    approver_users:
      type: array
      nullable: True
      items:
        $ref: ./user.yaml#/user_out_embed
      description: |
        List of users who are approvers for this project.
